# Airline Operations & Disruption Intelligence
## 01 — Data Understanding

### Objective

The objective of this notebook is to understand the structure, content,
scope, and business meaning of the raw flight operations dataset before
performing any data cleaning or exploratory analysis.

### Important Rule

At this stage, we will only understand and inspect the data.

We will NOT:
- Remove rows
- Fill missing values
- Remove duplicates
- Remove outliers
- Create analytical features
- Modify business values

Data cleaning will be performed in a separate stage.

## 1. Business Context

Flight delays, cancellations, and diversions can affect airline operations,
airport capacity, passenger experience, and overall network performance.

This project aims to understand the operational patterns behind flight
disruptions and identify the airlines, airports, routes, and time periods
where disruption is more common.

The analysis will later combine flight operations data with airport reference
and historical weather data.

## 2. Business Questions

The analysis will eventually answer questions such as:

1. What is the overall flight delay rate?
2. Which airlines have the highest delay rates?
3. Which airports experience the most delays?
4. Which routes have higher disruption rates?
5. Does the time of day affect delays?
6. Does airport congestion relate to delays?
7. Does weather relate to flight delays?
8. What are the major causes of delays?
9. Can high-risk flights be identified before departure?

## 3. Import Required Libraries

We use Pandas for data inspection and NumPy for basic numerical operations.

In [13]:
import pandas as pd
import numpy as np

## 4. Load the Dataset

The January, February, and March 2026 BTS flight datasets were previously
combined into a single dataset.

The original monthly files are preserved separately in the raw-data folder.

In [14]:
from pathlib import Path

# Define the location of the processed combined dataset
data_path = Path(r"D:\Data Analyst\EXCEL\api\flights_2026.csv")

# Load the combined dataset
flights = pd.read_csv(data_path)

print("Dataset loaded successfully.")

Dataset loaded successfully.

## 5. Dataset Size

First, we check the number of rows and columns.

- Each row represents one reported flight operation.
- Each column represents an attribute describing that flight.

In [15]:
rows, columns = flights.shape

print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 1847242
Number of columns: 44

In [16]:
flights.shape

(1847242, 44)

## 6. Preview the Dataset

We inspect the first few records to understand how the data is structured
and what a typical flight record looks like.

In [17]:
flights.head()

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,0,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,1,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,3,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,4,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

## 7. Check the End of the Dataset

We inspect the last records to make sure the dataset contains the expected
range of observations.

In [18]:
flights.tail()

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
1847237,1847237,2026,1,3,31,2,2026-03-31,WN,WN,19393,...,0.0,80.0,85.0,54.0,402.0,0.0,0.0,5.0,0.0,16.0
1847238,1847238,2026,1,3,31,2,2026-03-31,WN,WN,19393,...,0.0,140.0,143.0,126.0,1020.0,NaN,NaN,NaN,NaN,NaN
1847239,1847239,2026,1,3,31,2,2026-03-31,WN,WN,19393,...,0.0,145.0,141.0,125.0,930.0,NaN,NaN,NaN,NaN,NaN
1847240,1847240,2026,1,3,31,2,2026-03-31,WN,WN,19393,...,0.0,95.0,102.0,85.0,395.0,NaN,NaN,NaN,NaN,NaN
1847241,1847241,2026,1,3,31,2,2026-03-31,WN,WN,19393,...,0.0,130.0,118.0,100.0,794.0,NaN,NaN,NaN,NaN,NaN

## 8. Random Sample

The first rows may not represent the entire dataset.

A random sample gives us a quick view of records from different parts
of the dataset.

In [19]:
flights.sample(5, random_state=42)

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
454974,454974,2026,1,1,24,6,2026-01-24,AA,AA_CODESHARE,19805,...,0.0,86.0,NaN,NaN,383.0,NaN,NaN,NaN,NaN,NaN
1660385,1660385,2026,1,3,23,1,2026-03-23,DL,DL_CODESHARE,19790,...,0.0,75.0,77.0,38.0,224.0,NaN,NaN,NaN,NaN,NaN
1816002,1816002,2026,1,3,30,1,2026-03-30,DL,DL_CODESHARE,19790,...,0.0,117.0,NaN,NaN,479.0,NaN,NaN,NaN,NaN,NaN
417415,417415,2026,1,1,22,4,2026-01-22,AS,AS_CODESHARE,19930,...,0.0,130.0,131.0,106.0,605.0,NaN,NaN,NaN,NaN,NaN
173252,173252,2026,1,1,9,5,2026-01-09,DL,DL_CODESHARE,19790,...,0.0,105.0,123.0,63.0,390.0,NaN,NaN,NaN,NaN,NaN

## 9. Column Names

The dataset contains 44 variables covering:

- Flight date and calendar information
- Airline information
- Origin and destination airports
- Scheduled and actual departure/arrival times
- Delay information
- Cancellation and diversion information
- Flight operational metrics
- Delay causes

- Data types

In [20]:
for i, column in enumerate(flights.columns, start=1):
    print(i, column)

1 Unnamed: 0
2 YEAR
3 QUARTER
4 MONTH
5 DAY_OF_MONTH
6 DAY_OF_WEEK
7 FL_DATE
8 MKT_UNIQUE_CARRIER
9 BRANDED_CODE_SHARE
10 MKT_CARRIER_AIRLINE_ID
11 MKT_CARRIER
12 MKT_CARRIER_FL_NUM
13 ORIGIN
14 ORIGIN_CITY_NAME
15 ORIGIN_STATE_ABR
16 ORIGIN_STATE_NM
17 DEST
18 DEST_CITY_NAME
19 DEST_STATE_ABR
20 DEST_STATE_NM
21 CRS_DEP_TIME
22 DEP_TIME
23 DEP_DELAY
24 DEP_DELAY_NEW
25 DEP_DEL15
26 TAXI_OUT
27 TAXI_IN
28 CRS_ARR_TIME
29 ARR_TIME
30 ARR_DELAY
31 ARR_DELAY_NEW
32 ARR_DEL15
33 CANCELLED
34 CANCELLATION_CODE
35 DIVERTED
36 CRS_ELAPSED_TIME
37 ACTUAL_ELAPSED_TIME
38 AIR_TIME
39 DISTANCE
40 CARRIER_DELAY
41 WEATHER_DELAY
42 NAS_DELAY
43 SECURITY_DELAY
44 LATE_AIRCRAFT_DELAY

## 10. Data Types

Understanding data types is important before analysis.

For example:

- Dates should be represented as dates.
- Delay values should be numerical.
- Airline and airport codes are categorical.
- Cancellation and diversion indicators represent flight status.

In [21]:
flights.dtypes

Unnamed: 0                  int64
YEAR                        int64
QUARTER                     int64
MONTH                       int64
DAY_OF_MONTH                int64
DAY_OF_WEEK                 int64
FL_DATE                    object
MKT_UNIQUE_CARRIER         object
BRANDED_CODE_SHARE         object
MKT_CARRIER_AIRLINE_ID      int64
MKT_CARRIER                object
MKT_CARRIER_FL_NUM          int64
ORIGIN                     object
ORIGIN_CITY_NAME           object
ORIGIN_STATE_ABR           object
ORIGIN_STATE_NM            object
DEST                       object
DEST_CITY_NAME             object
DEST_STATE_ABR             object
DEST_STATE_NM              object
CRS_DEP_TIME                int64
DEP_TIME                  float64
DEP_DELAY                 float64
DEP_DELAY_NEW             float64
DEP_DEL15                 float64
TAXI_OUT                  float64
TAXI_IN                   float64
CRS_ARR_TIME                int64
ARR_TIME                  float64
ARR_DELAY                 float64
ARR_DELAY_NEW             float64
ARR_DEL15                 float64
CANCELLED                 float64
CANCELLATION_CODE          object
DIVERTED                  float64
CRS_ELAPSED_TIME          float64
ACTUAL_ELAPSED_TIME       float64
AIR_TIME                  float64
DISTANCE                  float64
CARRIER_DELAY             float64
WEATHER_DELAY             float64
NAS_DELAY                 float64
SECURITY_DELAY            float64
LATE_AIRCRAFT_DELAY       float64
dtype: object

In [22]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1847242 entries, 0 to 1847241
Data columns (total 44 columns):
 #   Column                  Dtype
---  ------                  -----
 0   Unnamed: 0              int64
 1   YEAR                    int64
 2   QUARTER                 int64
 3   MONTH                   int64
 4   DAY_OF_MONTH            int64
 5   DAY_OF_WEEK             int64
 6   FL_DATE                 object
 7   MKT_UNIQUE_CARRIER      object
 8   BRANDED_CODE_SHARE      object
 9   MKT_CARRIER_AIRLINE_ID  int64
 10  MKT_CARRIER             object
 11  MKT_CARRIER_FL_NUM      int64
 12  ORIGIN                  object
 13  ORIGIN_CITY_NAME        object
 14  ORIGIN_STATE_ABR        object
 15  ORIGIN_STATE_NM         object
 16  DEST                    object
 17  DEST_CITY_NAME          object
 18  DEST_STATE_ABR          object
 19  DEST_STATE_NM           object
 20  CRS_DEP_TIME            int64
 21  DEP_TIME                float64
 22  DEP_DELAY               float64
 23  DEP_DELAY_NEW           float64
 24  DEP_DEL15               float64
 25  TAXI_OUT                float64
 26  TAXI_IN                 float64
 27  CRS_ARR_TIME            int64
 28  ARR_TIME                float64
 29  ARR_DELAY               float64
 30  ARR_DELAY_NEW           float64
 31  ARR_DEL15               float64
 32  CANCELLED               float64
 33  CANCELLATION_CODE       object
 34  DIVERTED                float64
 35  CRS_ELAPSED_TIME        float64
 36  ACTUAL_ELAPSED_TIME     float64
 37  AIR_TIME                float64
 38  DISTANCE                float64
 39  CARRIER_DELAY           float64
 40  WEATHER_DELAY           float64
 41  NAS_DELAY               float64
 42  SECURITY_DELAY          float64
 43  LATE_AIRCRAFT_DELAY     float64
dtypes: float64(21), int64(10), object(13)
memory usage: 620.1+ MB

In [23]:
flights.head()

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,0,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,1,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,3,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,4,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

# Data Directory

|  # | Column                   | Business Meaning                                                                   | Type        | Why We Need It                            |
| -: | ------------------------ | ---------------------------------------------------------------------------------- | ----------- | ----------------------------------------- |
|  1 | `YEAR`                   | Year in which the flight operated                                                  | Integer     | Analyze yearly trends                     |
|  2 | `QUARTER`                | Quarter of the year (1–4)                                                          | Integer     | Compare performance across quarters       |
|  3 | `MONTH`                  | Month in which the flight operated                                                 | Integer     | Analyze monthly delay patterns            |
|  4 | `DAY_OF_MONTH`           | Day of the month                                                                   | Integer     | Analyze daily patterns                    |
|  5 | `DAY_OF_WEEK`            | Day of week (1–7)                                                                  | Integer     | Identify weekday/weekend patterns         |
|  6 | `FL_DATE`                | Date on which the flight operated                                                  | Date        | Main time dimension for analysis          |
|  7 | `MKT_UNIQUE_CARRIER`     | Unique carrier code                                                      | Categorical | Compare airline performance               |
|  8 | `BRANDED_CODE_SHARE`     | Indicates whether the flight is part of a branded/code-share operation             | Categorical | Understand code-share operations          |
|  9 | `MKT_CARRIER_AIRLINE_ID` | US DOT AIR_LINE ID                                        | Integer     | Identify the airline consistently         |
| 10 | `MKT_CARRIER`            | marketing carrier code                                                        | Categorical | Identify the marketing airline            |
| 11 | `MKT_CARRIER_FL_NUM`     | flight number                                                    | Integer     | Identify individual flights               |
| 12 | `ORIGIN`                 | Airport where the flight starts                                                    | Categorical | Analyze departure airport performance     |
| 13 | `ORIGIN_CITY_NAME`       | City of the origin airport                                                         | Categorical | Analyze performance by city               |
| 14 | `ORIGIN_STATE_ABR`       | State abbreviation of origin airport                                               | Categorical | Analyze performance by state              |
| 15 | `ORIGIN_STATE_NM`        | State name of origin airport                                                       | Categorical | Analyze geographic patterns               |
| 16 | `DEST`                   | Airport where the flight is scheduled to arrive                                    | Categorical | Analyze destination and route performance |
| 17 | `DEST_CITY_NAME`         | Destination airport city                                                           | Categorical | Analyze performance by destination city   |
| 18 | `DEST_STATE_ABR`         | Destination state abbreviation                                                     | Categorical | Analyze destination geography             |
| 19 | `DEST_STATE_NM`          | Destination state name                                                             | Categorical | Analyze destination patterns              |
| 20 | `CRS_DEP_TIME`           | Scheduled departure time                                                           | Time        | Analyze delays by departure time          |
| 21 | `DEP_TIME`               | Actual departure time                                                              | Time        | Compare actual vs scheduled departure     |
| 22 | `DEP_DELAY`              | Difference between actual and scheduled departure in minutes; negative means early | Numeric     | Measure departure delay                   |
| 23 | `DEP_DELAY_NEW`          | Departure delay where early departures are recorded as 0                           | Numeric     | Calculate departure delay metrics         |
| 24 | `DEP_DEL15`              | Indicates whether departure was delayed 15+ minutes                                | Binary      | Calculate departure delay rate            |
| 25 | `TAXI_OUT`               | Time from gate departure to takeoff                                                | Numeric     | Analyze airport ground operations         |
| 26 | `TAXI_IN`                | Time from landing to arrival gate                                                  | Numeric     | Analyze airport ground operations         |
| 27 | `CRS_ARR_TIME`           | Scheduled arrival time                                                             | Time        | Compare scheduled vs actual arrival       |
| 28 | `ARR_TIME`               | Actual arrival time                                                                | Time        | Measure actual arrival performance        |
| 29 | `ARR_DELAY`              | Difference between actual and scheduled arrival in minutes                         | Numeric     | Main arrival delay measure                |
| 30 | `ARR_DELAY_NEW`          | Arrival delay where early arrivals are recorded as 0                               | Numeric     | Calculate arrival delay metrics           |
| 31 | `ARR_DEL15`              | Indicates whether arrival was delayed 15+ minutes                                  | Binary      | Calculate arrival delay rate              |
| 32 | `CANCELLED`              | Indicates whether the flight was cancelled                                         | Binary      | Calculate cancellation rate               |
| 33 | `CANCELLATION_CODE`      | Reason why a flight was cancelled                                                  | Categorical | Understand cancellation causes            |
| 34 | `DIVERTED`               | Indicates whether the flight was diverted                                          | Binary      | Measure operational disruptions           |
| 35 | `CRS_ELAPSED_TIME`       | Scheduled flight duration in minutes                                               | Numeric     | Compare planned flight duration           |
| 36 | `ACTUAL_ELAPSED_TIME`    | Actual flight duration in minutes                                                  | Numeric     | Compare planned vs actual duration        |
| 37 | `AIR_TIME`               | Actual time spent in the air                                                       | Numeric     | Analyze flight performance                |
| 38 | `DISTANCE`               | Distance between origin and destination airports in miles                          | Numeric     | Analyze routes and flight duration        |
| 39 | `CARRIER_DELAY`          | Delay caused by the airline/carrier                                                | Numeric     | Identify carrier-related disruption       |
| 40 | `WEATHER_DELAY`          | Delay caused by weather                                                            | Numeric     | Analyze weather-related disruption        |
| 41 | `NAS_DELAY`              | Delay caused by the National Airspace System                                       | Numeric     | Analyze air-traffic/system delays         |
| 42 | `SECURITY_DELAY`         | Delay caused by security-related issues                                            | Numeric     | Analyze security-related disruption       |
| 43 | `LATE_AIRCRAFT_DELAY`    | Delay caused by a previous flight arriving late                                    | Numeric     | Analyze cascading delays                  |

# Business Group


| Business Group          | Main Columns                                                                                                                                              | Business Purpose                                   |
| ----------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| **Time**                | `YEAR`, `QUARTER`, `MONTH`, `DAY_OF_MONTH`, `DAY_OF_WEEK`, `FL_DATE`                                                                                      | When did the flight operate?                       |
| **Airline**             | `MKT_UNIQUE_CARRIER`, `BRANDED_CODE_SHARE`, `MKT_CARRIER_AIRLINE_ID`, `MKT_CARRIER`, `MKT_CARRIER_FL_NUM`                                                 | Which airline/flight was involved?                 |
| **Origin**              | `ORIGIN`, `ORIGIN_CITY_NAME`, `ORIGIN_STATE_ABR`, `ORIGIN_STATE_NM`                                                                                       | Where did the flight start?                        |
| **Destination**         | `DEST`, `DEST_CITY_NAME`, `DEST_STATE_ABR`, `DEST_STATE_NM`                                                                                               | Where was the flight going?                        |
| **Departure**           | `CRS_DEP_TIME`, `DEP_TIME`, `DEP_DELAY`, `DEP_DELAY_NEW`, `DEP_DEL15`, `TAXI_OUT`                                                                         | How well did the flight depart?                    |
| **Arrival**             | `CRS_ARR_TIME`, `ARR_TIME`, `ARR_DELAY`, `ARR_DELAY_NEW`, `ARR_DEL15`, `TAXI_IN`                                                                          | How well did the flight arrive?                    |
| **Disruption**          | `CANCELLED`, `CANCELLATION_CODE`, `DIVERTED`                                                                                                              | Was the flight disrupted?                          |
| **Operations & Causes** | `CRS_ELAPSED_TIME`, `ACTUAL_ELAPSED_TIME`, `AIR_TIME`, `DISTANCE`, `CARRIER_DELAY`, `WEATHER_DELAY`, `NAS_DELAY`, `SECURITY_DELAY`, `LATE_AIRCRAFT_DELAY` | Why was the flight delayed and how did it operate? |

## 11. Date Coverage

We check the earliest and latest flight dates to understand the time period
covered by the dataset.

In [24]:
flights.head()

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,0,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,1,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,3,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,4,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

In [25]:
# Convert FL_DATE only if it was saved as a string in the processed CSV
flights["FL_DATE"] = pd.to_datetime(
    flights["FL_DATE"],
    errors="coerce"
)

print("Start date:", flights["FL_DATE"].min())
print("End date:", flights["FL_DATE"].max())

Start date: 2026-01-01 00:00:00
End date: 2026-03-31 00:00:00

## 12. Flight Records by Month

In [26]:
flights["FL_DATE"].dt.month.value_counts().sort_index()

FL_DATE
1    602953
2    568789
3    675500
Name: count, dtype: int64

In [27]:
monthly_flights = (
    flights["FL_DATE"]
    .dt.month
    .value_counts()
    .sort_index()
)

monthly_flights

FL_DATE
1    602953
2    568789
3    675500
Name: count, dtype: int64

## 13. What Does One Row Represent?

Each row represents a flight operation reported in the BTS On-Time
Performance dataset.

The record contains information about:

- When the flight was scheduled
- Which airline operated/marketed the flight
- Where it departed
- Where it arrived
- Actual departure and arrival
- Delay information
- Cancellation/diversion status
- Operational characteristics
- Reported causes of delay

Therefore, the primary analytical unit is:

> One flight operation.

## 14. Variable Classification

To understand the dataset more easily, we group variables according to
their business purpose.

In [28]:
date_columns = [
    "YEAR",
    "QUARTER",
    "MONTH",
    "DAY_OF_MONTH",
    "DAY_OF_WEEK",
    "FL_DATE"
]
date_columns

['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE']

In [29]:
airline_columns = [
    "MKT_UNIQUE_CARRIER",
    "BRANDED_CODE_SHARE",
    "MKT_CARRIER_AIRLINE_ID",
    "MKT_CARRIER",
    "MKT_CARRIER_FL_NUM"
]
airline_columns

['MKT_UNIQUE_CARRIER',
 'BRANDED_CODE_SHARE',
 'MKT_CARRIER_AIRLINE_ID',
 'MKT_CARRIER',
 'MKT_CARRIER_FL_NUM']

In [30]:
route_columns = [
    "ORIGIN",
    "ORIGIN_CITY_NAME",
    "ORIGIN_STATE_ABR",
    "ORIGIN_STATE_NM",
    "DEST",
    "DEST_CITY_NAME",
    "DEST_STATE_ABR",
    "DEST_STATE_NM"
]
route_columns

['ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'DEST_STATE_NM']

In [31]:
departure_columns = [
    "CRS_DEP_TIME",
    "DEP_TIME",
    "DEP_DELAY",
    "DEP_DELAY_NEW",
    "DEP_DEL15",
    "TAXI_OUT"
]
departure_columns

['CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'TAXI_OUT']

In [32]:
arrival_columns = [
    "CRS_ARR_TIME",
    "ARR_TIME",
    "ARR_DELAY",
    "ARR_DELAY_NEW",
    "ARR_DEL15",
    "TAXI_IN"
]
arrival_columns

['CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'TAXI_IN']

In [33]:
status_columns = [
    "CANCELLED",
    "CANCELLATION_CODE",
    "DIVERTED"
]
status_columns

['CANCELLED', 'CANCELLATION_CODE', 'DIVERTED']

In [34]:
delay_cause_columns = [
    "CARRIER_DELAY",
    "WEATHER_DELAY",
    "NAS_DELAY",
    "SECURITY_DELAY",
    "LATE_AIRCRAFT_DELAY"
]
delay_cause_columns

['CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY']

## 15. Numerical Variables

We identify numerical variables because they will later be used for
statistical analysis and exploratory analysis.

Examples include:

- Departure delay
- Arrival delay
- Taxi time
- Air time
- Distance
- Delay causes

In [35]:
numeric_columns = flights.select_dtypes(
    include=np.number
).columns.tolist()

numeric_columns

['Unnamed: 0',
 'YEAR',
 'QUARTER',
 'MONTH',
 'DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'MKT_CARRIER_AIRLINE_ID',
 'MKT_CARRIER_FL_NUM',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'TAXI_OUT',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'CANCELLED',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY']

## 16. Categorical Variables

Categorical variables describe groups or categories such as:

- Airline
- Airport
- State
- Cancellation reason
- Code-share information

These variables will later be useful for comparison and segmentation.

In [36]:
categorical_columns = flights.select_dtypes(
    include="object"
).columns.tolist()

categorical_columns

['MKT_UNIQUE_CARRIER',
 'BRANDED_CODE_SHARE',
 'MKT_CARRIER',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'DEST_STATE_NM',
 'CANCELLATION_CODE']

## 17. Airline Coverage

We check how many unique marketing carriers are represented in the dataset.

In [37]:
print(
    "Unique airlines:",
    flights["MKT_UNIQUE_CARRIER"].nunique()
)

Unique airlines: 9

In [38]:
flights["MKT_UNIQUE_CARRIER"].unique()

array(['AA', 'AS', 'B6', 'DL', 'F9', 'G4', 'NK', 'UA', 'WN'], dtype=object)

## 18. Airport Coverage

In [39]:
print("Unique origin airports:", flights["ORIGIN"].nunique())
print("Unique destination airports:", flights["DEST"].nunique())

Unique origin airports: 362
Unique destination airports: 362

## 19. Route Coverage

In [40]:
unique_routes = flights[
    ["ORIGIN", "DEST"]
].drop_duplicates()

print("Unique routes:", len(unique_routes))

Unique routes: 6422

## 20. Flight Status Variables

The dataset contains indicators for:

- Cancellation
- Diversion
- Arrival delay
- Departure delay

We inspect their available values to understand how flight status is represented.

In [41]:
print("CANCELLED:")
print(flights["CANCELLED"].value_counts(dropna=False))

print("\nDIVERTED:")
print(flights["DIVERTED"].value_counts(dropna=False))

print("\nDEP_DEL15:")
print(flights["DEP_DEL15"].value_counts(dropna=False))

print("\nARR_DEL15:")
print(flights["ARR_DEL15"].value_counts(dropna=False))

CANCELLED:
CANCELLED
0.0    1784931
1.0      62311
Name: count, dtype: int64

DIVERTED:
DIVERTED
0.0    1842505
1.0       4737
Name: count, dtype: int64

DEP_DEL15:
DEP_DEL15
0.0    1396419
1.0     389849
NaN      60974
Name: count, dtype: int64

ARR_DEL15:
ARR_DEL15
0.0    1395768
1.0     384426
NaN      67048
Name: count, dtype: int64

## 21. Delay Cause Variables

BTS provides several reported delay causes:

- Carrier delay
- Weather delay
- National Airspace System (NAS) delay
- Security delay
- Late aircraft delay

These variables will later help us understand the composition of flight delays.

In [42]:
flights[
    delay_cause_columns
].describe()

,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
count,384426.000000,384426.000000,384426.000000,384426.000000,384426.000000
mean,26.771269,5.317260,14.499233,0.130366,29.269703
std,82.074800,41.409899,34.940501,4.280014,64.896116
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.000000,0.000000,0.000000,0.000000,0.000000
75%,23.000000,0.000000,18.000000,0.000000,33.000000
max,3339.000000,1958.000000,1560.000000,1600.000000,2338.000000

## 22. Initial Numerical Summary

We inspect basic statistics for numerical variables.

This is an initial understanding step, not the final EDA.

We will investigate unusual values and outliers later during the
Data Quality and EDA stages.

In [43]:
flights.describe().T

,count,mean,min,25%,50%,75%,max,std
Unnamed: 0,1847242.0,923620.5,0.0,461810.25,923620.5,1385430.75,1847241.0,533252.977317
YEAR,1847242.0,2026.0,2026.0,2026.0,2026.0,2026.0,2026.0,0.0
QUARTER,1847242.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0
MONTH,1847242.0,2.039273,1.0,1.0,2.0,3.0,3.0,0.830991
DAY_OF_MONTH,1847242.0,15.569698,1.0,8.0,16.0,23.0,31.0,8.701216
DAY_OF_WEEK,1847242.0,4.018039,1.0,2.0,4.0,6.0,7.0,2.017735
FL_DATE,1847242,2026-02-15 16:33:46.758594560,2026-01-01 00:00:00,2026-01-24 00:00:00,2026-02-17 00:00:00,2026-03-11 00:00:00,2026-03-31 00:00:00,NaN
MKT_CARRIER_AIRLINE_ID,1847242.0,19827.496986,19393.0,19790.0,19805.0,19977.0,20436.0,266.707311
MKT_CARRIER_FL_NUM,1847242.0,2764.304239,1.0,1332.0,2452.0,4145.0,9914.0,1724.520983
CRS_DEP_TIME,1847242.0,1322.166387,1.0,908.0,1315.0,1730.0,2359.0,485.142064
DEP_TIME,1786458.0,1329.817735,1.0,913.0,1325.0,1739.0,2400.0,501.122881
DEP_DELAY,1786268.0,13.938069,-66.0,-7.0,-2.0,10.0,3339.0,61.113006
DEP_DELAY_NEW,1786268.0,17.586258,0.0,0.0,0.0,10.0,3339.0,59.914301
DEP_DEL15,1786268.0,0.218248,0.0,0.0,0.0,0.0,1.0,0.413057
TAXI_OUT,1785251.0,19.20085,1.0,13.0,16.0,22.0,224.0,11.130109
TAXI_IN,1784292.0,8.786492,1.0,5.0,7.0,10.0,341.0,7.780903
CRS_ARR_TIME,1847242.0,1504.609117,1.0,1115.0,1524.0,1929.0,2359.0,506.232615
ARR_TIME,1784292.0,1474.002672,1.0,1058.0,1511.0,1920.0,2400.0,534.159829
ARR_DELAY,1780194.0,7.249089,-90.0,-18.0,-7.0,10.0,3339.0,63.468663
ARR_DELAY_NEW,1780194.0,17.345602,0.0,0.0,0.0,10.0,3339.0,59.63412
ARR_DEL15,1780194.0,0.215946,0.0,0.0,0.0,0.0,1.0,0.411477
CANCELLED,1847242.0,0.033732,0.0,0.0,0.0,0.0,1.0,0.180538
DIVERTED,1847242.0,0.002564,0.0,0.0,0.0,0.0,1.0,0.050575
CRS_ELAPSED_TIME,1847241.0,148.070241,-85.0,95.0,131.0,180.0,1202.0,72.255269
ACTUAL_ELAPSED_TIME,1780185.0,141.567923,14.0,89.0,125.0,173.0,763.0,72.431443
AIR_TIME,1780185.0,113.598469,6.0,62.0,97.0,144.0,719.0,70.744396
DISTANCE,1847242.0,808.080003,31.0,373.0,657.0,1050.0,4983.0,589.653629
CARRIER_DELAY,384426.0,26.771269,0.0,0.0,3.0,23.0,3339.0,82.0748
WEATHER_DELAY,384426.0,5.31726,0.0,0.0,0.0,0.0,1958.0,41.409899
NAS_DELAY,384426.0,14.499233,0.0,0.0,0.0,18.0,1560.0,34.940501
SECURITY_DELAY,384426.0,0.130366,0.0,0.0,0.0,0.0,1600.0,4.280014
LATE_AIRCRAFT_DELAY,384426.0,29.269703,0.0,0.0,0.0,33.0,2338.0,64.896116

In [44]:
# Unique Air_lines

flights['MKT_UNIQUE_CARRIER'].unique()

array(['AA', 'AS', 'B6', 'DL', 'F9', 'G4', 'NK', 'UA', 'WN'], dtype=object)

In [45]:
#number of Air_Lines
flights['MKT_UNIQUE_CARRIER'].nunique()

9

In [46]:
#Air_line_id's
flights['MKT_CARRIER_AIRLINE_ID'].unique()

array([19805, 19930, 20409, 19790, 20436, 20368, 20416, 19977, 19393])

In [47]:
#number of Air_line_id's
flights['MKT_CARRIER_AIRLINE_ID'].nunique()

9

In [48]:
flights.head()

,Unnamed: 0,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,0,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,1,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,3,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,4,2026,1,1,1,4,2026-01-01,AA,AA,19805,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN