# ✈️ Airline Operations Analytics — Deep Data Cleaning

## Project Goal

The goal of this notebook is to clean the **original airline operations data** before doing EDA, Power BI and business analysis.

I will follow this process:

**Understand → Audit → Investigate → Decide → Clean → Validate**

> Important: I will not blindly remove rows or fill every missing value.
> I will first understand **why the value is missing or wrong**.

# PART 1 — IMPORT AND LOAD DATA

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [3]:
# Change this to your original/raw CSV path
file_path = r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv"

df = pd.read_csv(file_path)

print("Data loaded successfully")

Data loaded successfully

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1847242
Columns: 43

In [5]:
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,MKT_CARRIER_FL_NUM,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_STATE_NM,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_STATE_NM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,TAXI_OUT,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,CANCELLATION_CODE,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,California,700,657.0,-3.0,0.0,0.0,67.0,11.0,1021,1104.0,43.0,43.0,1.0,0.0,NaN,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,New York,2130,2128.0,-2.0,0.0,0.0,16.0,6.0,551,520.0,-31.0,0.0,0.0,0.0,NaN,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1002,MIA,"Miami, FL",FL,Florida,MSY,"New Orleans, LA",LA,Louisiana,2245,2252.0,7.0,7.0,0.0,16.0,3.0,2359,2356.0,-3.0,0.0,0.0,0.0,NaN,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1003,DEN,"Denver, CO",CO,Colorado,MIA,"Miami, FL",FL,Florida,2338,2338.0,0.0,0.0,0.0,13.0,6.0,527,508.0,-19.0,0.0,0.0,0.0,NaN,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1004,BOS,"Boston, MA",MA,Massachusetts,CLT,"Charlotte, NC",NC,North Carolina,757,756.0,-1.0,0.0,0.0,26.0,4.0,1030,1023.0,-7.0,0.0,0.0,0.0,NaN,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

# PART 2 — UNDERSTAND THE ORIGINAL DATA

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1847242 entries, 0 to 1847241
Data columns (total 43 columns):
 #   Column                  Dtype
---  ------                  -----
 0   YEAR                    int64
 1   QUARTER                 int64
 2   MONTH                   int64
 3   DAY_OF_MONTH            int64
 4   DAY_OF_WEEK             int64
 5   FL_DATE                 object
 6   MKT_UNIQUE_CARRIER      object
 7   BRANDED_CODE_SHARE      object
 8   MKT_CARRIER_AIRLINE_ID  int64
 9   MKT_CARRIER             object
 10  MKT_CARRIER_FL_NUM      int64
 11  ORIGIN                  object
 12  ORIGIN_CITY_NAME        object
 13  ORIGIN_STATE_ABR        object
 14  ORIGIN_STATE_NM         object
 15  DEST                    object
 16  DEST_CITY_NAME          object
 17  DEST_STATE_ABR          object
 18  DEST_STATE_NM           object
 19  CRS_DEP_TIME            int64
 20  DEP_TIME                float64
 21  DEP_DELAY               float64
 22  DEP_DELAY_NEW           float64
 23  DEP_DEL15               float64
 24  TAXI_OUT                float64
 25  TAXI_IN                 float64
 26  CRS_ARR_TIME            int64
 27  ARR_TIME                float64
 28  ARR_DELAY               float64
 29  ARR_DELAY_NEW           float64
 30  ARR_DEL15               float64
 31  CANCELLED               float64
 32  CANCELLATION_CODE       object
 33  DIVERTED                float64
 34  CRS_ELAPSED_TIME        float64
 35  ACTUAL_ELAPSED_TIME     float64
 36  AIR_TIME                float64
 37  DISTANCE                float64
 38  CARRIER_DELAY           float64
 39  WEATHER_DELAY           float64
 40  NAS_DELAY               float64
 41  SECURITY_DELAY          float64
 42  LATE_AIRCRAFT_DELAY     float64
dtypes: float64(21), int64(9), object(13)
memory usage: 606.0+ MB

In [7]:
print("Column names:")
print(df.columns.tolist())

Column names:
['YEAR', 'QUARTER', 'MONTH', 'DAY_OF_MONTH', 'DAY_OF_WEEK', 'FL_DATE', 'MKT_UNIQUE_CARRIER', 'BRANDED_CODE_SHARE', 'MKT_CARRIER_AIRLINE_ID', 'MKT_CARRIER', 'MKT_CARRIER_FL_NUM', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_ABR', 'ORIGIN_STATE_NM', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_ABR', 'DEST_STATE_NM', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'DEP_DELAY_NEW', 'DEP_DEL15', 'TAXI_OUT', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'ARR_DELAY_NEW', 'ARR_DEL15', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ACTUAL_ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'CARRIER_DELAY', 'WEATHER_DELAY', 'NAS_DELAY', 'SECURITY_DELAY', 'LATE_AIRCRAFT_DELAY']

In [8]:
# Basic descriptive statistics for numeric columns
df.describe()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER_FL_NUM,CRS_DEP_TIME,DEP_TIME,DEP_DELAY,DEP_DELAY_NEW,DEP_DEL15,TAXI_OUT,TAXI_IN,CRS_ARR_TIME,ARR_TIME,ARR_DELAY,ARR_DELAY_NEW,ARR_DEL15,CANCELLED,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
count,1847242.0,1847242.0,1.847242e+06,1.847242e+06,1.847242e+06,1.847242e+06,1.847242e+06,1.847242e+06,1.786458e+06,1.786268e+06,1.786268e+06,1.786268e+06,1.785251e+06,1.784292e+06,1.847242e+06,1.784292e+06,1.780194e+06,1.780194e+06,1.780194e+06,1.847242e+06,1.847242e+06,1.847241e+06,1.780185e+06,1.780185e+06,1.847242e+06,384426.000000,384426.000000,384426.000000,384426.000000,384426.000000
mean,2026.0,1.0,2.039273e+00,1.556970e+01,4.018039e+00,1.982750e+04,2.764304e+03,1.322166e+03,1.329818e+03,1.393807e+01,1.758626e+01,2.182478e-01,1.920085e+01,8.786492e+00,1.504609e+03,1.474003e+03,7.249089e+00,1.734560e+01,2.159461e-01,3.373191e-02,2.564364e-03,1.480702e+02,1.415679e+02,1.135985e+02,8.080800e+02,26.771269,5.317260,14.499233,0.130366,29.269703
std,0.0,0.0,8.309906e-01,8.701216e+00,2.017735e+00,2.667073e+02,1.724521e+03,4.851421e+02,5.011229e+02,6.111301e+01,5.991430e+01,4.130566e-01,1.113011e+01,7.780903e+00,5.062326e+02,5.341598e+02,6.346866e+01,5.963412e+01,4.114772e-01,1.805383e-01,5.057459e-02,7.225527e+01,7.243144e+01,7.074440e+01,5.896536e+02,82.074800,41.409899,34.940501,4.280014,64.896116
min,2026.0,1.0,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.000000e+00,1.000000e+00,-6.600000e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,-9.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.500000e+01,1.400000e+01,6.000000e+00,3.100000e+01,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,1.0,1.000000e+00,8.000000e+00,2.000000e+00,1.979000e+04,1.332000e+03,9.080000e+02,9.130000e+02,-7.000000e+00,0.000000e+00,0.000000e+00,1.300000e+01,5.000000e+00,1.115000e+03,1.058000e+03,-1.800000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.500000e+01,8.900000e+01,6.200000e+01,3.730000e+02,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2026.0,1.0,2.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.452000e+03,1.315000e+03,1.325000e+03,-2.000000e+00,0.000000e+00,0.000000e+00,1.600000e+01,7.000000e+00,1.524000e+03,1.511000e+03,-7.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.310000e+02,1.250000e+02,9.700000e+01,6.570000e+02,3.000000,0.000000,0.000000,0.000000,0.000000
75%,2026.0,1.0,3.000000e+00,2.300000e+01,6.000000e+00,1.997700e+04,4.145000e+03,1.730000e+03,1.739000e+03,1.000000e+01,1.000000e+01,0.000000e+00,2.200000e+01,1.000000e+01,1.929000e+03,1.920000e+03,1.000000e+01,1.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00,1.800000e+02,1.730000e+02,1.440000e+02,1.050000e+03,23.000000,0.000000,18.000000,0.000000,33.000000
max,2026.0,1.0,3.000000e+00,3.100000e+01,7.000000e+00,2.043600e+04,9.914000e+03,2.359000e+03,2.400000e+03,3.339000e+03,3.339000e+03,1.000000e+00,2.240000e+02,3.410000e+02,2.359000e+03,2.400000e+03,3.339000e+03,3.339000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.202000e+03,7.630000e+02,7.190000e+02,4.983000e+03,3339.000000,1958.000000,1560.000000,1600.000000,2338.000000

In [9]:
# Number of unique values
df.nunique().sort_values(ascending=False).head(20)

MKT_CARRIER_FL_NUM     6582
ARR_DELAY              1622
DEP_DELAY              1581
DISTANCE               1567
ARR_DELAY_NEW          1535
DEP_DELAY_NEW          1525
ARR_TIME               1440
DEP_TIME               1436
CRS_ARR_TIME           1364
CARRIER_DELAY          1321
CRS_DEP_TIME           1266
LATE_AIRCRAFT_DELAY    1002
WEATHER_DELAY           882
ACTUAL_ELAPSED_TIME     706
AIR_TIME                669
NAS_DELAY               616
CRS_ELAPSED_TIME        521
ORIGIN                  362
DEST                    362
DEST_CITY_NAME          356
dtype: int64

In [10]:
# Standadise columns
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_", regex=False)
)

## Check the date range

In [11]:
df.dtypes

year                        int64
quarter                     int64
month                       int64
day_of_month                int64
day_of_week                 int64
fl_date                    object
mkt_unique_carrier         object
branded_code_share         object
mkt_carrier_airline_id      int64
mkt_carrier                object
mkt_carrier_fl_num          int64
origin                     object
origin_city_name           object
origin_state_abr           object
origin_state_nm            object
dest                       object
dest_city_name             object
dest_state_abr             object
dest_state_nm              object
crs_dep_time                int64
dep_time                  float64
dep_delay                 float64
dep_delay_new             float64
dep_del15                 float64
taxi_out                  float64
taxi_in                   float64
crs_arr_time                int64
arr_time                  float64
arr_delay                 float64
arr_delay_new             float64
arr_del15                 float64
cancelled                 float64
cancellation_code          object
diverted                  float64
crs_elapsed_time          float64
actual_elapsed_time       float64
air_time                  float64
distance                  float64
carrier_delay             float64
weather_delay             float64
nas_delay                 float64
security_delay            float64
late_aircraft_delay       float64
dtype: object

In [12]:
# convert to datetime.
df["fl_date"] = pd.to_datetime(df["fl_date"], errors="coerce")

In [13]:
print("Minimum date:", df["fl_date"].min())
print("Maximum date:", df["fl_date"].max())

Minimum date: 2026-01-01 00:00:00
Maximum date: 2026-03-31 00:00:00

# Data Directory

|  # | Column                   | Business Meaning                                                                   | Type        | Why We Need It                            |
| -: | ------------------------ | ---------------------------------------------------------------------------------- | ----------- | ----------------------------------------- |
|  1 | `YEAR`                   | Year in which the flight operated                                                  | Integer     | Analyze yearly trends                     |
|  2 | `QUARTER`                | Quarter of the year (1–4)                                                          | Integer     | Compare performance across quarters       |
|  3 | `MONTH`                  | Month in which the flight operated                                                 | Integer     | Analyze monthly delay patterns            |
|  4 | `DAY_OF_MONTH`           | Day of the month                                                                   | Integer     | Analyze daily patterns                    |
|  5 | `DAY_OF_WEEK`            | Day of week (1–7)                                                                  | Integer     | Identify weekday/weekend patterns         |
|  6 | `FL_DATE`                | Date on which the flight operated                                                  | Date        | Main time dimension for analysis          |
|  7 | `MKT_UNIQUE_CARRIER`     | Unique carrier code                                                      | Categorical | Compare airline performance               |
|  8 | `BRANDED_CODE_SHARE`     | Indicates whether the flight is part of a branded/code-share operation             | Categorical | Understand code-share operations          |
|  9 | `MKT_CARRIER_AIRLINE_ID` | US DOT AIR_LINE ID                                        | Integer     | Identify the airline consistently         |
| 10 | `MKT_CARRIER`            | marketing carrier code                                                        | Categorical | Identify the marketing airline            |
| 11 | `MKT_CARRIER_FL_NUM`     | flight number                                                    | Integer     | Identify individual flights               |
| 12 | `ORIGIN`                 | Airport where the flight starts                                                    | Categorical | Analyze departure airport performance     |
| 13 | `ORIGIN_CITY_NAME`       | City of the origin airport                                                         | Categorical | Analyze performance by city               |
| 14 | `ORIGIN_STATE_ABR`       | State abbreviation of origin airport                                               | Categorical | Analyze performance by state              |
| 15 | `ORIGIN_STATE_NM`        | State name of origin airport                                                       | Categorical | Analyze geographic patterns               |
| 16 | `DEST`                   | Airport where the flight is scheduled to arrive                                    | Categorical | Analyze destination and route performance |
| 17 | `DEST_CITY_NAME`         | Destination airport city                                                           | Categorical | Analyze performance by destination city   |
| 18 | `DEST_STATE_ABR`         | Destination state abbreviation                                                     | Categorical | Analyze destination geography             |
| 19 | `DEST_STATE_NM`          | Destination state name                                                             | Categorical | Analyze destination patterns              |
| 20 | `CRS_DEP_TIME`           | Scheduled departure time                                                           | Time        | Analyze delays by departure time          |
| 21 | `DEP_TIME`               | Actual departure time                                                              | Time        | Compare actual vs scheduled departure     |
| 22 | `DEP_DELAY`              | Difference between actual and scheduled departure in minutes; negative means early | Numeric     | Measure departure delay                   |
| 23 | `DEP_DELAY_NEW`          | Departure delay where early departures are recorded as 0                           | Numeric     | Calculate departure delay metrics         |
| 24 | `DEP_DEL15`              | Indicates whether departure was delayed 15+ minutes                                | Binary      | Calculate departure delay rate            |
| 25 | `TAXI_OUT`               | Time from gate departure to takeoff                                                | Numeric     | Analyze airport ground operations         |
| 26 | `TAXI_IN`                | Time from landing to arrival gate                                                  | Numeric     | Analyze airport ground operations         |
| 27 | `CRS_ARR_TIME`           | Scheduled arrival time                                                             | Time        | Compare scheduled vs actual arrival       |
| 28 | `ARR_TIME`               | Actual arrival time                                                                | Time        | Measure actual arrival performance        |
| 29 | `ARR_DELAY`              | Difference between actual and scheduled arrival in minutes                         | Numeric     | Main arrival delay measure                |
| 30 | `ARR_DELAY_NEW`          | Arrival delay where early arrivals are recorded as 0                               | Numeric     | Calculate arrival delay metrics           |
| 31 | `ARR_DEL15`              | Indicates whether arrival was delayed 15+ minutes                                  | Binary      | Calculate arrival delay rate              |
| 32 | `CANCELLED`              | Indicates whether the flight was cancelled                                         | Binary      | Calculate cancellation rate               |
| 33 | `CANCELLATION_CODE`      | Reason why a flight was cancelled                                                  | Categorical | Understand cancellation causes            |
| 34 | `DIVERTED`               | Indicates whether the flight was diverted                                          | Binary      | Measure operational disruptions           |
| 35 | `CRS_ELAPSED_TIME`       | Scheduled flight duration in minutes                                               | Numeric     | Compare planned flight duration           |
| 36 | `ACTUAL_ELAPSED_TIME`    | Actual flight duration in minutes                                                  | Numeric     | Compare planned vs actual duration        |
| 37 | `AIR_TIME`               | Actual time spent in the air                                                       | Numeric     | Analyze flight performance                |
| 38 | `DISTANCE`               | Distance between origin and destination airports in miles                          | Numeric     | Analyze routes and flight duration        |
| 39 | `CARRIER_DELAY`          | Delay caused by the airline/carrier                                                | Numeric     | Identify carrier-related disruption       |
| 40 | `WEATHER_DELAY`          | Delay caused by weather                                                            | Numeric     | Analyze weather-related disruption        |
| 41 | `NAS_DELAY`              | Delay caused by the National Airspace System                                       | Numeric     | Analyze air-traffic/system delays         |
| 42 | `SECURITY_DELAY`         | Delay caused by security-related issues                                            | Numeric     | Analyze security-related disruption       |
| 43 | `LATE_AIRCRAFT_DELAY`    | Delay caused by a previous flight arriving late                                    | Numeric     | Analyze cascading delays                  |

# Business Group


| Business Group          | Main Columns                                                                                                                                              | Business Purpose                                   |
| ----------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| **Time**                | `YEAR`, `QUARTER`, `MONTH`, `DAY_OF_MONTH`, `DAY_OF_WEEK`, `FL_DATE`                                                                                      | When did the flight operate?                       |
| **Airline**             | `MKT_UNIQUE_CARRIER`, `BRANDED_CODE_SHARE`, `MKT_CARRIER_AIRLINE_ID`, `MKT_CARRIER`, `MKT_CARRIER_FL_NUM`                                                 | Which airline/flight was involved?                 |
| **Origin**              | `ORIGIN`, `ORIGIN_CITY_NAME`, `ORIGIN_STATE_ABR`, `ORIGIN_STATE_NM`                                                                                       | Where did the flight start?                        |
| **Destination**         | `DEST`, `DEST_CITY_NAME`, `DEST_STATE_ABR`, `DEST_STATE_NM`                                                                                               | Where was the flight going?                        |
| **Departure**           | `CRS_DEP_TIME`, `DEP_TIME`, `DEP_DELAY`, `DEP_DELAY_NEW`, `DEP_DEL15`, `TAXI_OUT`                                                                         | How well did the flight depart?                    |
| **Arrival**             | `CRS_ARR_TIME`, `ARR_TIME`, `ARR_DELAY`, `ARR_DELAY_NEW`, `ARR_DEL15`, `TAXI_IN`                                                                          | How well did the flight arrive?                    |
| **Disruption**          | `CANCELLED`, `CANCELLATION_CODE`, `DIVERTED`                                                                                                              | Was the flight disrupted?                          |
| **Operations & Causes** | `CRS_ELAPSED_TIME`, `ACTUAL_ELAPSED_TIME`, `AIR_TIME`, `DISTANCE`, `CARRIER_DELAY`, `WEATHER_DELAY`, `NAS_DELAY`, `SECURITY_DELAY`, `LATE_AIRCRAFT_DELAY` | Why was the flight delayed and how did it operate? |

# PART 3 — DUPLICATE CHECK

In [14]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [15]:
if duplicate_count > 0:
    display(df[df.duplicated(keep=False)].head(20))
else:
    print("No duplicate rows found.")

No duplicate rows found.

# PART 4 — UNDERSTAND FLIGHT STATUS

For airline data, missing values cannot be understood correctly without knowing whether the flight was:

- Completed
- Cancelled
- Diverted

In [16]:
df["flight_status"] = np.where(
    df["cancelled"] == 1,
    "CANCELLED",
    np.where(
        df["diverted"] == 1,
        "DIVERTED",
        "COMPLETED"
    )
)

In [17]:
df['flight_status']

0          COMPLETED
1          COMPLETED
2          COMPLETED
3          COMPLETED
4          COMPLETED
             ...
1847237    COMPLETED
1847238    COMPLETED
1847239    COMPLETED
1847240    COMPLETED
1847241    COMPLETED
Name: flight_status, Length: 1847242, dtype: object

In [17]:
status_check=df[['cancelled','diverted','flight_status']]
status_check

         cancelled  diverted flight_status
0              0.0       0.0     COMPLETED
1              0.0       0.0     COMPLETED
2              0.0       0.0     COMPLETED
3              0.0       0.0     COMPLETED
4              0.0       0.0     COMPLETED
...            ...       ...           ...
1847237        0.0       0.0     COMPLETED
1847238        0.0       0.0     COMPLETED
1847239        0.0       0.0     COMPLETED
1847240        0.0       0.0     COMPLETED
1847241        0.0       0.0     COMPLETED

[1847242 rows x 3 columns]

In [18]:
df["flight_status"].value_counts()

flight_status
COMPLETED    1780194
CANCELLED      62311
DIVERTED        4737
Name: count, dtype: int64

In [19]:
status_percentage = (
    df["flight_status"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

status_percentage

flight_status
COMPLETED    96.37
CANCELLED     3.37
DIVERTED      0.26
Name: proportion, dtype: float64

# PART 5 — MISSING VALUE AUDIT

In [20]:
missing_count = df.isna().sum()

missing_count = (
    missing_count[missing_count > 0]
    .sort_values(ascending=False)
)

missing_count

cancellation_code      1784931
nas_delay              1462816
security_delay         1462816
weather_delay          1462816
carrier_delay          1462816
late_aircraft_delay    1462816
actual_elapsed_time      67057
air_time                 67057
arr_delay_new            67048
arr_del15                67048
arr_delay                67048
arr_time                 62950
taxi_in                  62950
taxi_out                 61991
dep_delay                60974
dep_del15                60974
dep_delay_new            60974
dep_time                 60784
crs_elapsed_time             1
dtype: int64

In [21]:
missing_percentage = (
    df.isna()
    .mean()
    .mul(100)
    .round(2)
    .sort_values(ascending=False)
)

missing_percentage

cancellation_code         96.63
carrier_delay             79.19
late_aircraft_delay       79.19
weather_delay             79.19
nas_delay                 79.19
security_delay            79.19
arr_del15                  3.63
arr_delay                  3.63
actual_elapsed_time        3.63
arr_delay_new              3.63
air_time                   3.63
taxi_in                    3.41
arr_time                   3.41
taxi_out                   3.36
dep_del15                  3.30
dep_delay                  3.30
dep_delay_new              3.30
dep_time                   3.29
mkt_carrier                0.00
mkt_carrier_airline_id     0.00
day_of_month               0.00
month                      0.00
quarter                    0.00
year                       0.00
branded_code_share         0.00
mkt_unique_carrier         0.00
fl_date                    0.00
day_of_week                0.00
origin                     0.00
mkt_carrier_fl_num         0.00
crs_arr_time               0.00
dest                       0.00
dest_city_name             0.00
dest_state_abr             0.00
dest_state_nm              0.00
crs_dep_time               0.00
origin_city_name           0.00
origin_state_abr           0.00
origin_state_nm            0.00
cancelled                  0.00
crs_elapsed_time           0.00
diverted                   0.00
distance                   0.00
flight_status              0.00
dtype: float64

## Missing values by flight status

This is important because a missing arrival time for a **cancelled flight** can be valid, while a missing arrival time for a **completed flight** can be suspicious.

In [22]:
important_columns = [
    "dep_time",
    "arr_time",
    "dep_delay",
    "arr_delay",
    "air_time",
    "actual_elapsed_time",
    "taxi_out",
    "taxi_in"
]

In [23]:
df[important_columns]

,dep_time,arr_time,dep_delay,arr_delay,air_time,actual_elapsed_time,taxi_out,taxi_in
0,657.0,1104.0,-3.0,43.0,349.0,427.0,67.0,11.0
1,2128.0,520.0,-2.0,-31.0,270.0,292.0,16.0,6.0
2,2252.0,2356.0,7.0,-3.0,105.0,124.0,16.0,3.0
3,2338.0,508.0,0.0,-19.0,191.0,210.0,13.0,6.0
4,756.0,1023.0,-1.0,-7.0,117.0,147.0,26.0,4.0
...,...,...,...,...,...,...,...,...
1847237,1311.0,1536.0,16.0,21.0,54.0,85.0,27.0,4.0
1847238,2040.0,103.0,5.0,8.0,126.0,143.0,12.0,5.0
1847239,627.0,848.0,-8.0,-12.0,125.0,141.0,13.0,3.0
1847240,2115.0,2257.0,0.0,7.0,85.0,102.0,13.0,4.0
1847241,1450.0,1748.0,-5.0,-17.0,100.0,118.0,15.0,3.0

In [24]:
completed = df["flight_status"] == "COMPLETED"
cancelled = df["flight_status"] == "CANCELLED"
diverted = df["flight_status"] == "DIVERTED"

In [25]:
print("COMPLETED")
print(df.loc[completed, important_columns].isna().sum())

COMPLETED
dep_time               0
arr_time               0
dep_delay              0
arr_delay              0
air_time               9
actual_elapsed_time    9
taxi_out               0
taxi_in                0
dtype: int64

In [26]:
print("CANCELLED")
print(df.loc[cancelled, important_columns].isna().sum())

CANCELLED
dep_time               60784
arr_time               62311
dep_delay              60974
arr_delay              62311
air_time               62311
actual_elapsed_time    62311
taxi_out               61991
taxi_in                62311
dtype: int64

In [27]:
print("DIVERTED")
print(df.loc[diverted, important_columns].isna().sum())

DIVERTED
dep_time                  0
arr_time                639
dep_delay                 0
arr_delay              4737
air_time               4737
actual_elapsed_time    4737
taxi_out                  0
taxi_in                 639
dtype: int64

# PART 6 — INVESTIGATE SUSPICIOUS MISSING VALUES

A completed flight should normally have operational timing information.

First, find completed flights with missing `air_time`.

In [28]:
completed_missing_air = df[
    (df["flight_status"] == "COMPLETED")
    & df["air_time"].isna()
]

print("Completed flights missing air_time:",
      len(completed_missing_air))

Completed flights missing air_time: 9

In [29]:
display(
    completed_missing_air[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "dep_time",
            "arr_time",
            "air_time"
        ]
    ]
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,dep_time,arr_time,air_time
422251,2026-01-22,DL,5444,JAX,LGA,1203.0,1415.0,NaN
1353591,2026-03-09,DL,5200,CHS,JFK,1742.0,1945.0,NaN
1418120,2026-03-12,DL,4780,RDU,IND,1148.0,1330.0,NaN
1418485,2026-03-12,DL,5202,ATL,BMI,1024.0,1140.0,NaN
1418486,2026-03-12,DL,5202,BMI,ATL,1219.0,1459.0,NaN
1441673,2026-03-13,DL,5509,JFK,BUF,1330.0,1510.0,NaN
1550400,2026-03-18,DL,4982,CWA,MSP,1617.0,1720.0,NaN
1595193,2026-03-20,DL,5049,JFK,CLT,1232.0,1416.0,NaN
1595582,2026-03-20,DL,5384,CWA,MSP,653.0,750.0,NaN

## Completed flights missing actual elapsed time

In [30]:
completed_missing_elapsed = df[
    (df["flight_status"] == "COMPLETED")
    & df["actual_elapsed_time"].isna()
]

print(
    "Completed flights missing actual_elapsed_time:",
    len(completed_missing_elapsed)
)

Completed flights missing actual_elapsed_time: 9

In [31]:
display(
    completed_missing_elapsed[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "dep_time",
            "arr_time",
            "actual_elapsed_time"
        ]
    ]
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,dep_time,arr_time,actual_elapsed_time
422251,2026-01-22,DL,5444,JAX,LGA,1203.0,1415.0,NaN
1353591,2026-03-09,DL,5200,CHS,JFK,1742.0,1945.0,NaN
1418120,2026-03-12,DL,4780,RDU,IND,1148.0,1330.0,NaN
1418485,2026-03-12,DL,5202,ATL,BMI,1024.0,1140.0,NaN
1418486,2026-03-12,DL,5202,BMI,ATL,1219.0,1459.0,NaN
1441673,2026-03-13,DL,5509,JFK,BUF,1330.0,1510.0,NaN
1550400,2026-03-18,DL,4982,CWA,MSP,1617.0,1720.0,NaN
1595193,2026-03-20,DL,5049,JFK,CLT,1232.0,1416.0,NaN
1595582,2026-03-20,DL,5384,CWA,MSP,653.0,750.0,NaN

## Find completed flights missing either measurement

This is the final suspicious-record check.

In [32]:
suspicious_completed = df[
    (df["flight_status"] == "COMPLETED")
    & (
        df["air_time"].isna()
        | df["actual_elapsed_time"].isna()
    )
]

In [33]:
print(
    "Suspicious completed flights:",
    len(suspicious_completed)
)

Suspicious completed flights: 9

In [34]:
suspicious_completed

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
422251,2026,1,1,22,4,2026-01-22,DL,DL_CODESHARE,19790,DL,5444,JAX,"Jacksonville, FL",FL,Florida,LGA,"New York, NY",NY,New York,1208,1203.0,-5.0,0.0,0.0,17.0,10.0,1429,1415.0,-14.0,0.0,0.0,0.0,NaN,0.0,141.0,NaN,NaN,834.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1353591,2026,1,3,9,1,2026-03-09,DL,DL_CODESHARE,19790,DL,5200,CHS,"Charleston, SC",SC,South Carolina,JFK,"New York, NY",NY,New York,1751,1742.0,-9.0,0.0,0.0,18.0,7.0,1959,1945.0,-14.0,0.0,0.0,0.0,NaN,0.0,128.0,NaN,NaN,636.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1418120,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,4780,RDU,"Raleigh/Durham, NC",NC,North Carolina,IND,"Indianapolis, IN",IN,Indiana,1150,1148.0,-2.0,0.0,0.0,14.0,6.0,1350,1330.0,-20.0,0.0,0.0,0.0,NaN,0.0,120.0,NaN,NaN,489.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1418485,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,5202,ATL,"Atlanta, GA",GA,Georgia,BMI,"Bloomington/Normal, IL",IL,Illinois,1025,1024.0,-1.0,0.0,0.0,43.0,7.0,1119,1140.0,21.0,21.0,1.0,0.0,NaN,0.0,114.0,NaN,NaN,533.0,21.0,0.0,0.0,0.0,0.0,COMPLETED
1418486,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,5202,BMI,"Bloomington/Normal, IL",IL,Illinois,ATL,"Atlanta, GA",GA,Georgia,1202,1219.0,17.0,17.0,1.0,14.0,9.0,1450,1459.0,9.0,9.0,0.0,0.0,NaN,0.0,108.0,NaN,NaN,533.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1441673,2026,1,3,13,5,2026-03-13,DL,DL_CODESHARE,19790,DL,5509,JFK,"New York, NY",NY,New York,BUF,"Buffalo, NY",NY,New York,1335,1330.0,-5.0,0.0,0.0,19.0,14.0,1514,1510.0,-4.0,0.0,0.0,0.0,NaN,0.0,99.0,NaN,NaN,301.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1550400,2026,1,3,18,3,2026-03-18,DL,DL_CODESHARE,19790,DL,4982,CWA,"Mosinee, WI",WI,Wisconsin,MSP,"Minneapolis, MN",MN,Minnesota,1619,1617.0,-2.0,0.0,0.0,14.0,7.0,1727,1720.0,-7.0,0.0,0.0,0.0,NaN,0.0,68.0,NaN,NaN,174.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1595193,2026,1,3,20,5,2026-03-20,DL,DL_CODESHARE,19790,DL,5049,JFK,"New York, NY",NY,New York,CLT,"Charlotte, NC",NC,North Carolina,1240,1232.0,-8.0,0.0,0.0,20.0,5.0,1445,1416.0,-29.0,0.0,0.0,0.0,NaN,0.0,125.0,NaN,NaN,542.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1595582,2026,1,3,20,5,2026-03-20,DL,DL_CODESHARE,19790,DL,5384,CWA,"Mosinee, WI",WI,Wisconsin,MSP,"Minneapolis, MN",MN,Minnesota,700,653.0,-7.0,0.0,0.0,15.0,8.0,814,750.0,-24.0,0.0,0.0,0.0,NaN,0.0,74.0,NaN,NaN,174.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [35]:
display(
    suspicious_completed[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "dep_time",
            "arr_time",
            "dep_delay",
            "arr_delay",
            "crs_elapsed_time",
            "actual_elapsed_time",
            "air_time"
        ]
    ]
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,dep_time,arr_time,dep_delay,arr_delay,crs_elapsed_time,actual_elapsed_time,air_time
422251,2026-01-22,DL,5444,JAX,LGA,1203.0,1415.0,-5.0,-14.0,141.0,NaN,NaN
1353591,2026-03-09,DL,5200,CHS,JFK,1742.0,1945.0,-9.0,-14.0,128.0,NaN,NaN
1418120,2026-03-12,DL,4780,RDU,IND,1148.0,1330.0,-2.0,-20.0,120.0,NaN,NaN
1418485,2026-03-12,DL,5202,ATL,BMI,1024.0,1140.0,-1.0,21.0,114.0,NaN,NaN
1418486,2026-03-12,DL,5202,BMI,ATL,1219.0,1459.0,17.0,9.0,108.0,NaN,NaN
1441673,2026-03-13,DL,5509,JFK,BUF,1330.0,1510.0,-5.0,-4.0,99.0,NaN,NaN
1550400,2026-03-18,DL,4982,CWA,MSP,1617.0,1720.0,-2.0,-7.0,68.0,NaN,NaN
1595193,2026-03-20,DL,5049,JFK,CLT,1232.0,1416.0,-8.0,-29.0,125.0,NaN,NaN
1595582,2026-03-20,DL,5384,CWA,MSP,653.0,750.0,-7.0,-24.0,74.0,NaN,NaN

# PART 7 — VALIDATE HHMM TIME COLUMNS

`dep_time` and `arr_time` are stored as HHMM-style numbers.

Examples:

- `530` → 05:30
- `1345` → 13:45
- `2460` → invalid
- `1265` → invalid

We need to check the values before cleaning them.

In [36]:
df.head()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,California,700,657.0,-3.0,0.0,0.0,67.0,11.0,1021,1104.0,43.0,43.0,1.0,0.0,NaN,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0,COMPLETED
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,New York,2130,2128.0,-2.0,0.0,0.0,16.0,6.0,551,520.0,-31.0,0.0,0.0,0.0,NaN,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1002,MIA,"Miami, FL",FL,Florida,MSY,"New Orleans, LA",LA,Louisiana,2245,2252.0,7.0,7.0,0.0,16.0,3.0,2359,2356.0,-3.0,0.0,0.0,0.0,NaN,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1003,DEN,"Denver, CO",CO,Colorado,MIA,"Miami, FL",FL,Florida,2338,2338.0,0.0,0.0,0.0,13.0,6.0,527,508.0,-19.0,0.0,0.0,0.0,NaN,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1004,BOS,"Boston, MA",MA,Massachusetts,CLT,"Charlotte, NC",NC,North Carolina,757,756.0,-1.0,0.0,0.0,26.0,4.0,1030,1023.0,-7.0,0.0,0.0,0.0,NaN,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [37]:
def valid_hhmm(value):
    if pd.isna(value):
        return True

    try:
        value = int(value)
    except:
        return False

    hour = value // 100
    minute = value % 100

    return (
        0 <= hour <= 23
        and 0 <= minute <= 59
    )

In [38]:
invalid_dep_time = (
    df["dep_time"].notna()
    & ~df["dep_time"].apply(valid_hhmm)
)

print(
    "Invalid dep_time values:",
    invalid_dep_time.sum()
)
df[invalid_dep_time].head(20)

Invalid dep_time values: 156

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
184,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1219,MIA,"Miami, FL",FL,Florida,ORD,"Chicago, IL",IL,Illinois,2210,2400.0,110.0,110.0,1.0,14.0,6.0,43,208.0,85.0,85.0,1.0,0.0,NaN,0.0,213.0,188.0,168.0,1197.0,43.0,0.0,0.0,0.0,42.0,COMPLETED
464,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1536,SMF,"Sacramento, CA",CA,California,DFW,"Dallas/Fort Worth, TX",TX,Texas,2359,2400.0,1.0,1.0,0.0,13.0,21.0,512,511.0,-1.0,0.0,0.0,0.0,NaN,0.0,193.0,191.0,157.0,1431.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
4468,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,5451,CLT,"Charlotte, NC",NC,North Carolina,PIA,"Peoria, IL",IL,Illinois,2240,2400.0,80.0,80.0,1.0,13.0,4.0,2356,59.0,63.0,63.0,1.0,0.0,NaN,0.0,136.0,119.0,102.0,607.0,63.0,0.0,0.0,0.0,0.0,COMPLETED
25431,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,484,OGG,"Kahului, HI",HI,Hawaii,SAN,"San Diego, CA",CA,California,2359,2400.0,1.0,1.0,0.0,18.0,8.0,720,713.0,-7.0,0.0,0.0,0.0,NaN,0.0,321.0,313.0,287.0,2540.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
27178,2026,1,1,2,5,2026-01-02,DL,DL,19790,DL,1114,ATL,"Atlanta, GA",GA,Georgia,GNV,"Gainesville, FL",FL,Florida,2245,2400.0,75.0,75.0,1.0,12.0,5.0,2359,100.0,61.0,61.0,1.0,0.0,NaN,0.0,74.0,60.0,43.0,300.0,0.0,0.0,0.0,0.0,61.0,COMPLETED
38810,2026,1,1,2,5,2026-01-02,WN,WN,19393,WN,2526,DEN,"Denver, CO",CO,Colorado,MCO,"Orlando, FL",FL,Florida,2355,2400.0,5.0,5.0,0.0,16.0,5.0,525,507.0,-18.0,0.0,0.0,0.0,NaN,0.0,210.0,187.0,166.0,1547.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
46673,2026,1,1,3,6,2026-01-03,AA,AA_CODESHARE,19805,AA,6492,DFW,"Dallas/Fort Worth, TX",TX,Texas,SJT,"San Angelo, TX",TX,Texas,2245,2400.0,75.0,75.0,1.0,16.0,5.0,2359,103.0,64.0,64.0,1.0,0.0,NaN,0.0,74.0,63.0,42.0,229.0,0.0,0.0,0.0,0.0,64.0,COMPLETED
48675,2026,1,1,3,6,2026-01-03,B6,B6,20409,B6,675,JFK,"New York, NY",NY,New York,BDL,"Hartford, CT",CT,Connecticut,2259,2400.0,61.0,61.0,1.0,15.0,7.0,2359,49.0,50.0,50.0,1.0,0.0,NaN,0.0,60.0,49.0,27.0,106.0,0.0,0.0,40.0,0.0,10.0,COMPLETED
48774,2026,1,1,3,6,2026-01-03,B6,B6,20409,B6,98,DEN,"Denver, CO",CO,Colorado,JFK,"New York, NY",NY,New York,2359,2400.0,1.0,1.0,0.0,21.0,4.0,540,529.0,-11.0,0.0,0.0,0.0,NaN,0.0,221.0,209.0,184.0,1626.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
50985,2026,1,1,3,6,2026-01-03,DL,DL,19790,DL,696,SLC,"Salt Lake City, UT",UT,Utah,BOS,"Boston, MA",MA,Massachusetts,2359,2400.0,1.0,1.0,0.0,21.0,16.0,642,626.0,-16.0,0.0,0.0,0.0,NaN,0.0,283.0,266.0,229.0,2105.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
53211,2026,1,1,3,6,2026-01-03,F9,F9,20436,F9,2520,DEN,"Denver, CO",CO,Colorado,MCO,"Orlando, FL",FL,Florida,2359,2400.0,1.0,1.0,0.0,25.0,14.0,531,533.0,2.0,2.0,0.0,0.0,NaN,0.0,212.0,213.0,174.0,1547.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
64037,2026,1,1,4,7,2026-01-04,AA,AA,19805,AA,2537,MIA,"Miami, FL",FL,Florida,MEM,"Memphis, TN",TN,Tennessee,2256,2400.0,64.0,64.0,1.0,12.0,5.0,40,123.0,43.0,43.0,1.0,0.0,NaN,0.0,164.0,143.0,126.0,859.0,4.0,0.0,0.0,0.0,39.0,COMPLETED
64170,2026,1,1,4,7,2026-01-04,AA,AA,19805,AA,2666,LAS,"Las Vegas, NV",NV,Nevada,DFW,"Dallas/Fort Worth, TX",TX,Texas,2359,2400.0,1.0,1.0,0.0,13.0,5.0,437,418.0,-19.0,0.0,0.0,0.0,NaN,0.0,158.0,138.0,120.0,1055.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
70059,2026,1,1,4,7,2026-01-04,B6,B6,20409,B6,2369,BOS,"Boston, MA",MA,Massachusetts,FLL,"Fort Lauderdale, FL",FL,Florida,2129,2400.0,151.0,151.0,1.0,42.0,4.0,59,324.0,145.0,145.0,1.0,0.0,NaN,0.0,210.0,204.0,158.0,1237.0,134.0,0.0,0.0,0.0,11.0,COMPLETED
70303,2026,1,1,4,7,2026-01-04,B6,B6,20409,B6,675,JFK,"New York, NY",NY,New York,BDL,"Hartford, CT",CT,Connecticut,2259,2400.0,61.0,61.0,1.0,22.0,54.0,2359,144.0,105.0,105.0,1.0,0.0,NaN,0.0,60.0,104.0,28.0,106.0,20.0,0.0,44.0,0.0,41.0,COMPLETED
80815,2026,1,1,4,7,2026-01-04,WN,WN,19393,WN,1316,BNA,"Nashville, TN",TN,Tennessee,SAT,"San Antonio, TX",TX,Texas,2250,2400.0,70.0,70.0,1.0,13.0,4.0,125,218.0,53.0,53.0,1.0,0.0,NaN,0.0,155.0,138.0,121.0,822.0,0.0,0.0,0.0,0.0,53.0,COMPLETED
88292,2026,1,1,5,1,2026-01-05,AA,AA_CODESHARE,19805,AA,4527,ORD,"Chicago, IL",IL,Illinois,LIT,"Little Rock, AR",AR,Arkansas,2,2400.0,-2.0,0.0,0.0,21.0,9.0,217,154.0,-23.0,0.0,0.0,0.0,NaN,0.0,135.0,114.0,84.0,552.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
90713,2026,1,1,5,1,2026-01-05,AS,AS,19930,AS,484,OGG,"Kahului, HI",HI,Hawaii,SAN,"San Diego, CA",CA,California,2359,2400.0,1.0,1.0,0.0,11.0,3.0,720,735.0,15.0,15.0,1.0,0.0,NaN,0.0,321.0,335.0,321.0,2540.0,0.0,0.0,15.0,0.0,0.0,COMPLETED
108105,2026,1,1,6,2,2026-01-06,AA,AA,19805,AA,3124,DFW,"Dallas/Fort Worth, TX",TX,Texas,MFE,"Mission/McAllen/Edinburg, TX",TX,Texas,2140,2400.0,140.0,140.0,1.0,14.0,5.0,2317,128.0,131.0,131.0,1.0,0.0,NaN,0.0,97.0,88.0,69.0,469.0,35.0,0.0,0.0,0.0,96.0,COMPLETED
115409,2026,1,1,6,2,2026-01-06,DL,DL,19790,DL,929,PHX,"Phoenix, AZ",AZ,Arizona,ATL,"Atlanta, GA",GA,Georgia,2353,2400.0,7.0,7.0,0.0,16.0,13.0,521,518.0,-3.0,0.0,0.0,0.0,NaN,0.0,208.0,198.0,169.0,1587.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [39]:
invalid_arr_time = (
    df["arr_time"].notna()
    & ~df["arr_time"].apply(valid_hhmm)
)

print(
    "Invalid arr_time values:",
    invalid_arr_time.sum()
)
df[invalid_arr_time].head(20)

Invalid arr_time values: 894

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
482,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1554,MIA,"Miami, FL",FL,Florida,DFW,"Dallas/Fort Worth, TX",TX,Texas,2205,2158.0,-7.0,0.0,0.0,13.0,6.0,36,2400.0,-36.0,0.0,0.0,0.0,NaN,0.0,211.0,182.0,163.0,1121.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
618,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1690,MIA,"Miami, FL",FL,Florida,MSP,"Minneapolis, MN",MN,Minnesota,2056,2103.0,7.0,7.0,0.0,11.0,9.0,2359,2400.0,1.0,1.0,0.0,0.0,NaN,0.0,243.0,237.0,217.0,1501.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1909,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,2941,MIA,"Miami, FL",FL,Florida,LAS,"Las Vegas, NV",NV,Nevada,2108,2122.0,14.0,14.0,0.0,11.0,12.0,2341,2400.0,19.0,19.0,1.0,0.0,NaN,0.0,333.0,338.0,315.0,2174.0,14.0,0.0,5.0,0.0,0.0,COMPLETED
2326,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,3308,MIA,"Miami, FL",FL,Florida,OMA,"Omaha, NE",NE,Nebraska,2106,2106.0,0.0,0.0,0.0,21.0,5.0,2355,2400.0,5.0,5.0,0.0,0.0,NaN,0.0,229.0,234.0,208.0,1393.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
4247,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,5207,DCA,"Washington, DC",VA,Virginia,CHS,"Charleston, SC",SC,South Carolina,1949,2210.0,141.0,141.0,1.0,25.0,12.0,2143,2400.0,137.0,137.0,1.0,0.0,NaN,0.0,114.0,110.0,73.0,444.0,0.0,0.0,0.0,0.0,137.0,COMPLETED
6885,2026,1,1,1,4,2026-01-01,B6,B6,20409,B6,1294,MCO,"Orlando, FL",FL,Florida,HPN,"White Plains, NY",NY,New York,2020,2112.0,52.0,52.0,1.0,19.0,5.0,2304,2400.0,56.0,56.0,1.0,0.0,NaN,0.0,164.0,168.0,144.0,972.0,25.0,0.0,4.0,0.0,27.0,COMPLETED
6976,2026,1,1,1,4,2026-01-01,B6,B6,20409,B6,1701,JFK,"New York, NY",NY,New York,FLL,"Fort Lauderdale, FL",FL,Florida,2030,2102.0,32.0,32.0,1.0,26.0,6.0,2352,2400.0,8.0,8.0,0.0,0.0,NaN,0.0,202.0,178.0,146.0,1069.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
7308,2026,1,1,1,4,2026-01-01,B6,B6,20409,B6,538,BQN,"Aguadilla, PR",PR,Puerto Rico,JFK,"New York, NY",NY,New York,2046,2121.0,35.0,35.0,1.0,9.0,7.0,2344,2400.0,16.0,16.0,1.0,0.0,NaN,0.0,238.0,219.0,203.0,1576.0,1.0,0.0,0.0,0.0,15.0,COMPLETED
8692,2026,1,1,1,4,2026-01-01,DL,DL,19790,DL,2715,DTW,"Detroit, MI",MI,Michigan,BWI,"Baltimore, MD",MD,Maryland,2156,2222.0,26.0,26.0,1.0,35.0,7.0,2331,2400.0,29.0,29.0,1.0,0.0,NaN,0.0,95.0,98.0,56.0,409.0,14.0,0.0,3.0,0.0,12.0,COMPLETED
20105,2026,1,1,2,5,2026-01-02,AA,AA,19805,AA,1970,MIA,"Miami, FL",FL,Florida,TPA,"Tampa, FL",FL,Florida,2240,2239.0,-1.0,0.0,0.0,34.0,6.0,2359,2400.0,1.0,1.0,0.0,0.0,NaN,0.0,79.0,81.0,41.0,204.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
21013,2026,1,1,2,5,2026-01-02,AA,AA,19805,AA,2827,CLT,"Charlotte, NC",NC,North Carolina,PBI,"West Palm Beach/Palm Beach, FL",FL,Florida,2236,2226.0,-10.0,0.0,0.0,12.0,5.0,23,2400.0,-23.0,0.0,0.0,0.0,NaN,0.0,107.0,94.0,77.0,590.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
21548,2026,1,1,2,5,2026-01-02,AA,AA,19805,AA,3265,CLT,"Charlotte, NC",NC,North Carolina,MSN,"Madison, WI",WI,Wisconsin,2250,2248.0,-2.0,0.0,0.0,24.0,4.0,2359,2400.0,1.0,1.0,0.0,0.0,NaN,0.0,129.0,132.0,104.0,708.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
23946,2026,1,1,2,5,2026-01-02,AA,AA_CODESHARE,19805,AA,5549,CLT,"Charlotte, NC",NC,North Carolina,IAD,"Washington, DC",VA,Virginia,2240,2251.0,11.0,11.0,0.0,11.0,5.0,4,2400.0,-4.0,0.0,0.0,0.0,NaN,0.0,84.0,69.0,53.0,322.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
26328,2026,1,1,2,5,2026-01-02,AS,AS_CODESHARE,19930,AS,3460,SEA,"Seattle, WA",WA,Washington,BLI,"Bellingham, WA",WA,Washington,2320,2312.0,-8.0,0.0,0.0,21.0,5.0,16,2400.0,-16.0,0.0,0.0,0.0,NaN,0.0,56.0,48.0,22.0,93.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
27015,2026,1,1,2,5,2026-01-02,B6,B6,20409,B6,866,FLL,"Fort Lauderdale, FL",FL,Florida,BUF,"Buffalo, NY",NY,New York,2040,2058.0,18.0,18.0,1.0,19.0,5.0,2343,2400.0,17.0,17.0,1.0,0.0,NaN,0.0,183.0,182.0,158.0,1166.0,17.0,0.0,0.0,0.0,0.0,COMPLETED
28114,2026,1,1,2,5,2026-01-02,DL,DL,19790,DL,2154,LAX,"Los Angeles, CA",CA,California,MSY,"New Orleans, LA",LA,Louisiana,1835,1835.0,0.0,0.0,0.0,21.0,4.0,9,2400.0,-9.0,0.0,0.0,0.0,NaN,0.0,214.0,205.0,180.0,1671.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
28255,2026,1,1,2,5,2026-01-02,DL,DL,19790,DL,2309,MSP,"Minneapolis, MN",MN,Minnesota,MCO,"Orlando, FL",FL,Florida,1900,2000.0,60.0,60.0,1.0,15.0,6.0,2322,2400.0,38.0,38.0,1.0,0.0,NaN,0.0,202.0,180.0,159.0,1310.0,25.0,0.0,0.0,0.0,13.0,COMPLETED
32714,2026,1,1,2,5,2026-01-02,NK,NK,20416,NK,200,ATL,"Atlanta, GA",GA,Georgia,FLL,"Fort Lauderdale, FL",FL,Florida,2157,2158.0,1.0,1.0,0.0,17.0,11.0,2358,2400.0,2.0,2.0,0.0,0.0,NaN,0.0,121.0,122.0,94.0,581.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
37274,2026,1,1,2,5,2026-01-02,WN,WN,19393,WN,1194,BWI,"Baltimore, MD",MD,Maryland,LAX,"Los Angeles, CA",CA,California,2015,2100.0,45.0,45.0,1.0,12.0,35.0,2305,2400.0,55.0,55.0,1.0,0.0,NaN,0.0,350.0,360.0,313.0,2329.0,30.0,0.0,10.0,0.0,15.0,COMPLETED
37370,2026,1,1,2,5,2026-01-02,WN,WN,19393,WN,1286,MDW,"Chicago, IL",IL,Illinois,SDF,"Louisville, KY",KY,Kentucky,2200,2200.0,0.0,0.0,0.0,9.0,3.0,10,2400.0,-10.0,0.0,0.0,0.0,NaN,0.0,70.0,60.0,48.0,271.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [40]:
bad_dep_records = df.loc[
    invalid_dep_time,
    [
        "fl_date",
        "mkt_carrier",
        "mkt_carrier_fl_num",
        "origin",
        "dest",
        "crs_dep_time",
        "dep_time",
        "dep_delay"
    ]
]

display(bad_dep_records.head(20))

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_dep_time,dep_time,dep_delay
184,2026-01-01,AA,1219,MIA,ORD,2210,2400.0,110.0
464,2026-01-01,AA,1536,SMF,DFW,2359,2400.0,1.0
4468,2026-01-01,AA,5451,CLT,PIA,2240,2400.0,80.0
25431,2026-01-02,AS,484,OGG,SAN,2359,2400.0,1.0
27178,2026-01-02,DL,1114,ATL,GNV,2245,2400.0,75.0
38810,2026-01-02,WN,2526,DEN,MCO,2355,2400.0,5.0
46673,2026-01-03,AA,6492,DFW,SJT,2245,2400.0,75.0
48675,2026-01-03,B6,675,JFK,BDL,2259,2400.0,61.0
48774,2026-01-03,B6,98,DEN,JFK,2359,2400.0,1.0
50985,2026-01-03,DL,696,SLC,BOS,2359,2400.0,1.0
53211,2026-01-03,F9,2520,DEN,MCO,2359,2400.0,1.0
64037,2026-01-04,AA,2537,MIA,MEM,2256,2400.0,64.0
64170,2026-01-04,AA,2666,LAS,DFW,2359,2400.0,1.0
70059,2026-01-04,B6,2369,BOS,FLL,2129,2400.0,151.0
70303,2026-01-04,B6,675,JFK,BDL,2259,2400.0,61.0
80815,2026-01-04,WN,1316,BNA,SAT,2250,2400.0,70.0
88292,2026-01-05,AA,4527,ORD,LIT,2,2400.0,-2.0
90713,2026-01-05,AS,484,OGG,SAN,2359,2400.0,1.0
108105,2026-01-06,AA,3124,DFW,MFE,2140,2400.0,140.0
115409,2026-01-06,DL,929,PHX,ATL,2353,2400.0,7.0

In [41]:
bad_arr_records = df.loc[
    invalid_arr_time,
    [
        "fl_date",
        "mkt_carrier",
        "mkt_carrier_fl_num",
        "origin",
        "dest",
        "crs_arr_time",
        "arr_time",
        "arr_delay"
    ]
]

display(bad_arr_records.head(20))

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_arr_time,arr_time,arr_delay
482,2026-01-01,AA,1554,MIA,DFW,36,2400.0,-36.0
618,2026-01-01,AA,1690,MIA,MSP,2359,2400.0,1.0
1909,2026-01-01,AA,2941,MIA,LAS,2341,2400.0,19.0
2326,2026-01-01,AA,3308,MIA,OMA,2355,2400.0,5.0
4247,2026-01-01,AA,5207,DCA,CHS,2143,2400.0,137.0
6885,2026-01-01,B6,1294,MCO,HPN,2304,2400.0,56.0
6976,2026-01-01,B6,1701,JFK,FLL,2352,2400.0,8.0
7308,2026-01-01,B6,538,BQN,JFK,2344,2400.0,16.0
8692,2026-01-01,DL,2715,DTW,BWI,2331,2400.0,29.0
20105,2026-01-02,AA,1970,MIA,TPA,2359,2400.0,1.0
21013,2026-01-02,AA,2827,CLT,PBI,23,2400.0,-23.0
21548,2026-01-02,AA,3265,CLT,MSN,2359,2400.0,1.0
23946,2026-01-02,AA,5549,CLT,IAD,4,2400.0,-4.0
26328,2026-01-02,AS,3460,SEA,BLI,16,2400.0,-16.0
27015,2026-01-02,B6,866,FLL,BUF,2343,2400.0,17.0
28114,2026-01-02,DL,2154,LAX,MSY,9,2400.0,-9.0
28255,2026-01-02,DL,2309,MSP,MCO,2322,2400.0,38.0
32714,2026-01-02,NK,200,ATL,FLL,2358,2400.0,2.0
37274,2026-01-02,WN,1194,BWI,LAX,2305,2400.0,55.0
37370,2026-01-02,WN,1286,MDW,SDF,10,2400.0,-10.0

# PART 8 — NUMERIC RANGE CHECKS

These are **data-quality plausibility rules**.

They are not saying every value outside the range is mathematically impossible. They identify values that require investigation.

In [42]:
df.head()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,California,700,657.0,-3.0,0.0,0.0,67.0,11.0,1021,1104.0,43.0,43.0,1.0,0.0,NaN,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0,COMPLETED
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,New York,2130,2128.0,-2.0,0.0,0.0,16.0,6.0,551,520.0,-31.0,0.0,0.0,0.0,NaN,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1002,MIA,"Miami, FL",FL,Florida,MSY,"New Orleans, LA",LA,Louisiana,2245,2252.0,7.0,7.0,0.0,16.0,3.0,2359,2356.0,-3.0,0.0,0.0,0.0,NaN,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1003,DEN,"Denver, CO",CO,Colorado,MIA,"Miami, FL",FL,Florida,2338,2338.0,0.0,0.0,0.0,13.0,6.0,527,508.0,-19.0,0.0,0.0,0.0,NaN,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1004,BOS,"Boston, MA",MA,Massachusetts,CLT,"Charlotte, NC",NC,North Carolina,757,756.0,-1.0,0.0,0.0,26.0,4.0,1030,1023.0,-7.0,0.0,0.0,0.0,NaN,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [43]:
df.sort_values(by='taxi_in',ascending=False)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
1286019,2026,1,3,6,5,2026-03-06,DL,DL,19790,DL,2329,ORF,"Norfolk, VA",VA,Virginia,ATL,"Atlanta, GA",GA,Georgia,1814,2221.0,247.0,247.0,1.0,13.0,341.0,2029,535.0,546.0,546.0,1.0,0.0,NaN,0.0,135.0,434.0,80.0,516.0,0.0,0.0,505.0,0.0,41.0,COMPLETED
1286662,2026,1,3,6,5,2026-03-06,DL,DL,19790,DL,3095,GSP,"Greer, SC",SC,South Carolina,ATL,"Atlanta, GA",GA,Georgia,1718,2257.0,339.0,339.0,1.0,12.0,333.0,1824,517.0,653.0,653.0,1.0,0.0,NaN,0.0,66.0,380.0,35.0,153.0,339.0,0.0,314.0,0.0,0.0,COMPLETED
1288452,2026,1,3,6,5,2026-03-06,DL,DL_CODESHARE,19790,DL,5073,XNA,"Fayetteville, AR",AR,Arkansas,ATL,"Atlanta, GA",GA,Georgia,1759,2042.0,163.0,163.0,1.0,31.0,307.0,2051,439.0,468.0,468.0,1.0,0.0,NaN,0.0,112.0,417.0,79.0,589.0,0.0,0.0,453.0,0.0,15.0,COMPLETED
1285325,2026,1,3,6,5,2026-03-06,DL,DL,19790,DL,1549,BOS,"Boston, MA",MA,Massachusetts,ATL,"Atlanta, GA",GA,Georgia,2025,2156.0,91.0,91.0,1.0,21.0,305.0,2340,533.0,353.0,353.0,1.0,0.0,NaN,0.0,195.0,457.0,131.0,946.0,0.0,0.0,262.0,0.0,91.0,COMPLETED
1286400,2026,1,3,6,5,2026-03-06,DL,DL,19790,DL,2780,DAL,"Dallas, TX",TX,Texas,ATL,"Atlanta, GA",GA,Georgia,1838,2052.0,134.0,134.0,1.0,33.0,303.0,2147,504.0,437.0,437.0,1.0,0.0,NaN,0.0,129.0,432.0,96.0,721.0,1.0,25.0,303.0,0.0,108.0,COMPLETED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844566,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,22,HOU,"Houston, TX",TX,Texas,DAL,"Dallas, TX",TX,Texas,1130,NaN,NaN,NaN,NaN,NaN,NaN,1235,NaN,NaN,NaN,NaN,1.0,A,0.0,65.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1844991,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,2613,DEN,"Denver, CO",CO,Colorado,MDW,"Chicago, IL",IL,Illinois,625,NaN,NaN,NaN,NaN,NaN,NaN,950,NaN,NaN,NaN,NaN,1.0,A,0.0,145.0,NaN,NaN,895.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1845075,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,27,DAL,"Dallas, TX",TX,Texas,HOU,"Houston, TX",TX,Texas,1300,NaN,NaN,NaN,NaN,NaN,NaN,1415,NaN,NaN,NaN,NaN,1.0,A,0.0,75.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1846157,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,3821,CLE,"Cleveland, OH",OH,Ohio,LAS,"Las Vegas, NV",NV,Nevada,1535,NaN,NaN,NaN,NaN,NaN,NaN,1715,NaN,NaN,NaN,NaN,1.0,A,0.0,280.0,NaN,NaN,1824.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1846459,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,4153,ORD,"Chicago, IL",IL,Illinois,RSW,"Fort Myers, FL",FL,Florida,1030,NaN,NaN,NaN,NaN,NaN,NaN,1425,NaN,NaN,NaN,NaN,1.0,A,0.0,175.0,NaN,NaN,1120.0,NaN,NaN,NaN,NaN,NaN,CANCELLED

In [44]:
print(
    "Invalid taxi_in:",
    ((df["taxi_in"] < 0) | (df["taxi_in"] > 300)).sum()
)

Invalid taxi_in: 5

In [45]:
df.sort_values(by='taxi_out',ascending=False)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
1478818,2026,1,3,15,7,2026-03-15,AS,AS,19930,AS,301,MCO,"Orlando, FL",FL,Florida,PDX,"Portland, OR",OR,Oregon,1653,1932.0,159.0,159.0,1.0,224.0,14.0,2023,423.0,NaN,NaN,NaN,0.0,NaN,1.0,390.0,NaN,NaN,2535.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
1435653,2026,1,3,13,5,2026-03-13,AS,AS,19930,AS,4,SEA,"Seattle, WA",WA,Washington,DCA,"Washington, DC",VA,Virginia,800,822.0,22.0,22.0,1.0,221.0,16.0,1606,2209.0,NaN,NaN,NaN,0.0,NaN,1.0,306.0,NaN,NaN,2329.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
1487757,2026,1,3,15,7,2026-03-15,UA,UA,19977,UA,1832,MCO,"Orlando, FL",FL,Florida,LAX,"Los Angeles, CA",CA,California,1435,1432.0,-3.0,0.0,0.0,215.0,31.0,1730,2039.0,189.0,189.0,1.0,0.0,NaN,0.0,355.0,547.0,301.0,2218.0,0.0,0.0,189.0,0.0,0.0,COMPLETED
470924,2026,1,1,25,7,2026-01-25,AA,AA,19805,AA,810,DFW,"Dallas/Fort Worth, TX",TX,Texas,SFO,"San Francisco, CA",CA,California,1530,1927.0,237.0,237.0,1.0,213.0,6.0,1724,19.0,415.0,415.0,1.0,0.0,NaN,0.0,234.0,412.0,193.0,1464.0,0.0,237.0,178.0,0.0,0.0,COMPLETED
1509397,2026,1,3,16,1,2026-03-16,NK,NK,20416,NK,198,FLL,"Fort Lauderdale, FL",FL,Florida,CLT,"Charlotte, NC",NC,North Carolina,1810,2126.0,196.0,196.0,1.0,189.0,6.0,2017,206.0,349.0,349.0,1.0,0.0,NaN,0.0,127.0,280.0,85.0,632.0,0.0,0.0,349.0,0.0,0.0,COMPLETED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844566,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,22,HOU,"Houston, TX",TX,Texas,DAL,"Dallas, TX",TX,Texas,1130,NaN,NaN,NaN,NaN,NaN,NaN,1235,NaN,NaN,NaN,NaN,1.0,A,0.0,65.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1844991,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,2613,DEN,"Denver, CO",CO,Colorado,MDW,"Chicago, IL",IL,Illinois,625,NaN,NaN,NaN,NaN,NaN,NaN,950,NaN,NaN,NaN,NaN,1.0,A,0.0,145.0,NaN,NaN,895.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1845075,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,27,DAL,"Dallas, TX",TX,Texas,HOU,"Houston, TX",TX,Texas,1300,NaN,NaN,NaN,NaN,NaN,NaN,1415,NaN,NaN,NaN,NaN,1.0,A,0.0,75.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1846157,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,3821,CLE,"Cleveland, OH",OH,Ohio,LAS,"Las Vegas, NV",NV,Nevada,1535,NaN,NaN,NaN,NaN,NaN,NaN,1715,NaN,NaN,NaN,NaN,1.0,A,0.0,280.0,NaN,NaN,1824.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1846459,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,4153,ORD,"Chicago, IL",IL,Illinois,RSW,"Fort Myers, FL",FL,Florida,1030,NaN,NaN,NaN,NaN,NaN,NaN,1425,NaN,NaN,NaN,NaN,1.0,A,0.0,175.0,NaN,NaN,1120.0,NaN,NaN,NaN,NaN,NaN,CANCELLED

In [46]:
print(
    "Invalid taxi_out:",
    ((df["taxi_out"] < 0) | (df["taxi_out"] > 300)).sum()
)

Invalid taxi_out: 0

In [47]:
df.sort_values(by='crs_elapsed_time',ascending=False)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
135791,2026,1,1,7,3,2026-01-07,NK,NK,20416,NK,1475,PHL,"Philadelphia, PA",PA,Pennsylvania,ACY,"Atlantic City, NJ",NJ,New Jersey,120,1018.0,538.0,538.0,1.0,11.0,5.0,2122,1052.0,810.0,810.0,1.0,0.0,NaN,0.0,1202.0,34.0,18.0,45.0,810.0,0.0,0.0,0.0,0.0,COMPLETED
1308300,2026,1,3,7,6,2026-03-07,DL,DL,19790,DL,636,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,1000,1017.0,17.0,17.0,1.0,21.0,23.0,1623,1541.0,-42.0,0.0,0.0,0.0,NaN,0.0,743.0,684.0,640.0,4983.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1114935,2026,1,2,26,4,2026-02-26,AS,AS,19930,AS,9885,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,1030,1134.0,64.0,64.0,1.0,29.0,4.0,1711,1754.0,43.0,43.0,1.0,0.0,NaN,0.0,701.0,680.0,647.0,4983.0,43.0,0.0,0.0,0.0,0.0,COMPLETED
853779,2026,1,2,13,5,2026-02-13,UA,UA,19977,UA,363,EWR,"Newark, NJ",NJ,New Jersey,HNL,"Honolulu, HI",HI,Hawaii,900,859.0,-1.0,0.0,0.0,30.0,3.0,1528,1445.0,-43.0,0.0,0.0,0.0,NaN,0.0,688.0,646.0,613.0,4962.0,NaN,NaN,NaN,NaN,NaN,COMPLETED
1687131,2026,1,3,24,2,2026-03-24,UA,UA,19977,UA,363,EWR,"Newark, NJ",NJ,New Jersey,HNL,"Honolulu, HI",HI,Hawaii,905,1106.0,121.0,121.0,1.0,20.0,3.0,1433,1537.0,64.0,64.0,1.0,0.0,NaN,0.0,688.0,631.0,608.0,4962.0,64.0,0.0,0.0,0.0,0.0,COMPLETED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
448674,2026,1,1,23,5,2026-01-23,WN,WN,19393,WN,1651,BWI,"Baltimore, MD",MD,Maryland,MHT,"Manchester, NH",NH,New Hampshire,1254,1222.0,-32.0,0.0,0.0,11.0,3.0,1210,1559.0,NaN,NaN,NaN,0.0,NaN,1.0,-44.0,NaN,NaN,377.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
15768,2026,1,1,1,4,2026-01-01,WN,WN,19393,WN,1067,PHX,"Phoenix, AZ",AZ,Arizona,LAS,"Las Vegas, NV",NV,Nevada,2140,2207.0,27.0,27.0,1.0,26.0,3.0,2105,19.0,NaN,NaN,NaN,0.0,NaN,1.0,-64.0,NaN,NaN,255.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
941573,2026,1,2,17,2,2026-02-17,WN,WN,19393,WN,427,OAK,"Oakland, CA",CA,California,BUR,"Burbank, CA",CA,California,2215,2152.0,-23.0,0.0,0.0,15.0,NaN,2110,NaN,NaN,NaN,NaN,1.0,C,0.0,-65.0,NaN,NaN,325.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1253362,2026,1,3,4,3,2026-03-04,WN,WN,19393,WN,3448,SAT,"San Antonio, TX",TX,Texas,DAL,"Dallas, TX",TX,Texas,1950,1925.0,-25.0,0.0,0.0,14.0,11.0,1825,35.0,NaN,NaN,NaN,0.0,NaN,1.0,-85.0,NaN,NaN,247.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
1447150,2026,1,3,13,5,2026-03-13,UA,UA_CODESHARE,19977,UA,5035,DEN,"Denver, CO",CO,Colorado,ATY,"Watertown, SD",SD,South Dakota,1410,1403.0,-7.0,0.0,0.0,28.0,8.0,1657,1657.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,114.0,78.0,519.0,NaN,NaN,NaN,NaN,NaN,COMPLETED

In [48]:
print(
    "Invalid crs_elapsed_time:",
    (
        (df["crs_elapsed_time"] < 1)
        | (df["crs_elapsed_time"] > 1000)
    ).sum()
)

Invalid crs_elapsed_time: 9

In [49]:
df.sort_values(by='actual_elapsed_time',ascending=False)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status
69145,2026,1,1,4,7,2026-01-04,AS,AS,19930,AS,829,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,832,846.0,14.0,14.0,0.0,27.0,71.0,1448,1629.0,101.0,101.0,1.0,0.0,NaN,0.0,676.0,763.0,665.0,4983.0,101.0,0.0,0.0,0.0,0.0,COMPLETED
1015411,2026,1,2,21,6,2026-02-21,DL,DL,19790,DL,636,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,1000,952.0,-8.0,0.0,0.0,59.0,38.0,1623,1729.0,66.0,66.0,1.0,0.0,NaN,0.0,683.0,757.0,660.0,4983.0,0.0,0.0,66.0,0.0,0.0,COMPLETED
1461610,2026,1,3,14,6,2026-03-14,DL,DL,19790,DL,636,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,1000,1000.0,0.0,0.0,0.0,34.0,60.0,1521,1631.0,70.0,70.0,1.0,0.0,NaN,0.0,681.0,751.0,657.0,4983.0,0.0,0.0,70.0,0.0,0.0,COMPLETED
1289247,2026,1,3,6,5,2026-03-06,F9,F9,20436,F9,1441,ATL,"Atlanta, GA",GA,Georgia,ORD,"Chicago, IL",IL,Illinois,927,957.0,30.0,30.0,1.0,15.0,15.0,1056,2126.0,630.0,630.0,1.0,0.0,NaN,0.0,149.0,749.0,719.0,606.0,0.0,0.0,600.0,0.0,30.0,COMPLETED
889079,2026,1,2,15,7,2026-02-15,DL,DL,19790,DL,636,JFK,"New York, NY",NY,New York,HNL,"Honolulu, HI",HI,Hawaii,1000,946.0,-14.0,0.0,0.0,40.0,42.0,1623,1703.0,40.0,40.0,1.0,0.0,NaN,0.0,683.0,737.0,655.0,4983.0,0.0,0.0,40.0,0.0,0.0,COMPLETED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1845022,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,2649,HOU,"Houston, TX",TX,Texas,MDW,"Chicago, IL",IL,Illinois,820,836.0,16.0,16.0,1.0,8.0,5.0,1045,1329.0,NaN,NaN,NaN,0.0,NaN,1.0,145.0,NaN,NaN,937.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
1845075,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,27,DAL,"Dallas, TX",TX,Texas,HOU,"Houston, TX",TX,Texas,1300,NaN,NaN,NaN,NaN,NaN,NaN,1415,NaN,NaN,NaN,NaN,1.0,A,0.0,75.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1845304,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,2947,MCO,"Orlando, FL",FL,Florida,PIT,"Pittsburgh, PA",PA,Pennsylvania,2055,2158.0,63.0,63.0,1.0,12.0,11.0,2320,211.0,NaN,NaN,NaN,0.0,NaN,1.0,145.0,NaN,NaN,834.0,NaN,NaN,NaN,NaN,NaN,DIVERTED
1846157,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,3821,CLE,"Cleveland, OH",OH,Ohio,LAS,"Las Vegas, NV",NV,Nevada,1535,NaN,NaN,NaN,NaN,NaN,NaN,1715,NaN,NaN,NaN,NaN,1.0,A,0.0,280.0,NaN,NaN,1824.0,NaN,NaN,NaN,NaN,NaN,CANCELLED
1846459,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,4153,ORD,"Chicago, IL",IL,Illinois,RSW,"Fort Myers, FL",FL,Florida,1030,NaN,NaN,NaN,NaN,NaN,NaN,1425,NaN,NaN,NaN,NaN,1.0,A,0.0,175.0,NaN,NaN,1120.0,NaN,NaN,NaN,NaN,NaN,CANCELLED

In [50]:
print(
    "Invalid actual_elapsed_time:",
    (
        (df["actual_elapsed_time"] < 1)
        | (df["actual_elapsed_time"] > 1500)
    ).sum()
)

Invalid actual_elapsed_time: 0

In [51]:
print(
    "Invalid air_time:",
    (
        (df["air_time"] < 1)
        | (df["air_time"] > 1500)
    ).sum()
)

Invalid air_time: 0

In [52]:
print(
    "Invalid distance:",
    (
        (df["distance"] < 1)
        | (df["distance"] > 6000)
    ).sum()
)

Invalid distance: 0

## Investigate invalid taxi_in records

In [53]:
bad_taxi_in = df[
    (df["taxi_in"] < 0)
    | (df["taxi_in"] > 300)
]

In [54]:
print("Invalid taxi_in records:", len(bad_taxi_in))

Invalid taxi_in records: 5

In [55]:
display(
    bad_taxi_in[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "taxi_in",
            "taxi_out",
            "air_time",
            "actual_elapsed_time"
        ]
    ]
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,taxi_in,taxi_out,air_time,actual_elapsed_time
1285325,2026-03-06,DL,1549,BOS,ATL,305.0,21.0,131.0,457.0
1286019,2026-03-06,DL,2329,ORF,ATL,341.0,13.0,80.0,434.0
1286400,2026-03-06,DL,2780,DAL,ATL,303.0,33.0,96.0,432.0
1286662,2026-03-06,DL,3095,GSP,ATL,333.0,12.0,35.0,380.0
1288452,2026-03-06,DL,5073,XNA,ATL,307.0,31.0,79.0,417.0

## Investigate invalid scheduled elapsed time

In [56]:
bad_crs_elapsed = df[
    (df["crs_elapsed_time"] < 1)
    | (df["crs_elapsed_time"] > 1000)
]

In [57]:
print(
    "Invalid crs_elapsed_time records:",
    len(bad_crs_elapsed)
)

Invalid crs_elapsed_time records: 9

In [58]:
display(
    bad_crs_elapsed[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "crs_elapsed_time",
            "distance"
        ]
    ]
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_elapsed_time,distance
15768,2026-01-01,WN,1067,PHX,LAS,-64.0,255.0
135791,2026-01-07,NK,1475,PHL,ACY,1202.0,45.0
275482,2026-01-14,WN,373,DAL,SAT,-16.0,247.0
293824,2026-01-15,WN,1493,STL,DSM,-14.0,259.0
448674,2026-01-23,WN,1651,BWI,MHT,-44.0,377.0
941573,2026-02-17,WN,427,OAK,BUR,-65.0,325.0
1253362,2026-03-04,WN,3448,SAT,DAL,-85.0,247.0
1448834,2026-03-13,WN,1730,BWI,ROC,-17.0,277.0
1517653,2026-03-16,WN,4698,GSP,BNA,-17.0,265.0

# PART 9 — BUSINESS RULE CHECKS

These checks test whether columns agree with each other.

In [59]:
cancelled_with_arrival = df[
    (df["cancelled"] == 1)
    & df["arr_time"].notna()
]

print(
    "Cancelled flights with arrival time:",
    len(cancelled_with_arrival)
)

Cancelled flights with arrival time: 0

In [60]:
cancelled_with_arr_delay = df[
    (df["cancelled"] == 1)
    & df["arr_delay"].notna()
]

print(
    "Cancelled flights with arrival delay:",
    len(cancelled_with_arr_delay)
)

Cancelled flights with arrival delay: 0

In [61]:
diverted_cancelled = df[
    (df["diverted"] == 1)
    & (df["cancelled"] == 1)
]

print(
    "Flights both diverted and cancelled:",
    len(diverted_cancelled)
)

Flights both diverted and cancelled: 0

In [62]:
completed_without_dep = df[
    (df["flight_status"] == "COMPLETED")
    & df["dep_time"].isna()
]

print(
    "Completed flights without departure time:",
    len(completed_without_dep)
)

Completed flights without departure time: 0

In [63]:
completed_without_arr = df[
    (df["flight_status"] == "COMPLETED")
    & df["arr_time"].isna()
]

print(
    "Completed flights without arrival time:",
    len(completed_without_arr)
)

Completed flights without arrival time: 0

# PART 10 — CHECK DELAY EXTREMES

An extreme value is not automatically wrong.

For example, a 900-minute delay may be a real operational event.

Therefore, we will **flag extreme delays instead of deleting them**.

In [64]:
extreme_departure = df[
    df["dep_delay"].abs() > 720
]

print(
    "Extreme departure delays:",
    len(extreme_departure)
)

Extreme departure delays: 2313

In [65]:
extreme_arrival = df[
    df["arr_delay"].abs() > 720
]

print(
    "Extreme arrival delays:",
    len(extreme_arrival)
)

Extreme arrival delays: 2267

In [66]:
display(
    extreme_departure[
        [
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest",
            "dep_delay",
            "arr_delay"
        ]
    ]
    .sort_values("dep_delay", ascending=False)
    .head(20)
)

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,dep_delay,arr_delay
545981,2026-01-29,AA,1652,SDF,DFW,3339.0,3339.0
943931,2026-02-18,AA,2448,MFE,DFW,3120.0,3113.0
164767,2026-01-09,AA,2774,AUS,PHL,2954.0,2975.0
1069948,2026-02-24,AA,164,HNL,LAX,2937.0,2919.0
1781179,2026-03-29,AA,1240,BDL,MIA,2888.0,2862.0
1412313,2026-03-12,AA,9656,BNA,CLT,2874.0,2882.0
932419,2026-02-17,DL,3587,SDF,DTW,2748.0,2738.0
124764,2026-01-07,AA,1182,MCI,PHX,2706.0,2680.0
1342971,2026-03-09,AA,2266,OMA,DFW,2663.0,2678.0
1366117,2026-03-10,AA,2691,AUS,PHL,2625.0,2610.0
1173548,2026-03-01,AA,2753,CID,DFW,2621.0,2601.0
201873,2026-01-11,AA,2734,STT,MIA,2581.0,2567.0
1320807,2026-03-08,AA,2630,FAT,DFW,2566.0,2596.0
643917,2026-02-03,AA,1264,CLE,CLT,2543.0,2550.0
143991,2026-01-08,AA,2087,DSM,PHX,2539.0,2572.0
144516,2026-01-08,AA,2549,AUS,CLT,2357.0,2351.0
1606983,2026-03-21,AA,1768,MSY,DFW,2317.0,2362.0
1760826,2026-03-28,AA,1395,MSP,DFW,2301.0,2318.0
1007570,2026-02-21,AA,2272,OKC,DFW,2297.0,2286.0
394573,2026-01-21,AA,307,LAX,JFK,2270.0,2234.0

# PART 11 — DATA QUALITY SUMMARY

At this point we know which values are:

- Structurally missing
- Invalid
- Suspicious
- Extreme but potentially valid
- Business-rule violations

In [67]:
quality_summary = pd.DataFrame({
    "Issue": [
        "Duplicate rows",
        "Invalid dep_time",
        "Invalid arr_time",
        "Invalid taxi_in",
        "Invalid crs_elapsed_time",
        "Completed missing air_time / actual_elapsed_time",
        "Extreme departure delays",
        "Extreme arrival delays"
    ],
    "Count": [
        df.duplicated().sum(),
        invalid_dep_time.sum(),
        invalid_arr_time.sum(),
        len(bad_taxi_in),
        len(bad_crs_elapsed),
        len(suspicious_completed),
        len(extreme_departure),
        len(extreme_arrival)
    ]
})

quality_summary

                                              Issue  Count
0                                    Duplicate rows      0
1                                  Invalid dep_time    156
2                                  Invalid arr_time    894
3                                   Invalid taxi_in      5
4                          Invalid crs_elapsed_time      9
5  Completed missing air_time / actual_elapsed_time      9
6                          Extreme departure delays   2313
7                            Extreme arrival delays   2267

# PART 12 — CLEANING DECISIONS

| Problem | Cleaning decision |
|---|---|
| Duplicate rows | Remove only if duplicates exist |
| Invalid HHMM | Replace invalid value with `NaN` |
| Invalid numeric measurement | Replace invalid value with `NaN` |
| Cancelled-flight structural missingness | Keep as `NaN` |
| Suspicious completed-flight measurement | Keep record + create quality flag |
| Extreme delays | Keep record + create outlier flag |

The important principle is:

**Do not delete an entire flight just because one measurement is wrong.**

# PART 13 — CREATE CLEAN DATASET

In [68]:
df_clean = df.copy()

print("Original rows:", len(df))
print("Clean rows:", len(df_clean))

Original rows: 1847242
Clean rows: 1847242

## Clean invalid departure times

In [69]:
df_clean.loc[
    invalid_dep_time,
    "dep_time"
] = np.nan

## Clean invalid arrival times

In [70]:
df_clean.loc[
    invalid_arr_time,
    "arr_time"
] = np.nan

## Clean invalid taxi_in

In [71]:
bad_taxi_in_clean = (
    (df_clean["taxi_in"] < 0)
    | (df_clean["taxi_in"] > 300)
)

df_clean.loc[
    bad_taxi_in_clean,
    "taxi_in"
] = np.nan

## Clean invalid taxi_out

In [72]:
bad_taxi_out_clean = (
    (df_clean["taxi_out"] < 0)
    | (df_clean["taxi_out"] > 300)
)

df_clean.loc[
    bad_taxi_out_clean,
    "taxi_out"
] = np.nan

## Clean invalid scheduled elapsed time

In [73]:
bad_crs_clean = (
    (df_clean["crs_elapsed_time"] < 1)
    | (df_clean["crs_elapsed_time"] > 1000)
)

df_clean.loc[
    bad_crs_clean,
    "crs_elapsed_time"
] = np.nan

## Clean invalid actual elapsed time

In [74]:
bad_actual_elapsed_clean = (
    (df_clean["actual_elapsed_time"] < 1)
    | (df_clean["actual_elapsed_time"] > 1500)
)

df_clean.loc[
    bad_actual_elapsed_clean,
    "actual_elapsed_time"
] = np.nan

## Clean invalid air time

In [75]:
bad_air_time_clean = (
    (df_clean["air_time"] < 1)
    | (df_clean["air_time"] > 1500)
)

df_clean.loc[
    bad_air_time_clean,
    "air_time"
] = np.nan

## Clean invalid distance

In [76]:
bad_distance_clean = (
    (df_clean["distance"] < 1)
    | (df_clean["distance"] > 6000)
)

df_clean.loc[
    bad_distance_clean,
    "distance"
] = np.nan

# PART 14 — HANDLE STRUCTURAL MISSINGNESS

We do **not** replace cancelled-flight arrival values with zero.

Missing means the operation did not happen or the field is not applicable.

In [77]:
# Preserve any departure information recorded before cancellation
df_clean["dep_time_at_cancellation"] = np.where(
    df_clean["cancelled"] == 1,
    df_clean["dep_time"],
    np.nan
)

In [78]:
# Cancelled flights should not be treated as normally departed
df_clean.loc[
    df_clean["cancelled"] == 1,
    "dep_time"
] = np.nan

# PART 15 — FLAG SUSPICIOUS RECORDS

We keep the 9 suspicious completed flights because deleting them would remove real flight records.

Instead, create a flag for later investigation.

In [79]:
df_clean["missing_operational_duration"] = (
    (df_clean["flight_status"] == "COMPLETED")
    & (
        df_clean["air_time"].isna()
        | df_clean["actual_elapsed_time"].isna()
    )
)

In [80]:
print(
    "Suspicious completed flights:",
    df_clean["missing_operational_duration"].sum()
)

Suspicious completed flights: 9

# PART 16 — FLAG EXTREME DELAYS

In [81]:
df_clean["extreme_dep_delay"] = (
    df_clean["dep_delay"].abs() > 720
)

In [82]:
df_clean["extreme_arr_delay"] = (
    df_clean["arr_delay"].abs() > 720
)

In [83]:
print(
    "Extreme departure delays:",
    df_clean["extreme_dep_delay"].sum()
)

print(
    "Extreme arrival delays:",
    df_clean["extreme_arr_delay"].sum()
)

Extreme departure delays: 2313
Extreme arrival delays: 2267

# PART 17 — CREATE BUSINESS-FRIENDLY FLAGS

In [84]:
df_clean["is_cancelled"] = (
    df_clean["cancelled"] == 1
).astype(int)

In [85]:
df_clean["is_diverted"] = (
    df_clean["diverted"] == 1
).astype(int)

In [86]:
df_clean["is_irregular_operation"] = (
    (df_clean["cancelled"] == 1)
    | (df_clean["diverted"] == 1)
).astype(int)

In [87]:
df_clean["is_departure_delayed"] = (
    df_clean["dep_delay"] >= 15
).astype("Int64")

In [88]:
df_clean["is_arrival_delayed"] = (
    df_clean["arr_delay"] >= 15
).astype("Int64")

In [89]:
df_clean["severe_departure_delay"] = (
    df_clean["dep_delay"] >= 60
).astype("Int64")

In [90]:
df_clean["severe_arrival_delay"] = (
    df_clean["arr_delay"] >= 60
).astype("Int64")

# PART 18 — RECHECK DATA QUALITY AFTER CLEANING

In [91]:
print("Original rows:", len(df))
print("Cleaned rows :", len(df_clean))

Original rows: 1847242
Cleaned rows : 1847242

In [92]:
print(
    "Duplicate rows after cleaning:",
    df_clean.duplicated().sum()
)

Duplicate rows after cleaning: 0

In [93]:
invalid_dep_after = (
    df_clean["dep_time"].notna()
    & ~df_clean["dep_time"].apply(valid_hhmm)
)

print(
    "Invalid dep_time after cleaning:",
    invalid_dep_after.sum()
)

Invalid dep_time after cleaning: 0

In [94]:
invalid_arr_after = (
    df_clean["arr_time"].notna()
    & ~df_clean["arr_time"].apply(valid_hhmm)
)

print(
    "Invalid arr_time after cleaning:",
    invalid_arr_after.sum()
)

Invalid arr_time after cleaning: 0

In [95]:
invalid_taxi_in_after = (
    df_clean["taxi_in"].notna()
    & (
        (df_clean["taxi_in"] < 0)
        | (df_clean["taxi_in"] > 300)
    )
)

print(
    "Invalid taxi_in after cleaning:",
    invalid_taxi_in_after.sum()
)

Invalid taxi_in after cleaning: 0

In [96]:
invalid_crs_after = (
    df_clean["crs_elapsed_time"].notna()
    & (
        (df_clean["crs_elapsed_time"] < 1)
        | (df_clean["crs_elapsed_time"] > 1000)
    )
)

print(
    "Invalid crs_elapsed_time after cleaning:",
    invalid_crs_after.sum()
)

Invalid crs_elapsed_time after cleaning: 0

# PART 19 — BUSINESS RULE VALIDATION

In [97]:
check1 = (
    (df_clean["cancelled"] == 1)
    & df_clean["arr_time"].notna()
).sum()

print("Cancelled + arrival time:", check1)

Cancelled + arrival time: 0

In [98]:
check2 = (
    (df_clean["cancelled"] == 1)
    & df_clean["arr_delay"].notna()
).sum()

print("Cancelled + arrival delay:", check2)

Cancelled + arrival delay: 0

In [99]:
check3 = (
    (df_clean["diverted"] == 1)
    & (df_clean["cancelled"] == 1)
).sum()

print("Diverted + cancelled:", check3)

Diverted + cancelled: 0

# PART 20 — FINAL ASSERTIONS

These checks stop the pipeline if important data-quality rules fail.

In [100]:
assert df_clean.duplicated().sum() == 0

print("✓ No duplicate rows")

✓ No duplicate rows

In [101]:
assert invalid_dep_after.sum() == 0

print("✓ No invalid departure HHMM values")

✓ No invalid departure HHMM values

In [102]:
assert invalid_arr_after.sum() == 0

print("✓ No invalid arrival HHMM values")

✓ No invalid arrival HHMM values

In [103]:
assert invalid_taxi_in_after.sum() == 0

print("✓ No invalid taxi_in values")

✓ No invalid taxi_in values

In [104]:
assert invalid_crs_after.sum() == 0

print("✓ No invalid crs_elapsed_time values")

✓ No invalid crs_elapsed_time values

In [105]:
assert check3 == 0

print("✓ No diverted + cancelled conflicts")

✓ No diverted + cancelled conflicts

# PART 21 — BEFORE VS AFTER

In [106]:
comparison = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Invalid dep_time",
        "Invalid arr_time",
        "Invalid taxi_in",
        "Invalid crs_elapsed_time",
        "Duplicate rows"
    ],
    "Original": [
        len(df),
        df.shape[1],
        invalid_dep_time.sum(),
        invalid_arr_time.sum(),
        len(bad_taxi_in),
        len(bad_crs_elapsed),
        df.duplicated().sum()
    ],
    "Cleaned": [
        len(df_clean),
        df_clean.shape[1],
        invalid_dep_after.sum(),
        invalid_arr_after.sum(),
        invalid_taxi_in_after.sum(),
        invalid_crs_after.sum(),
        df_clean.duplicated().sum()
    ]
})

comparison

                     Metric  Original  Cleaned
0                      Rows   1847242  1847242
1                   Columns        44       55
2          Invalid dep_time       156        0
3          Invalid arr_time       894        0
4           Invalid taxi_in         5        0
5  Invalid crs_elapsed_time         9        0
6            Duplicate rows         0        0

# PART 22 — FINAL DATASET CHECK

In [107]:
print("Final shape:", df_clean.shape)

Final shape: (1847242, 55)

In [108]:
df_clean.head()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,mkt_carrier_fl_num,origin,origin_city_name,origin_state_abr,origin_state_nm,dest,dest_city_name,dest_state_abr,dest_state_nm,crs_dep_time,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,flight_status,dep_time_at_cancellation,missing_operational_duration,extreme_dep_delay,extreme_arr_delay,is_cancelled,is_diverted,is_irregular_operation,is_departure_delayed,is_arrival_delayed,severe_departure_delay,severe_arrival_delay
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1,JFK,"New York, NY",NY,New York,LAX,"Los Angeles, CA",CA,California,700,657.0,-3.0,0.0,0.0,67.0,11.0,1021,1104.0,43.0,43.0,1.0,0.0,NaN,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0,COMPLETED,NaN,False,False,False,0,0,0,0,1,0,0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,10,LAX,"Los Angeles, CA",CA,California,JFK,"New York, NY",NY,New York,2130,2128.0,-2.0,0.0,0.0,16.0,6.0,551,520.0,-31.0,0.0,0.0,0.0,NaN,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN,COMPLETED,NaN,False,False,False,0,0,0,0,0,0,0
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1002,MIA,"Miami, FL",FL,Florida,MSY,"New Orleans, LA",LA,Louisiana,2245,2252.0,7.0,7.0,0.0,16.0,3.0,2359,2356.0,-3.0,0.0,0.0,0.0,NaN,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN,COMPLETED,NaN,False,False,False,0,0,0,0,0,0,0
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1003,DEN,"Denver, CO",CO,Colorado,MIA,"Miami, FL",FL,Florida,2338,2338.0,0.0,0.0,0.0,13.0,6.0,527,508.0,-19.0,0.0,0.0,0.0,NaN,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN,COMPLETED,NaN,False,False,False,0,0,0,0,0,0,0
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,1004,BOS,"Boston, MA",MA,Massachusetts,CLT,"Charlotte, NC",NC,North Carolina,757,756.0,-1.0,0.0,0.0,26.0,4.0,1030,1023.0,-7.0,0.0,0.0,0.0,NaN,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN,COMPLETED,NaN,False,False,False,0,0,0,0,0,0,0

In [109]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1847242 entries, 0 to 1847241
Data columns (total 55 columns):
 #   Column                        Dtype
---  ------                        -----
 0   year                          int64
 1   quarter                       int64
 2   month                         int64
 3   day_of_month                  int64
 4   day_of_week                   int64
 5   fl_date                       datetime64[ns]
 6   mkt_unique_carrier            object
 7   branded_code_share            object
 8   mkt_carrier_airline_id        int64
 9   mkt_carrier                   object
 10  mkt_carrier_fl_num            int64
 11  origin                        object
 12  origin_city_name              object
 13  origin_state_abr              object
 14  origin_state_nm               object
 15  dest                          object
 16  dest_city_name                object
 17  dest_state_abr                object
 18  dest_state_nm                 object
 19  crs_dep_time                  int64
 20  dep_time                      float64
 21  dep_delay                     float64
 22  dep_delay_new                 float64
 23  dep_del15                     float64
 24  taxi_out                      float64
 25  taxi_in                       float64
 26  crs_arr_time                  int64
 27  arr_time                      float64
 28  arr_delay                     float64
 29  arr_delay_new                 float64
 30  arr_del15                     float64
 31  cancelled                     float64
 32  cancellation_code             object
 33  diverted                      float64
 34  crs_elapsed_time              float64
 35  actual_elapsed_time           float64
 36  air_time                      float64
 37  distance                      float64
 38  carrier_delay                 float64
 39  weather_delay                 float64
 40  nas_delay                     float64
 41  security_delay                float64
 42  late_aircraft_delay           float64
 43  flight_status                 object
 44  dep_time_at_cancellation      float64
 45  missing_operational_duration  bool
 46  extreme_dep_delay             bool
 47  extreme_arr_delay             bool
 48  is_cancelled                  int64
 49  is_diverted                   int64
 50  is_irregular_operation        int64
 51  is_departure_delayed          Int64
 52  is_arrival_delayed            Int64
 53  severe_departure_delay        Int64
 54  severe_arrival_delay          Int64
dtypes: Int64(4), bool(3), datetime64[ns](1), float64(22), int64(12), object(13)
memory usage: 745.2+ MB

# PART 23 — SAVE CLEANED DATA

This file will be used for:

- Exploratory Data Analysis
- KPI analysis
- Root-cause analysis
- Power BI dashboard
- Airline operations business recommendations

In [111]:
output_path = r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv"

df_clean.to_csv(
    output_path,
    index=False
)

print("Cleaned file saved:", output_path)

Cleaned file saved: D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv

# Extra

In [112]:
# Check negative departure delays
negative_dep_delay = df_clean[df_clean["dep_delay"] < 0]

print("Negative dep_delay:", len(negative_dep_delay))

Negative dep_delay: 1048051

In [113]:
# Check negative arrival delays
negative_arr_delay = df_clean[df_clean["arr_delay"] < 0]

print("Negative arr_delay:", len(negative_arr_delay))

Negative arr_delay: 1114558

In [114]:
negative_dep_delay[
    ["fl_date", "mkt_carrier", "origin", "dest", "dep_delay"]
].sort_values("dep_delay").head(20)

           fl_date mkt_carrier origin dest  dep_delay
1030003 2026-02-22          AA    DCA  BTR      -66.0
1094652 2026-02-25          AS    CDV  ANC      -65.0
369899  2026-01-19          UA    IAH  AMA      -60.0
293824  2026-01-15          WN    STL  DSM      -59.0
47377   2026-01-03          AS    YAK  CDV      -58.0
47374   2026-01-03          AS    CDV  ANC      -58.0
726397  2026-02-07          AS    ADK  ANC      -57.0
1468812 2026-03-14          UA    DEN  SGU      -56.0
1517653 2026-03-16          WN    GSP  BNA      -56.0
591007  2026-01-31          AS    YAK  CDV      -56.0
735147  2026-02-07          UA    DEC  ORD      -52.0
640699  2026-02-02          WN    BUF  BWI      -51.0
1616664 2026-03-21          DL    DTW  MQT      -51.0
651674  2026-02-03          DL    ATL  BWI      -50.0
1457845 2026-03-14          AS    ADK  ANC      -49.0
1391184 2026-03-11          AS    ADK  ANC      -48.0
1038372 2026-02-22          F9    IAD  DFW      -45.0
1320420 2026-03-08          AA    AUS  JFK      -44.0
591004  2026-01-31          AS    CDV  ANC      -44.0
1116765 2026-02-26          DL    PBI  ATL      -43.0

In [115]:
negative_arr_delay[
    ["fl_date", "mkt_carrier", "origin", "dest", "arr_delay"]
].sort_values("arr_delay").head(20)

           fl_date mkt_carrier origin dest  arr_delay
1278109 2026-03-06          AA    DFW  KOA      -90.0
1038372 2026-02-22          F9    IAD  DFW      -89.0
663751  2026-02-04          AA    JFK  LAX      -86.0
670886  2026-02-04          DL    JFK  LAX      -86.0
668090  2026-02-04          B6    JFK  SAN      -86.0
267041  2026-01-14          DL    JFK  LAX      -85.0
679120  2026-02-04          WN    BWI  SAN      -85.0
674381  2026-02-04          UA    IAD  LAX      -84.0
1278852 2026-03-06          AA    DFW  OGG      -84.0
1292479 2026-03-06          UA    IAH  HNL      -82.0
670909  2026-02-04          DL    JFK  PHX      -82.0
1287255 2026-03-06          DL    ATL  HNL      -82.0
664195  2026-02-04          AA    PHL  LAX      -82.0
1307936 2026-03-07          DL    DTW  HNL      -82.0
681562  2026-02-05          AA    PHL  DFW      -81.0
662339  2026-02-04          AA    PHL  SAN      -81.0
680127  2026-02-05          AA    BWI  DFW      -81.0
1301621 2026-03-07          AA    PHX  HNL      -81.0
1312258 2026-03-07          UA    DEN  KOA      -80.0
1531874 2026-03-17          UA    EWR  SAN      -80.0

In [116]:
df_clean["extreme_negative_dep_delay"] = (
    df_clean["dep_delay"] < -720
)

In [117]:
df_clean["extreme_negative_arr_delay"] = (
    df_clean["arr_delay"] < -720
)

In [118]:
print(
    "Extreme negative dep_delay:",
    df_clean["extreme_negative_dep_delay"].sum()
)

print(
    "Extreme negative arr_delay:",
    df_clean["extreme_negative_arr_delay"].sum()
)

Extreme negative dep_delay: 0
Extreme negative arr_delay: 0

In [119]:
df_clean.loc[
    df_clean["extreme_negative_dep_delay"],
    "dep_delay"
] = np.nan

In [120]:
df_clean.loc[
    df_clean["extreme_negative_arr_delay"],
    "arr_delay"
] = np.nan

In [121]:
print(
    "Extreme negative dep_delay after cleaning:",
    (df_clean["dep_delay"] < -720).sum()
)

print(
    "Extreme negative arr_delay after cleaning:",
    (df_clean["arr_delay"] < -720).sum()
)

Extreme negative dep_delay after cleaning: 0
Extreme negative arr_delay after cleaning: 0

In [122]:
print("Negative dep_delay:", (df_clean["dep_delay"] < 0).sum())
print("Negative arr_delay:", (df_clean["arr_delay"] < 0).sum())

Negative dep_delay: 1048051
Negative arr_delay: 1114558

In [123]:
print(
    "Extreme negative dep_delay:",
    (df_clean["dep_delay"] < -720).sum()
)

print(
    "Extreme negative arr_delay:",
    (df_clean["arr_delay"] < -720).sum()
)

Extreme negative dep_delay: 0
Extreme negative arr_delay: 0

In [124]:
df_clean['dep_delay'].sort_values(ascending=True)

1030003   -66.0
1094652   -65.0
369899    -60.0
293824    -59.0
47374     -58.0
           ...
1844566     NaN
1844991     NaN
1845075     NaN
1846157     NaN
1846459     NaN
Name: dep_delay, Length: 1847242, dtype: float64

# ✅ DATA CLEANING COMPLETE

## What I did

1. Understood the original dataset.
2. Checked duplicates.
3. Classified flights as completed/cancelled/diverted.
4. Investigated missing values by flight status.
5. Found suspicious completed-flight missing values.
6. Validated HHMM time values.
7. Found and cleaned invalid numeric values.
8. Checked airline business rules.
9. Investigated extreme delays.
10. Preserved structurally valid missing values.
11. Flagged suspicious records instead of deleting them.
12. Flagged extreme delays instead of deleting them.
13. Validated the cleaned dataset.
14. Saved the analysis-ready dataset.

## Main principle

**I cleaned the data based on business meaning, not simply by deleting missing values or outliers.**