In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

data_path = Path(r"D:\Data Analyst\EXCEL\api\processed\flights_2026_q1.csv")

flights = pd.read_csv(data_path)

print("Dataset loaded successfully.")
print("Shape:", flights.shape)

Dataset loaded successfully.
Shape: (1847242, 43)

In [2]:
df=flights.copy()

In [3]:
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

# correcting columns

In [4]:
df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(' ', '_')
)
df.columns

Index(['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date',
       'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id',
       'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name',
       'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name',
       'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time',
       'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in',
       'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15',
       'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time',
       'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay'],
      dtype='object')

In [5]:
df.head()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

In [6]:
df.tail()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
1847237,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,80.0,85.0,54.0,402.0,0.0,0.0,5.0,0.0,16.0
1847238,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,140.0,143.0,126.0,1020.0,NaN,NaN,NaN,NaN,NaN
1847239,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,145.0,141.0,125.0,930.0,NaN,NaN,NaN,NaN,NaN
1847240,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,95.0,102.0,85.0,395.0,NaN,NaN,NaN,NaN,NaN
1847241,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,130.0,118.0,100.0,794.0,NaN,NaN,NaN,NaN,NaN

# Handling Duplicate columns

In [7]:
df.duplicated().sum()

np.int64(0)

# Handling Null values

In [8]:
null_values_count=df.isna().sum().sort_values(ascending=False)
null_values_count

cancellation_code         1784931
late_aircraft_delay       1462816
carrier_delay             1462816
security_delay            1462816
nas_delay                 1462816
weather_delay             1462816
air_time                    67057
actual_elapsed_time         67057
arr_delay_new               67048
arr_delay                   67048
arr_del15                   67048
arr_time                    62950
taxi_in                     62950
taxi_out                    61991
dep_delay                   60974
dep_del15                   60974
dep_delay_new               60974
dep_time                    60784
crs_elapsed_time                1
month                           0
quarter                         0
year                            0
branded_code_share              0
mkt_unique_carrier              0
fl_date                         0
day_of_week                     0
day_of_month                    0
mkt_carrier_fl_num              0
mkt_carrier                     0
mkt_carrier_airline_id          0
crs_dep_time                    0
crs_arr_time                    0
dest_city_name                  0
dest_state_abr                  0
dest_state_nm                   0
origin_city_name                0
origin                          0
origin_state_abr                0
origin_state_nm                 0
dest                            0
cancelled                       0
diverted                        0
distance                        0
dtype: int64

In [9]:
df.head()

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

- if cancelled code is 0 then the cancellation code should be null because not cancelled

In [10]:
df['cancelled'].unique()

array([0., 1.])

In [11]:
df.loc[
    df['cancelled'] == 0,
    'cancellation_code'
].value_counts(dropna=False)

cancellation_code
NaN    1784931
Name: count, dtype: int64

In [12]:
df.loc[
    df['cancelled'] == 1,
    'cancellation_code'
].value_counts(dropna=False)

cancellation_code
B    47348
A    10042
C     4852
D       69
Name: count, dtype: int64

- if cancelled=1 then dep_time,dep_delay,dep_delay_new,dep_del15 should be null and cancellation code should not be null

In [13]:
df[df['cancelled']==1]

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
1303,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,180.0,NaN,NaN,986.0,NaN,NaN,NaN,NaN,NaN
1547,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,240.0,NaN,NaN,1460.0,NaN,NaN,NaN,NaN,NaN
2478,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,139.0,NaN,NaN,813.0,NaN,NaN,NaN,NaN,NaN
3952,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,...,0.0,59.0,NaN,NaN,119.0,NaN,NaN,NaN,NaN,NaN
4271,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,...,0.0,72.0,NaN,NaN,221.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844566,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,65.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN
1844991,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,145.0,NaN,NaN,895.0,NaN,NaN,NaN,NaN,NaN
1845075,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,75.0,NaN,NaN,239.0,NaN,NaN,NaN,NaN,NaN
1846157,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,280.0,NaN,NaN,1824.0,NaN,NaN,NaN,NaN,NaN
1846459,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,175.0,NaN,NaN,1120.0,NaN,NaN,NaN,NaN,NaN

In [14]:
cancelled=df[df['cancelled']==1][['dep_time','dep_delay', 'dep_delay_new', 'dep_del15', 
    'taxi_out', 'taxi_in', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15',
    'cancelled','actual_elapsed_time', 'air_time', 'carrier_delay',
       'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']]
cancelled

,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,taxi_in,arr_time,arr_delay,arr_delay_new,arr_del15,cancelled,actual_elapsed_time,air_time,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
1303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3952,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1844991,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1845075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1846157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1846459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
cols = [
    'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15',
    'taxi_out', 'taxi_in', 'arr_time', 'arr_delay',
    'arr_delay_new', 'arr_del15', 'actual_elapsed_time',
    'air_time', 'carrier_delay', 'weather_delay',
    'nas_delay', 'security_delay', 'late_aircraft_delay'
]

# Find cancelled flights where all these columns are NULL
mask = (
    (df['cancelled'] == 1) &
    (df[cols].isna().all(axis=1))
)

# Convert columns to object so they can contain text
df[cols] = df[cols].astype('object')

# Fill only those cancelled rows
df.loc[mask, cols] = 'flight cancelled'

In [16]:
df[cols].isna().all(axis=1)

0          False
1          False
2          False
3          False
4          False
           ...
1847237    False
1847238    False
1847239    False
1847240    False
1847241    False
Length: 1847242, dtype: bool

In [17]:
df[df['cancelled']==1]

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
1303,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,180.0,flight cancelled,flight cancelled,986.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
1547,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,240.0,flight cancelled,flight cancelled,1460.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
2478,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,139.0,flight cancelled,flight cancelled,813.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
3952,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,...,0.0,59.0,flight cancelled,flight cancelled,119.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
4271,2026,1,1,1,4,2026-01-01,AA,AA_CODESHARE,19805,AA,...,0.0,72.0,flight cancelled,flight cancelled,221.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1844566,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,65.0,flight cancelled,flight cancelled,239.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
1844991,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,145.0,flight cancelled,flight cancelled,895.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
1845075,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,75.0,flight cancelled,flight cancelled,239.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
1846157,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,280.0,flight cancelled,flight cancelled,1824.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled
1846459,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,175.0,flight cancelled,flight cancelled,1120.0,flight cancelled,flight cancelled,flight cancelled,flight cancelled,flight cancelled

In [18]:
df.shape

(1847242, 43)

In [19]:
df.sample(100)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
1251034,2026,1,3,4,3,2026-03-04,UA,UA_CODESHARE,19977,UA,...,0.0,65.0,49.0,19.0,67.0,0.0,0.0,0.0,0.0,16.0
1406871,2026,1,3,12,4,2026-03-12,AA,AA,19805,AA,...,0.0,184.0,185.0,142.0,1096.0,26.0,0.0,1.0,0.0,14.0
1611784,2026,1,3,21,6,2026-03-21,AS,AS,19930,AS,...,0.0,378.0,349.0,333.0,2497.0,NaN,NaN,NaN,NaN,NaN
1711242,2026,1,3,25,3,2026-03-25,WN,WN,19393,WN,...,0.0,285.0,289.0,261.0,2329.0,NaN,NaN,NaN,NaN,NaN
114691,2026,1,1,6,2,2026-01-06,DL,DL,19790,DL,...,0.0,95.0,76.0,61.0,453.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412868,2026,1,1,22,4,2026-01-22,AA,AA,19805,AA,...,0.0,107.0,111.0,76.0,631.0,NaN,NaN,NaN,NaN,NaN
615499,2026,1,2,1,7,2026-02-01,G4,G4,20368,G4,...,0.0,178.0,156.0,137.0,1035.0,NaN,NaN,NaN,NaN,NaN
125389,2026,1,1,7,3,2026-01-07,AA,AA,19805,AA,...,0.0,194.0,180.0,164.0,1389.0,0.0,0.0,0.0,0.0,38.0
111243,2026,1,1,6,2,2026-01-06,AS,AS,19930,AS,...,0.0,156.0,150.0,127.0,933.0,NaN,NaN,NaN,NaN,NaN
1348555,2026,1,3,9,1,2026-03-09,AS,AS_CODESHARE,19930,AS,...,0.0,96.0,94.0,74.0,399.0,NaN,NaN,NaN,NaN,NaN

In [20]:
df.isna().sum()

year                            0
quarter                         0
month                           0
day_of_month                    0
day_of_week                     0
fl_date                         0
mkt_unique_carrier              0
branded_code_share              0
mkt_carrier_airline_id          0
mkt_carrier                     0
mkt_carrier_fl_num              0
origin                          0
origin_city_name                0
origin_state_abr                0
origin_state_nm                 0
dest                            0
dest_city_name                  0
dest_state_abr                  0
dest_state_nm                   0
crs_dep_time                    0
dep_time                        0
dep_delay                     190
dep_delay_new                 190
dep_del15                     190
taxi_out                     1207
taxi_in                      2166
crs_arr_time                    0
arr_time                     2166
arr_delay                    6264
arr_delay_new                6264
arr_del15                    6264
cancelled                       0
cancellation_code         1784931
diverted                        0
crs_elapsed_time                1
actual_elapsed_time          6273
air_time                     6273
distance                        0
carrier_delay             1402032
weather_delay             1402032
nas_delay                 1402032
security_delay            1402032
late_aircraft_delay       1402032
dtype: int64

In [21]:
df['cancellation_code']=df['cancellation_code'].fillna("Not_canceled")

In [22]:
df.isna().sum()

year                            0
quarter                         0
month                           0
day_of_month                    0
day_of_week                     0
fl_date                         0
mkt_unique_carrier              0
branded_code_share              0
mkt_carrier_airline_id          0
mkt_carrier                     0
mkt_carrier_fl_num              0
origin                          0
origin_city_name                0
origin_state_abr                0
origin_state_nm                 0
dest                            0
dest_city_name                  0
dest_state_abr                  0
dest_state_nm                   0
crs_dep_time                    0
dep_time                        0
dep_delay                     190
dep_delay_new                 190
dep_del15                     190
taxi_out                     1207
taxi_in                      2166
crs_arr_time                    0
arr_time                     2166
arr_delay                    6264
arr_delay_new                6264
arr_del15                    6264
cancelled                       0
cancellation_code               0
diverted                        0
crs_elapsed_time                1
actual_elapsed_time          6273
air_time                     6273
distance                        0
carrier_delay             1402032
weather_delay             1402032
nas_delay                 1402032
security_delay            1402032
late_aircraft_delay       1402032
dtype: int64

In [23]:
df[['carrier_delay','weather_delay','nas_delay','security_delay','late_aircraft_delay']]=df[['carrier_delay','weather_delay','nas_delay','security_delay','late_aircraft_delay']].fillna(0)

In [24]:
df.shape

(1847242, 43)

In [25]:
df.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                  190
dep_delay_new              190
dep_del15                  190
taxi_out                  1207
taxi_in                   2166
crs_arr_time                 0
arr_time                  2166
arr_delay                 6264
arr_delay_new             6264
arr_del15                 6264
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             1
actual_elapsed_time       6273
air_time                  6273
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [26]:
df.sample(100)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
334256,2026,1,1,17,6,2026-01-17,WN,WN,19393,WN,...,0.0,180.0,163.0,149.0,926.0,1.0,0.0,0.0,0.0,14.0
819601,2026,1,2,12,4,2026-02-12,AA,AA_CODESHARE,19805,AA,...,0.0,108.0,144.0,64.0,286.0,0.0,0.0,23.0,0.0,0.0
1469147,2026,1,3,14,6,2026-03-14,WN,WN,19393,WN,...,0.0,105.0,88.0,71.0,472.0,0,0,0,0,0
1590056,2026,1,3,20,5,2026-03-20,AS,AS,19930,AS,...,0.0,418.0,432.0,399.0,2994.0,0,0,0,0,0
1619551,2026,1,3,21,6,2026-03-21,UA,UA,19977,UA,...,0.0,236.0,196.0,168.0,1346.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827940,2026,1,2,12,4,2026-02-12,DL,DL_CODESHARE,19790,DL,...,0.0,89.0,75.0,45.0,187.0,0,0,0,0,0
846927,2026,1,2,13,5,2026-02-13,DL,DL,19790,DL,...,0.0,76.0,84.0,52.0,259.0,0.0,0.0,8.0,0.0,172.0
591283,2026,1,1,31,6,2026-01-31,AS,AS_CODESHARE,19930,AS,...,0.0,88.0,70.0,52.0,337.0,0,0,0,0,0
1227865,2026,1,3,3,2,2026-03-03,UA,UA,19977,UA,...,0.0,171.0,134.0,119.0,854.0,0,0,0,0,0
1467284,2026,1,3,14,6,2026-03-14,UA,UA_CODESHARE,19977,UA,...,0.0,91.0,67.0,44.0,296.0,0,0,0,0,0

In [27]:
df[df['dep_delay'].isna()]

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
6689,2026,1,1,1,4,2026-01-01,AS,AS_CODESHARE,19930,AS,...,0.0,104.0,NaN,NaN,447.0,0,0,0,0,0
14602,2026,1,1,1,4,2026-01-01,UA,UA_CODESHARE,19977,UA,...,0.0,69.0,NaN,NaN,109.0,0,0,0,0,0
26202,2026,1,1,2,5,2026-01-02,AS,AS_CODESHARE,19930,AS,...,0.0,103.0,NaN,NaN,480.0,0,0,0,0,0
36427,2026,1,1,2,5,2026-01-02,UA,UA_CODESHARE,19977,UA,...,0.0,122.0,NaN,NaN,421.0,0,0,0,0,0
48092,2026,1,1,3,6,2026-01-03,AS,AS_CODESHARE,19930,AS,...,0.0,86.0,NaN,NaN,263.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1838048,2026,1,3,31,2,2026-03-31,DL,DL_CODESHARE,19790,DL,...,0.0,73.0,NaN,NaN,198.0,0,0,0,0,0
1842325,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,111.0,NaN,NaN,344.0,0,0,0,0,0
1842914,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,129.0,NaN,NaN,530.0,0,0,0,0,0
1843242,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,131.0,NaN,NaN,566.0,0,0,0,0,0
1843268,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,185.0,NaN,NaN,849.0,0,0,0,0,0

In [28]:
df[df['arr_delay'].isna()]

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
60,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,285.0,NaN,NaN,2077.0,0,0,0,0,0
77,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,336.0,NaN,NaN,2174.0,0,0,0,0,0
308,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,203.0,NaN,NaN,1471.0,0,0,0,0,0
530,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,291.0,NaN,NaN,1916.0,0,0,0,0,0
730,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,179.0,NaN,NaN,1055.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1843252,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,1.0,226.0,NaN,NaN,1498.0,0,0,0,0,0
1843268,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,185.0,NaN,NaN,849.0,0,0,0,0,0
1844640,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,1.0,145.0,NaN,NaN,798.0,0,0,0,0,0
1845022,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,1.0,145.0,NaN,NaN,937.0,0,0,0,0,0
1845304,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,1.0,145.0,NaN,NaN,834.0,0,0,0,0,0

In [29]:
df['diverted'].unique()

array([0., 1.])

In [30]:
diverted=df[df['diverted']==1]

In [31]:
diverted.head(100)

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
60,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,285.0,NaN,NaN,2077.0,0,0,0,0,0
77,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,336.0,NaN,NaN,2174.0,0,0,0,0,0
308,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,203.0,NaN,NaN,1471.0,0,0,0,0,0
530,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,291.0,NaN,NaN,1916.0,0,0,0,0,0
730,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,1.0,179.0,NaN,NaN,1055.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25156,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,...,1.0,228.0,NaN,NaN,1533.0,0,0,0,0,0
25214,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,...,1.0,387.0,NaN,NaN,2540.0,0,0,0,0,0
25326,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,...,1.0,407.0,NaN,NaN,2704.0,0,0,0,0,0
25328,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,...,1.0,330.0,NaN,NaN,2446.0,0,0,0,0,0
25381,2026,1,1,2,5,2026-01-02,AS,AS,19930,AS,...,1.0,249.0,NaN,NaN,1490.0,0,0,0,0,0

In [32]:
diverted.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                    0
dep_delay_new                0
dep_del15                    0
taxi_out                     0
taxi_in                    639
crs_arr_time                 0
arr_time                   639
arr_delay                 4737
arr_delay_new             4737
arr_del15                 4737
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             0
actual_elapsed_time       4737
air_time                  4737
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [39]:
cols1 = ['arr_delay',
    'arr_delay_new', 'arr_del15', 'actual_elapsed_time',
    'air_time',
]

# Find cancelled flights where all these columns are NULL
mask1 = (
    (df['diverted'] == 1) &
    (df[cols1].isna().all(axis=1))
)

# Convert columns to object so they can contain text
df[cols1] = df[cols1].astype('object')

# Fill only those cancelled rows
df.loc[mask1, cols1] = 'flight diverted'

In [40]:
df.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                  190
dep_delay_new              190
dep_del15                  190
taxi_out                  1207
taxi_in                   2166
crs_arr_time                 0
arr_time                  2166
arr_delay                 1527
arr_delay_new             1527
arr_del15                 1527
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             1
actual_elapsed_time       1536
air_time                  1536
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [45]:
arrival=df[['arr_time','arr_delay','arr_delay_new','arr_del15','actual_elapsed_time','air_time','cancelled',"diverted"]]

In [51]:
df['cancelled'].unique()

array([0., 1.])

In [52]:
arrival.isna().sum()

arr_time               2166
arr_delay              1527
arr_delay_new          1527
arr_del15              1527
actual_elapsed_time    1536
air_time               1536
cancelled                 0
diverted                  0
dtype: int64

In [59]:
arrival[arrival['arr_time'].isna()]

,arr_time,arr_delay,arr_delay_new,arr_del15,actual_elapsed_time,air_time,cancelled,diverted
5064,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
5316,NaN,flight diverted,flight diverted,flight diverted,flight diverted,flight diverted,0.0,1.0
6627,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
6674,NaN,flight diverted,flight diverted,flight diverted,flight diverted,flight diverted,0.0,1.0
6677,NaN,flight diverted,flight diverted,flight diverted,flight diverted,flight diverted,0.0,1.0
...,...,...,...,...,...,...,...,...
1842325,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1842914,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1843162,NaN,flight diverted,flight diverted,flight diverted,flight diverted,flight diverted,0.0,1.0
1843242,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0
1843268,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0

In [72]:
df.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                  190
dep_delay_new              190
dep_del15                  190
taxi_out                  1207
taxi_in                   2166
crs_arr_time                 0
arr_time                  2166
arr_delay                    0
arr_delay_new                0
arr_del15                    0
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             1
actual_elapsed_time          9
air_time                     9
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [76]:
df.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                  190
dep_delay_new              190
dep_del15                  190
taxi_out                  1207
taxi_in                   2166
crs_arr_time                 0
arr_time                  2166
arr_delay                    0
arr_delay_new                0
arr_del15                    0
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             1
actual_elapsed_time          9
air_time                     9
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

In [78]:
df[df['dep_delay'].isna()]

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
6689,2026,1,1,1,4,2026-01-01,AS,AS_CODESHARE,19930,AS,...,0.0,104.0,flight cancelled,flight cancelled,447.0,0,0,0,0,0
14602,2026,1,1,1,4,2026-01-01,UA,UA_CODESHARE,19977,UA,...,0.0,69.0,flight cancelled,flight cancelled,109.0,0,0,0,0,0
26202,2026,1,1,2,5,2026-01-02,AS,AS_CODESHARE,19930,AS,...,0.0,103.0,flight cancelled,flight cancelled,480.0,0,0,0,0,0
36427,2026,1,1,2,5,2026-01-02,UA,UA_CODESHARE,19977,UA,...,0.0,122.0,flight cancelled,flight cancelled,421.0,0,0,0,0,0
48092,2026,1,1,3,6,2026-01-03,AS,AS_CODESHARE,19930,AS,...,0.0,86.0,flight cancelled,flight cancelled,263.0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1838048,2026,1,3,31,2,2026-03-31,DL,DL_CODESHARE,19790,DL,...,0.0,73.0,flight cancelled,flight cancelled,198.0,0,0,0,0,0
1842325,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,111.0,flight cancelled,flight cancelled,344.0,0,0,0,0,0
1842914,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,129.0,flight cancelled,flight cancelled,530.0,0,0,0,0,0
1843242,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,131.0,flight cancelled,flight cancelled,566.0,0,0,0,0,0
1843268,2026,1,3,31,2,2026-03-31,UA,UA_CODESHARE,19977,UA,...,0.0,185.0,flight cancelled,flight cancelled,849.0,0,0,0,0,0

In [85]:
null=df[df['cancelled']==1].fillna("flight cancelled")

In [86]:
null.isna().sum()

year                      0
quarter                   0
month                     0
day_of_month              0
day_of_week               0
fl_date                   0
mkt_unique_carrier        0
branded_code_share        0
mkt_carrier_airline_id    0
mkt_carrier               0
mkt_carrier_fl_num        0
origin                    0
origin_city_name          0
origin_state_abr          0
origin_state_nm           0
dest                      0
dest_city_name            0
dest_state_abr            0
dest_state_nm             0
crs_dep_time              0
dep_time                  0
dep_delay                 0
dep_delay_new             0
dep_del15                 0
taxi_out                  0
taxi_in                   0
crs_arr_time              0
arr_time                  0
arr_delay                 0
arr_delay_new             0
arr_del15                 0
cancelled                 0
cancellation_code         0
diverted                  0
crs_elapsed_time          0
actual_elapsed_time       0
air_time                  0
distance                  0
carrier_delay             0
weather_delay             0
nas_delay                 0
security_delay            0
late_aircraft_delay       0
dtype: int64

In [87]:
df.isna().sum()

year                         0
quarter                      0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
mkt_unique_carrier           0
branded_code_share           0
mkt_carrier_airline_id       0
mkt_carrier                  0
mkt_carrier_fl_num           0
origin                       0
origin_city_name             0
origin_state_abr             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_abr               0
dest_state_nm                0
crs_dep_time                 0
dep_time                     0
dep_delay                  190
dep_delay_new              190
dep_del15                  190
taxi_out                  1207
taxi_in                   2166
crs_arr_time                 0
arr_time                  2166
arr_delay                    0
arr_delay_new                0
arr_del15                    0
cancelled                    0
cancellation_code            0
diverted                     0
crs_elapsed_time             1
actual_elapsed_time          9
air_time                     9
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64