In [1]:
import pandas as pd

In [2]:
flights = pd.read_csv(
    r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv"
)

airport_ref = pd.read_csv(
    r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\raw\airports\airport_reference.csv"
)

weather = pd.read_csv(
    r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\weather_cleaned.csv"
)

C:\Users\bhupa\AppData\Local\Temp\ipykernel_18376\1622160132.py:1: DtypeWarning: Columns (60,66) have mixed types. Specify dtype option on import or set low_memory=False.
  flights = pd.read_csv(

In [3]:
print("Flights:", flights.shape)
print("Airport reference:", airport_ref.shape)
print("Weather:", weather.shape)

Flights: (1847242, 70)
Airport reference: (362, 7)
Weather: (781920, 7)

In [4]:
print("FLIGHTS")
display(flights.head())

FLIGHTS

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,origin_timezone,dest_airport_name,dest_city,dest_country,dest_latitude,dest_longitude,dest_timezone,dep_hour,dep_minute,scheduled_departure
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,-5,Los Angeles International Airport,Los Angeles,United States,33.942501,-118.407997,-8,7,0,2026-01-01 07:00:00
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,-8,John F Kennedy International Airport,New York,United States,40.639801,-73.778900,-5,21,30,2026-01-01 21:30:00
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,-5,Louis Armstrong New Orleans International Airport,New Orleans,United States,29.993401,-90.258003,-6,22,45,2026-01-01 22:45:00
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,-7,Miami International Airport,Miami,United States,25.793200,-80.290604,-5,23,38,2026-01-01 23:38:00
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,-5,Charlotte Douglas International Airport,Charlotte,United States,35.214001,-80.943100,-5,7,57,2026-01-01 07:57:00

In [5]:
print("AIRPORT REFERENCE")
display(airport_ref.head())

AIRPORT REFERENCE

,iata_code,airport_name,city,country,latitude,longitude,timezone
0,PPG,Pago Pago International Airport,Pago Pago,American Samoa,-14.331000,-170.710007,-11
1,SPN,Saipan International Airport,Saipan,Northern Mariana Islands,15.119000,145.729004,10
2,GUM,Antonio B. Won Pat International Airport,Agana,Guam,13.483400,144.796005,10
3,STT,Cyril E. King Airport,St. Thomas,Virgin Islands,18.337299,-64.973396,-4
4,STX,Henry E Rohlsen Airport,St. Croix Island,Virgin Islands,17.701900,-64.798599,-4

In [6]:
print("WEATHER")
display(weather.head())

WEATHER

,airport_code,date,hour,temperature,precipitation,wind_speed,weather_code
0,PPG,2026-01-01,0,29.4,0.0,10.1,3
1,PPG,2026-01-01,1,29.3,0.1,9.9,51
2,PPG,2026-01-01,2,26.5,0.2,21.1,51
3,PPG,2026-01-01,3,27.6,0.0,10.3,3
4,PPG,2026-01-01,4,28.1,0.0,8.6,3

In [7]:
flights[
    ["fl_date", "origin", "crs_dep_time"]
].head(10)

      fl_date origin  crs_dep_time
0  2026-01-01    JFK           700
1  2026-01-01    LAX          2130
2  2026-01-01    MIA          2245
3  2026-01-01    DEN          2338
4  2026-01-01    BOS           757
5  2026-01-01    SFO          2359
6  2026-01-01    MIA          1926
7  2026-01-01    DFW          1910
8  2026-01-01    DFW          1646
9  2026-01-01    DFW          2105

In [8]:
weather[
    [
        "airport_code",
        "date",
        "hour",
        "temperature",
        "precipitation",
        "wind_speed",
        "weather_code"
    ]
].head(10)

,airport_code,date,hour,temperature,precipitation,wind_speed,weather_code
0,PPG,2026-01-01,0,29.4,0.0,10.1,3
1,PPG,2026-01-01,1,29.3,0.1,9.9,51
2,PPG,2026-01-01,2,26.5,0.2,21.1,51
3,PPG,2026-01-01,3,27.6,0.0,10.3,3
4,PPG,2026-01-01,4,28.1,0.0,8.6,3
5,PPG,2026-01-01,5,28.1,0.0,9.4,3
6,PPG,2026-01-01,6,28.2,0.0,9.4,3
7,PPG,2026-01-01,7,28.2,0.0,9.0,2
8,PPG,2026-01-01,8,28.2,0.0,8.0,3
9,PPG,2026-01-01,9,28.2,0.0,8.0,3

In [9]:
print("Flights:", flights.shape)
print("Airport reference:", airport_ref.shape)
print("Weather:", weather.shape)

Flights: (1847242, 70)
Airport reference: (362, 7)
Weather: (781920, 7)

In [10]:
flights_weather = flights.copy()

In [11]:
flights_weather["fl_date"] = pd.to_datetime(
    flights_weather["fl_date"]
)

In [12]:
print(flights_weather["fl_date"].dtype)

datetime64[ns]

In [13]:
flights_weather["crs_dep_time"] = pd.to_numeric(
    flights_weather["crs_dep_time"],
    errors="coerce"
)

In [14]:
flights_weather["departure_hour"] = (
    flights_weather["crs_dep_time"] // 100
)

In [15]:
flights_weather[
    ["fl_date", "origin", "crs_dep_time", "departure_hour"]
].head(20)

      fl_date origin  crs_dep_time  departure_hour
0  2026-01-01    JFK           700               7
1  2026-01-01    LAX          2130              21
2  2026-01-01    MIA          2245              22
3  2026-01-01    DEN          2338              23
4  2026-01-01    BOS           757               7
5  2026-01-01    SFO          2359              23
6  2026-01-01    MIA          1926              19
7  2026-01-01    DFW          1910              19
8  2026-01-01    DFW          1646              16
9  2026-01-01    DFW          2105              21
10 2026-01-01    CLT          1315              13
11 2026-01-01    DFW          2257              22
12 2026-01-01    DFW           809               8
13 2026-01-01    TUS          1030              10
14 2026-01-01    DFW           920               9
15 2026-01-01    JFK           530               5
16 2026-01-01    PHX          1315              13
17 2026-01-01    SJC           600               6
18 2026-01-01    HNL          1950              19
19 2026-01-01    DTW           530               5

In [16]:
print(
    flights_weather["departure_hour"]
    .value_counts()
    .sort_index()
)

departure_hour
0       2261
1        941
2        391
3        156
4         48
5      47741
6     124616
7     133721
8     126796
9     107047
10    117464
11    114229
12    117434
13    109839
14    109699
15    107285
16    108937
17    121344
18    107836
19    101692
20     76844
21     60699
22     37574
23     12648
Name: count, dtype: int64

In [17]:
invalid_hours = flights_weather[
    (flights_weather["departure_hour"] < 0) |
    (flights_weather["departure_hour"] > 23)
]

print("Invalid departure hours:", len(invalid_hours))

Invalid departure hours: 0

In [18]:
print(
    "Missing departure hours:",
    flights_weather["departure_hour"].isna().sum()
)

Missing departure hours: 0

In [19]:
print("Invalid departure hours:", len(invalid_hours))
print("Missing departure hours:", flights_weather["departure_hour"].isna().sum())

Invalid departure hours: 0
Missing departure hours: 0

In [20]:
weather_merge = weather.copy()

In [21]:
weather_merge["date"] = pd.to_datetime(
    weather_merge["date"]
)

In [22]:
print(weather_merge["date"].dtype)

datetime64[ns]

In [23]:
weather_merge["hour"] = pd.to_numeric(
    weather_merge["hour"],
    errors="coerce"
)

In [24]:
weather_merge[
    [
        "airport_code",
        "date",
        "hour",
        "temperature",
        "precipitation",
        "wind_speed",
        "weather_code"
    ]
].head(10)

,airport_code,date,hour,temperature,precipitation,wind_speed,weather_code
0,PPG,2026-01-01,0,29.4,0.0,10.1,3
1,PPG,2026-01-01,1,29.3,0.1,9.9,51
2,PPG,2026-01-01,2,26.5,0.2,21.1,51
3,PPG,2026-01-01,3,27.6,0.0,10.3,3
4,PPG,2026-01-01,4,28.1,0.0,8.6,3
5,PPG,2026-01-01,5,28.1,0.0,9.4,3
6,PPG,2026-01-01,6,28.2,0.0,9.4,3
7,PPG,2026-01-01,7,28.2,0.0,9.0,2
8,PPG,2026-01-01,8,28.2,0.0,8.0,3
9,PPG,2026-01-01,9,28.2,0.0,8.0,3

In [25]:
duplicate_weather = weather_merge.duplicated(
    subset=["airport_code", "date", "hour"]
)

print("Duplicate weather keys:", duplicate_weather.sum())

Duplicate weather keys: 0

In [26]:
print(
    "Minimum hour:",
    weather_merge["hour"].min()
)

print(
    "Maximum hour:",
    weather_merge["hour"].max()
)

Minimum hour: 0
Maximum hour: 23

In [27]:
print(
    "Unique weather airports:",
    weather_merge["airport_code"].nunique()
)

Unique weather airports: 362

In [28]:
print("Duplicate weather keys:", duplicate_weather.sum())

print("Weather hour range:",
      weather_merge["hour"].min(),
      "to",
      weather_merge["hour"].max())

print("Unique weather airports:",
      weather_merge["airport_code"].nunique())

Duplicate weather keys: 0
Weather hour range: 0 to 23
Unique weather airports: 362

In [29]:
flights_enriched = flights_weather.merge(
    weather_merge,
    left_on=["origin", "fl_date", "departure_hour"],
    right_on=["airport_code", "date", "hour"],
    how="left"
)

In [30]:
print("Flights before merge:", len(flights_weather))

Flights before merge: 1847242

In [31]:
print("Flights after merge:", len(flights_enriched))

Flights after merge: 1847242

In [32]:
flights_enriched["weather_matched"] = (
    flights_enriched["temperature"].notna()
)

In [33]:
print(
    flights_enriched["weather_matched"].value_counts()
)

weather_matched
True    1847242
Name: count, dtype: int64

In [34]:
weather_match_percentage = (
    flights_enriched["weather_matched"].mean() * 100
)

print(
    f"Weather match percentage: {weather_match_percentage:.2f}%"
)

Weather match percentage: 100.00%

In [35]:
missing_weather = flights_enriched[
    flights_enriched["weather_matched"] == False
]

print("Flights without weather:", len(missing_weather))

Flights without weather: 0

In [36]:
missing_weather[
    ["fl_date", "origin", "crs_dep_time", "departure_hour"]
].head(20)

Empty DataFrame
Columns: [fl_date, origin, crs_dep_time, departure_hour]
Index: []

In [37]:
print(flights_enriched.columns.tolist())

['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id', 'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay', 'flight_status', 'dep_time_at_cancellation', 'missing_operational_duration', 'extreme_dep_delay', 'extreme_arr_delay', 'is_cancelled', 'is_diverted', 'is_irregular_operation', 'is_departure_delayed', 'is_arrival_delayed', 'severe_departure_delay', 'severe_arrival_delay', 'origin_airport_name', 'origin_city', 'origin_country', 'origin_latitude', 'origin_longitude', 'origin_timezone', 'dest_airport_name', 'dest_city', 'dest_country', 'dest_latitude', 'dest_longitude', 'dest_timezone', 'dep_hour', 'dep_minute', 'scheduled_departure', 'departure_hour', 'airport_code', 'date', 'hour', 'temperature', 'precipitation', 'wind_speed', 'weather_code', 'weather_matched']

In [38]:
flights_enriched[
    [
        "fl_date",
        "origin",
        "crs_dep_time",
        "departure_hour",
        "temperature",
        "precipitation",
        "wind_speed",
        "weather_code"
    ]
].head(10)

,fl_date,origin,crs_dep_time,departure_hour,temperature,precipitation,wind_speed,weather_code
0,2026-01-01,JFK,700,7,0.9,0.0,18.3,3
1,2026-01-01,LAX,2130,21,17.3,0.2,4.5,51
2,2026-01-01,MIA,2245,22,18.2,0.0,7.9,0
3,2026-01-01,DEN,2338,23,12.5,0.0,4.8,2
4,2026-01-01,BOS,757,7,-2.4,0.1,16.7,71
5,2026-01-01,SFO,2359,23,14.8,0.0,10.9,3
6,2026-01-01,MIA,1926,19,18.9,0.0,10.1,0
7,2026-01-01,DFW,1910,19,19.3,0.0,8.9,3
8,2026-01-01,DFW,1646,16,11.5,0.0,6.8,3
9,2026-01-01,DFW,2105,21,21.0,0.0,11.0,3

In [39]:
print("Flights before merge:", len(flights_weather))
print("Flights after merge:", len(flights_enriched))

print(
    f"Weather match percentage: {weather_match_percentage:.2f}%"
)

print(
    "Flights without weather:",
    len(missing_weather)
)

Flights before merge: 1847242
Flights after merge: 1847242
Weather match percentage: 100.00%
Flights without weather: 0

In [40]:
missing_weather = flights_enriched[
    flights_enriched["weather_matched"] == False
]

In [41]:
missing_weather["origin"].value_counts().head(20)

Series([], Name: count, dtype: int64)

In [42]:
missing_weather["fl_date"].value_counts().head(20)

Series([], Name: count, dtype: int64)

In [43]:
missing_airports = missing_weather["origin"].unique()

print("Airports without weather:")
print(missing_airports)

Airports without weather:
[]

In [44]:
weather_airports = weather_merge["airport_code"].unique()

unavailable_airports = [
    airport
    for airport in missing_airports
    if airport not in weather_airports
]

print("Airports not available in weather data:")
print(unavailable_airports)

Airports not available in weather data:
[]

In [45]:
print(
    "Total flights without weather:",
    len(missing_weather)
)

Total flights without weather: 0

In [46]:
print(
    "Percentage without weather:",
    len(missing_weather) / len(flights_enriched) * 100
)

Percentage without weather: 0.0

In [47]:
print("Flights without weather:", len(missing_weather))

print(
    "Percentage without weather:",
    len(missing_weather) / len(flights_enriched) * 100
)

print("Airports without weather:")
print(missing_airports)

print("Airports not available in weather data:")
print(unavailable_airports)

Flights without weather: 0
Percentage without weather: 0.0
Airports without weather:
[]
Airports not available in weather data:
[]

In [48]:
print("Flights before merge:", len(flights_weather))
print("Flights after merge:", len(flights_enriched))

if len(flights_weather) == len(flights_enriched):
    print("PASS: Flight row count is unchanged.")
else:
    print("WARNING: Flight row count changed.")

Flights before merge: 1847242
Flights after merge: 1847242
PASS: Flight row count is unchanged.

In [49]:
print(flights_enriched.columns.tolist())

['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id', 'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay', 'flight_status', 'dep_time_at_cancellation', 'missing_operational_duration', 'extreme_dep_delay', 'extreme_arr_delay', 'is_cancelled', 'is_diverted', 'is_irregular_operation', 'is_departure_delayed', 'is_arrival_delayed', 'severe_departure_delay', 'severe_arrival_delay', 'origin_airport_name', 'origin_city', 'origin_country', 'origin_latitude', 'origin_longitude', 'origin_timezone', 'dest_airport_name', 'dest_city', 'dest_country', 'dest_latitude', 'dest_longitude', 'dest_timezone', 'dep_hour', 'dep_minute', 'scheduled_departure', 'departure_hour', 'airport_code', 'date', 'hour', 'temperature', 'precipitation', 'wind_speed', 'weather_code', 'weather_matched']

In [50]:
print(flights_weather.columns.tolist())

['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id', 'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay', 'flight_status', 'dep_time_at_cancellation', 'missing_operational_duration', 'extreme_dep_delay', 'extreme_arr_delay', 'is_cancelled', 'is_diverted', 'is_irregular_operation', 'is_departure_delayed', 'is_arrival_delayed', 'severe_departure_delay', 'severe_arrival_delay', 'origin_airport_name', 'origin_city', 'origin_country', 'origin_latitude', 'origin_longitude', 'origin_timezone', 'dest_airport_name', 'dest_city', 'dest_country', 'dest_latitude', 'dest_longitude', 'dest_timezone', 'dep_hour', 'dep_minute', 'scheduled_departure', 'departure_hour']

In [51]:
duplicate_flights = flights_enriched.duplicated(
    subset=[
        "fl_date",
        "origin",
        "crs_dep_time"
    ]
)

print("Duplicate flight records:", duplicate_flights.sum())

Duplicate flight records: 593203

In [52]:
print(flights_enriched.columns.tolist())

['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id', 'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay', 'flight_status', 'dep_time_at_cancellation', 'missing_operational_duration', 'extreme_dep_delay', 'extreme_arr_delay', 'is_cancelled', 'is_diverted', 'is_irregular_operation', 'is_departure_delayed', 'is_arrival_delayed', 'severe_departure_delay', 'severe_arrival_delay', 'origin_airport_name', 'origin_city', 'origin_country', 'origin_latitude', 'origin_longitude', 'origin_timezone', 'dest_airport_name', 'dest_city', 'dest_country', 'dest_latitude', 'dest_longitude', 'dest_timezone', 'dep_hour', 'dep_minute', 'scheduled_departure', 'departure_hour', 'airport_code', 'date', 'hour', 'temperature', 'precipitation', 'wind_speed', 'weather_code', 'weather_matched']

In [53]:
duplicate_flights = flights_enriched.duplicated(
    subset=[
        "fl_date",
        "mkt_carrier",
        "mkt_carrier_fl_num",
        "origin",
        "dest"
    ]
)

print("Duplicate flight records:", duplicate_flights.sum())

Duplicate flight records: 0

In [54]:
print("Flights before merge:", len(flights_weather))
print("Flights after merge:", len(flights_enriched))

print("Duplicate flight records:", duplicate_flights.sum())

print(
    "Weather matched:",
    flights_enriched["weather_matched"].sum()
)

print(
    "Weather missing:",
    (~flights_enriched["weather_matched"]).sum()
)

Flights before merge: 1847242
Flights after merge: 1847242
Duplicate flight records: 0
Weather matched: 1847242
Weather missing: 0

In [55]:
weather_match_percentage = (
    flights_enriched["weather_matched"].mean() * 100
)

print(
    f"Weather match percentage: {weather_match_percentage:.2f}%"
)

Weather match percentage: 100.00%

In [56]:
flights_enriched = flights_enriched.drop(
    columns=["airport_code", "date", "hour"]
)

In [57]:
print(flights_enriched.columns.tolist())

['year', 'quarter', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'mkt_unique_carrier', 'branded_code_share', 'mkt_carrier_airline_id', 'mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_abr', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_abr', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'dep_delay_new', 'dep_del15', 'taxi_out', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'arr_delay_new', 'arr_del15', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay', 'flight_status', 'dep_time_at_cancellation', 'missing_operational_duration', 'extreme_dep_delay', 'extreme_arr_delay', 'is_cancelled', 'is_diverted', 'is_irregular_operation', 'is_departure_delayed', 'is_arrival_delayed', 'severe_departure_delay', 'severe_arrival_delay', 'origin_airport_name', 'origin_city', 'origin_country', 'origin_latitude', 'origin_longitude', 'origin_timezone', 'dest_airport_name', 'dest_city', 'dest_country', 'dest_latitude', 'dest_longitude', 'dest_timezone', 'dep_hour', 'dep_minute', 'scheduled_departure', 'departure_hour', 'temperature', 'precipitation', 'wind_speed', 'weather_code', 'weather_matched']

In [58]:
flights_enriched[
    [
        "fl_date",
        "origin",
        "dest",
        "crs_dep_time",
        "departure_hour",
        "temperature",
        "precipitation",
        "wind_speed",
        "weather_code",
        "weather_matched"
    ]
].head(10)

,fl_date,origin,dest,crs_dep_time,departure_hour,temperature,precipitation,wind_speed,weather_code,weather_matched
0,2026-01-01,JFK,LAX,700,7,0.9,0.0,18.3,3,True
1,2026-01-01,LAX,JFK,2130,21,17.3,0.2,4.5,51,True
2,2026-01-01,MIA,MSY,2245,22,18.2,0.0,7.9,0,True
3,2026-01-01,DEN,MIA,2338,23,12.5,0.0,4.8,2,True
4,2026-01-01,BOS,CLT,757,7,-2.4,0.1,16.7,71,True
5,2026-01-01,SFO,DFW,2359,23,14.8,0.0,10.9,3,True
6,2026-01-01,MIA,ATL,1926,19,18.9,0.0,10.1,0,True
7,2026-01-01,DFW,MSY,1910,19,19.3,0.0,8.9,3,True
8,2026-01-01,DFW,MCO,1646,16,11.5,0.0,6.8,3,True
9,2026-01-01,DFW,STL,2105,21,21.0,0.0,11.0,3,True

In [59]:
output_path = (
    r"D:\Data Analyst\EXCEL\airline-operations-intelligence"
    r"\Airline-Operations-Intelligence\data\processed"
    r"\flights_2026_q1.csv"
)

flights_enriched.to_csv(
    output_path,
    index=False
)

print("Final dataset saved successfully.")
print(output_path)

Final dataset saved successfully.
D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv

In [60]:
flights_enriched['weather_code']

0           3
1          51
2           0
3           2
4          71
           ..
1847237     3
1847238     3
1847239     1
1847240    53
1847241     3
Name: weather_code, Length: 1847242, dtype: int64

In [61]:
def get_weather_category(code):

    if code == 0:
        return "Clear"

    elif code in [1, 2, 3]:
        return "Cloudy"

    elif code in [51, 53, 55, 56, 57, 61, 63, 65, 66, 67, 80, 81, 82]:
        return "Rain"

    elif code in [71, 73, 75, 77, 85, 86]:
        return "Snow"

    elif code in [95, 96, 99]:
        return "Storm"

    else:
        return "Unknown"

In [62]:
flights_enriched["weather_category"] = (
    flights_enriched["weather_code"].apply(get_weather_category)
)

In [63]:
print(
    flights_enriched["weather_category"].value_counts()
)

weather_category
Cloudy    997585
Clear     627886
Rain      165645
Snow       56126
Name: count, dtype: int64

In [64]:
flights_enriched[
    ["weather_code", "weather_category"]
].drop_duplicates().sort_values("weather_code")

      weather_code weather_category
2                0            Clear
10               1           Cloudy
3                2           Cloudy
0                3           Cloudy
1               51             Rain
147             53             Rain
460             55             Rain
13              61             Rain
92              63             Rain
1578            65             Rain
4               71             Snow
162             73             Snow
780             75             Snow

In [65]:
flights_enriched[
    ["weather_code", "weather_category"]
].drop_duplicates().sort_values("weather_code")

      weather_code weather_category
2                0            Clear
10               1           Cloudy
3                2           Cloudy
0                3           Cloudy
1               51             Rain
147             53             Rain
460             55             Rain
13              61             Rain
92              63             Rain
1578            65             Rain
4               71             Snow
162             73             Snow
780             75             Snow

In [66]:
flights_enriched["bad_weather"] = (
    flights_enriched["weather_category"].isin(
        ["Rain", "Snow", "Storm"]
    )
).astype(int)

In [67]:
print(flights_enriched["bad_weather"].value_counts())

bad_weather
0    1625471
1     221771
Name: count, dtype: int64

bad_weather = 0 → No bad weather
bad_weather = 1 → Bad weather

In [68]:
print(
    flights_enriched["bad_weather"]
    .value_counts(normalize=True)
    .mul(100)
)

bad_weather
0    87.99448
1    12.00552
Name: proportion, dtype: float64

In [69]:
print(
    flights_enriched[
        [
            "weather_code",
            "weather_category",
            "bad_weather"
        ]
    ].head(10)
)

   weather_code weather_category  bad_weather
0             3           Cloudy            0
1            51             Rain            1
2             0            Clear            0
3             2           Cloudy            0
4            71             Snow            1
5             3           Cloudy            0
6             0            Clear            0
7             3           Cloudy            0
8             3           Cloudy            0
9             3           Cloudy            0

In [70]:
weather_columns = [
    "temperature",
    "precipitation",
    "wind_speed",
    "weather_code",
    "weather_category",
    "bad_weather"
]

print(
    flights_enriched[weather_columns].isna().sum()
)

temperature         0
precipitation       0
wind_speed          0
weather_code        0
weather_category    0
bad_weather         0
dtype: int64

In [71]:
output_path = (
    r"D:\Data Analyst\EXCEL\airline-operations-intelligence"
    r"\Airline-Operations-Intelligence\data\processed"
    r"\flights_2026_q1.csv"
)

flights_enriched.to_csv(
    output_path,
    index=False
)

print("Final enriched dataset saved successfully:")
print(output_path)

Final enriched dataset saved successfully:
D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1.csv

In [73]:
print("Rows:", len(flights_enriched))

print(
    "Weather matched:",
    flights_enriched["weather_matched"].sum()
)

print(
    "Weather missing:",
    (~flights_enriched["weather_matched"]).sum()
)

print(
    "Duplicate flights:",
    flights_enriched.duplicated(
        subset=[
            "fl_date",
            "mkt_carrier",
            "mkt_carrier_fl_num",
            "origin",
            "dest"
        ]
    ).sum()
)

Rows: 1847242
Weather matched: 1847242
Weather missing: 0
Duplicate flights: 0

In [78]:
sample_data=flights_enriched.sample(100000)
sample_data

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,dep_minute,scheduled_departure,departure_hour,temperature,precipitation,wind_speed,weather_code,weather_matched,weather_category,bad_weather
500510,2026,1,1,26,1,2026-01-26,DL,DL_CODESHARE,19790,DL,...,45,2026-01-26 08:45:00,8,-5.3,0.0,11.9,3,True,Cloudy,0
678685,2026,1,2,4,3,2026-02-04,WN,WN,19393,WN,...,55,2026-02-04 17:55:00,17,-4.8,0.0,5.9,0,True,Clear,0
1397200,2026,1,3,11,3,2026-03-11,DL,DL_CODESHARE,19790,DL,...,19,2026-03-11 20:19:00,20,19.6,0.0,13.1,3,True,Cloudy,0
1787037,2026,1,3,29,7,2026-03-29,AS,AS,19930,AS,...,0,2026-03-29 07:00:00,7,6.4,0.0,5.8,0,True,Clear,0
125170,2026,1,1,7,3,2026-01-07,AA,AA,19805,AA,...,35,2026-01-07 17:35:00,17,12.8,0.0,6.0,3,True,Cloudy,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150430,2026,1,1,8,4,2026-01-08,DL,DL,19790,DL,...,11,2026-01-08 05:11:00,5,3.6,0.0,9.9,1,True,Cloudy,0
767892,2026,1,2,9,1,2026-02-09,DL,DL,19790,DL,...,10,2026-02-09 19:10:00,19,-5.6,0.0,10.7,0,True,Clear,0
735580,2026,1,2,7,6,2026-02-07,UA,UA_CODESHARE,19977,UA,...,23,2026-02-07 13:23:00,13,10.1,0.0,2.9,3,True,Cloudy,0
1247905,2026,1,3,4,3,2026-03-04,UA,UA,19977,UA,...,35,2026-03-04 12:35:00,12,0.2,0.0,11.5,0,True,Clear,0
693673,2026,1,2,5,4,2026-02-05,UA,UA,19977,UA,...,33,2026-02-05 08:33:00,8,16.1,0.0,8.6,0,True,Clear,0

In [79]:
sample_data.to_csv(r"D:\Data Analyst\EXCEL\airline-operations-intelligence\Airline-Operations-Intelligence\data\processed\flights_2026_q1_sample.csv")