In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"D:\Data Analyst\EXCEL\api\processed\flights_2026_q1.csv")

In [5]:
df_raw = df.copy()

In [6]:
df.shape

(1847242, 43)

In [7]:
df.head()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
0,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,381.0,427.0,349.0,2475.0,0.0,0.0,43.0,0.0,0.0
1,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,321.0,292.0,270.0,2475.0,NaN,NaN,NaN,NaN,NaN
2,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,134.0,124.0,105.0,674.0,NaN,NaN,NaN,NaN,NaN
3,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,229.0,210.0,191.0,1709.0,NaN,NaN,NaN,NaN,NaN
4,2026,1,1,1,4,2026-01-01,AA,AA,19805,AA,...,0.0,153.0,147.0,117.0,728.0,NaN,NaN,NaN,NaN,NaN

In [8]:
df.tail()

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
1847237,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,80.0,85.0,54.0,402.0,0.0,0.0,5.0,0.0,16.0
1847238,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,140.0,143.0,126.0,1020.0,NaN,NaN,NaN,NaN,NaN
1847239,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,145.0,141.0,125.0,930.0,NaN,NaN,NaN,NaN,NaN
1847240,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,95.0,102.0,85.0,395.0,NaN,NaN,NaN,NaN,NaN
1847241,2026,1,3,31,2,2026-03-31,WN,WN,19393,WN,...,0.0,130.0,118.0,100.0,794.0,NaN,NaN,NaN,NaN,NaN

In [9]:
df.sample(5, random_state=42)

,YEAR,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,MKT_UNIQUE_CARRIER,BRANDED_CODE_SHARE,MKT_CARRIER_AIRLINE_ID,MKT_CARRIER,...,DIVERTED,CRS_ELAPSED_TIME,ACTUAL_ELAPSED_TIME,AIR_TIME,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY
454974,2026,1,1,24,6,2026-01-24,AA,AA_CODESHARE,19805,AA,...,0.0,86.0,NaN,NaN,383.0,NaN,NaN,NaN,NaN,NaN
1660385,2026,1,3,23,1,2026-03-23,DL,DL_CODESHARE,19790,DL,...,0.0,75.0,77.0,38.0,224.0,NaN,NaN,NaN,NaN,NaN
1816002,2026,1,3,30,1,2026-03-30,DL,DL_CODESHARE,19790,DL,...,0.0,117.0,NaN,NaN,479.0,NaN,NaN,NaN,NaN,NaN
417415,2026,1,1,22,4,2026-01-22,AS,AS_CODESHARE,19930,AS,...,0.0,130.0,131.0,106.0,605.0,NaN,NaN,NaN,NaN,NaN
173252,2026,1,1,9,5,2026-01-09,DL,DL_CODESHARE,19790,DL,...,0.0,105.0,123.0,63.0,390.0,NaN,NaN,NaN,NaN,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1847242 entries, 0 to 1847241
Data columns (total 43 columns):
 #   Column                  Dtype
---  ------                  -----
 0   YEAR                    int64
 1   QUARTER                 int64
 2   MONTH                   int64
 3   DAY_OF_MONTH            int64
 4   DAY_OF_WEEK             int64
 5   FL_DATE                 object
 6   MKT_UNIQUE_CARRIER      object
 7   BRANDED_CODE_SHARE      object
 8   MKT_CARRIER_AIRLINE_ID  int64
 9   MKT_CARRIER             object
 10  MKT_CARRIER_FL_NUM      int64
 11  ORIGIN                  object
 12  ORIGIN_CITY_NAME        object
 13  ORIGIN_STATE_ABR        object
 14  ORIGIN_STATE_NM         object
 15  DEST                    object
 16  DEST_CITY_NAME          object
 17  DEST_STATE_ABR          object
 18  DEST_STATE_NM           object
 19  CRS_DEP_TIME            int64
 20  DEP_TIME                float64
 21  DEP_DELAY               float64
 22  DEP_DELAY_NEW           float64
 23  DEP_DEL15               float64
 24  TAXI_OUT                float64
 25  TAXI_IN                 float64
 26  CRS_ARR_TIME            int64
 27  ARR_TIME                float64
 28  ARR_DELAY               float64
 29  ARR_DELAY_NEW           float64
 30  ARR_DEL15               float64
 31  CANCELLED               float64
 32  CANCELLATION_CODE       object
 33  DIVERTED                float64
 34  CRS_ELAPSED_TIME        float64
 35  ACTUAL_ELAPSED_TIME     float64
 36  AIR_TIME                float64
 37  DISTANCE                float64
 38  CARRIER_DELAY           float64
 39  WEATHER_DELAY           float64
 40  NAS_DELAY               float64
 41  SECURITY_DELAY          float64
 42  LATE_AIRCRAFT_DELAY     float64
dtypes: float64(21), int64(9), object(13)
memory usage: 606.0+ MB

In [11]:
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
YEAR,1847242.0,NaN,NaN,NaN,2026.0,0.0,2026.0,2026.0,2026.0,2026.0,2026.0
QUARTER,1847242.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
MONTH,1847242.0,NaN,NaN,NaN,2.039273,0.830991,1.0,1.0,2.0,3.0,3.0
DAY_OF_MONTH,1847242.0,NaN,NaN,NaN,15.569698,8.701216,1.0,8.0,16.0,23.0,31.0
DAY_OF_WEEK,1847242.0,NaN,NaN,NaN,4.018039,2.017735,1.0,2.0,4.0,6.0,7.0
FL_DATE,1847242,90,2026-03-26,22912,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MKT_UNIQUE_CARRIER,1847242,9,AA,483902,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BRANDED_CODE_SHARE,1847242,13,WN,327083,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MKT_CARRIER_AIRLINE_ID,1847242.0,NaN,NaN,NaN,19827.496986,266.707311,19393.0,19790.0,19805.0,19977.0,20436.0
MKT_CARRIER,1847242,9,AA,483902,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MKT_CARRIER_FL_NUM,1847242.0,NaN,NaN,NaN,2764.304239,1724.520983,1.0,1332.0,2452.0,4145.0,9914.0
ORIGIN,1847242,362,ORD,88327,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGIN_CITY_NAME,1847242,356,"Chicago, IL",104475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGIN_STATE_ABR,1847242,52,TX,191545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ORIGIN_STATE_NM,1847242,52,Texas,191545,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEST,1847242,362,ORD,88307,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEST_CITY_NAME,1847242,356,"Chicago, IL",104466,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEST_STATE_ABR,1847242,52,TX,191533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DEST_STATE_NM,1847242,52,Texas,191533,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CRS_DEP_TIME,1847242.0,NaN,NaN,NaN,1322.166387,485.142064,1.0,908.0,1315.0,1730.0,2359.0
DEP_TIME,1786458.0,NaN,NaN,NaN,1329.817735,501.122881,1.0,913.0,1325.0,1739.0,2400.0
DEP_DELAY,1786268.0,NaN,NaN,NaN,13.938069,61.113006,-66.0,-7.0,-2.0,10.0,3339.0
DEP_DELAY_NEW,1786268.0,NaN,NaN,NaN,17.586258,59.914301,0.0,0.0,0.0,10.0,3339.0
DEP_DEL15,1786268.0,NaN,NaN,NaN,0.218248,0.413057,0.0,0.0,0.0,0.0,1.0
TAXI_OUT,1785251.0,NaN,NaN,NaN,19.20085,11.130109,1.0,13.0,16.0,22.0,224.0
TAXI_IN,1784292.0,NaN,NaN,NaN,8.786492,7.780903,1.0,5.0,7.0,10.0,341.0
CRS_ARR_TIME,1847242.0,NaN,NaN,NaN,1504.609117,506.232615,1.0,1115.0,1524.0,1929.0,2359.0
ARR_TIME,1784292.0,NaN,NaN,NaN,1474.002672,534.159829,1.0,1058.0,1511.0,1920.0,2400.0
ARR_DELAY,1780194.0,NaN,NaN,NaN,7.249089,63.468663,-90.0,-18.0,-7.0,10.0,3339.0
ARR_DELAY_NEW,1780194.0,NaN,NaN,NaN,17.345602,59.63412,0.0,0.0,0.0,10.0,3339.0
ARR_DEL15,1780194.0,NaN,NaN,NaN,0.215946,0.411477,0.0,0.0,0.0,0.0,1.0
CANCELLED,1847242.0,NaN,NaN,NaN,0.033732,0.180538,0.0,0.0,0.0,0.0,1.0
CANCELLATION_CODE,62311,4,B,47348,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DIVERTED,1847242.0,NaN,NaN,NaN,0.002564,0.050575,0.0,0.0,0.0,0.0,1.0
CRS_ELAPSED_TIME,1847241.0,NaN,NaN,NaN,148.070241,72.255269,-85.0,95.0,131.0,180.0,1202.0
ACTUAL_ELAPSED_TIME,1780185.0,NaN,NaN,NaN,141.567923,72.431443,14.0,89.0,125.0,173.0,763.0
AIR_TIME,1780185.0,NaN,NaN,NaN,113.598469,70.744396,6.0,62.0,97.0,144.0,719.0
DISTANCE,1847242.0,NaN,NaN,NaN,808.080003,589.653629,31.0,373.0,657.0,1050.0,4983.0
CARRIER_DELAY,384426.0,NaN,NaN,NaN,26.771269,82.0748,0.0,0.0,3.0,23.0,3339.0
WEATHER_DELAY,384426.0,NaN,NaN,NaN,5.31726,41.409899,0.0,0.0,0.0,0.0,1958.0
NAS_DELAY,384426.0,NaN,NaN,NaN,14.499233,34.940501,0.0,0.0,0.0,18.0,1560.0
SECURITY_DELAY,384426.0,NaN,NaN,NaN,0.130366,4.280014,0.0,0.0,0.0,0.0,1600.0
LATE_AIRCRAFT_DELAY,384426.0,NaN,NaN,NaN,29.269703,64.896116,0.0,0.0,0.0,33.0,2338.0

In [12]:
df.columns.tolist()

['YEAR',
 'QUARTER',
 'MONTH',
 'DAY_OF_MONTH',
 'DAY_OF_WEEK',
 'FL_DATE',
 'MKT_UNIQUE_CARRIER',
 'BRANDED_CODE_SHARE',
 'MKT_CARRIER_AIRLINE_ID',
 'MKT_CARRIER',
 'MKT_CARRIER_FL_NUM',
 'ORIGIN',
 'ORIGIN_CITY_NAME',
 'ORIGIN_STATE_ABR',
 'ORIGIN_STATE_NM',
 'DEST',
 'DEST_CITY_NAME',
 'DEST_STATE_ABR',
 'DEST_STATE_NM',
 'CRS_DEP_TIME',
 'DEP_TIME',
 'DEP_DELAY',
 'DEP_DELAY_NEW',
 'DEP_DEL15',
 'TAXI_OUT',
 'TAXI_IN',
 'CRS_ARR_TIME',
 'ARR_TIME',
 'ARR_DELAY',
 'ARR_DELAY_NEW',
 'ARR_DEL15',
 'CANCELLED',
 'CANCELLATION_CODE',
 'DIVERTED',
 'CRS_ELAPSED_TIME',
 'ACTUAL_ELAPSED_TIME',
 'AIR_TIME',
 'DISTANCE',
 'CARRIER_DELAY',
 'WEATHER_DELAY',
 'NAS_DELAY',
 'SECURITY_DELAY',
 'LATE_AIRCRAFT_DELAY']

In [13]:
# ============================================================
# 3. STANDARDIZE COLUMN NAMES
# ============================================================

df.columns = (
    df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_", regex=False)
)

df.columns.tolist()

['year',
 'quarter',
 'month',
 'day_of_month',
 'day_of_week',
 'fl_date',
 'mkt_unique_carrier',
 'branded_code_share',
 'mkt_carrier_airline_id',
 'mkt_carrier',
 'mkt_carrier_fl_num',
 'origin',
 'origin_city_name',
 'origin_state_abr',
 'origin_state_nm',
 'dest',
 'dest_city_name',
 'dest_state_abr',
 'dest_state_nm',
 'crs_dep_time',
 'dep_time',
 'dep_delay',
 'dep_delay_new',
 'dep_del15',
 'taxi_out',
 'taxi_in',
 'crs_arr_time',
 'arr_time',
 'arr_delay',
 'arr_delay_new',
 'arr_del15',
 'cancelled',
 'cancellation_code',
 'diverted',
 'crs_elapsed_time',
 'actual_elapsed_time',
 'air_time',
 'distance',
 'carrier_delay',
 'weather_delay',
 'nas_delay',
 'security_delay',
 'late_aircraft_delay']

In [14]:
len(df.columns)

43

In [15]:
df.dtypes

year                        int64
quarter                     int64
month                       int64
day_of_month                int64
day_of_week                 int64
fl_date                    object
mkt_unique_carrier         object
branded_code_share         object
mkt_carrier_airline_id      int64
mkt_carrier                object
mkt_carrier_fl_num          int64
origin                     object
origin_city_name           object
origin_state_abr           object
origin_state_nm            object
dest                       object
dest_city_name             object
dest_state_abr             object
dest_state_nm              object
crs_dep_time                int64
dep_time                  float64
dep_delay                 float64
dep_delay_new             float64
dep_del15                 float64
taxi_out                  float64
taxi_in                   float64
crs_arr_time                int64
arr_time                  float64
arr_delay                 float64
arr_delay_new             float64
arr_del15                 float64
cancelled                 float64
cancellation_code          object
diverted                  float64
crs_elapsed_time          float64
actual_elapsed_time       float64
air_time                  float64
distance                  float64
carrier_delay             float64
weather_delay             float64
nas_delay                 float64
security_delay            float64
late_aircraft_delay       float64
dtype: object

In [16]:
df.dtypes.value_counts()

float64    21
object     13
int64       9
Name: count, dtype: int64

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df[df.duplicated()].head()

Empty DataFrame
Columns: [year, quarter, month, day_of_month, day_of_week, fl_date, mkt_unique_carrier, branded_code_share, mkt_carrier_airline_id, mkt_carrier, mkt_carrier_fl_num, origin, origin_city_name, origin_state_abr, origin_state_nm, dest, dest_city_name, dest_state_abr, dest_state_nm, crs_dep_time, dep_time, dep_delay, dep_delay_new, dep_del15, taxi_out, taxi_in, crs_arr_time, arr_time, arr_delay, arr_delay_new, arr_del15, cancelled, cancellation_code, diverted, crs_elapsed_time, actual_elapsed_time, air_time, distance, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 43 columns]

In [19]:
df["cancelled"].value_counts(dropna=False)

cancelled
0.0    1784931
1.0      62311
Name: count, dtype: int64

In [20]:
df["diverted"].value_counts(dropna=False)

diverted
0.0    1842505
1.0       4737
Name: count, dtype: int64

In [21]:
df["cancellation_code"].value_counts(dropna=False)

cancellation_code
NaN    1784931
B        47348
A        10042
C         4852
D           69
Name: count, dtype: int64

In [22]:
quality_report = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_count": df.isna().sum().values,
    "missing_percent": (
        df.isna().mean().values * 100
    ),
    "unique_count": df.nunique(dropna=False).values
})

quality_report

,column,dtype,missing_count,missing_percent,unique_count
0,year,int64,0,0.000000,1
1,quarter,int64,0,0.000000,1
2,month,int64,0,0.000000,3
3,day_of_month,int64,0,0.000000,31
4,day_of_week,int64,0,0.000000,7
5,fl_date,object,0,0.000000,90
6,mkt_unique_carrier,object,0,0.000000,9
7,branded_code_share,object,0,0.000000,13
8,mkt_carrier_airline_id,int64,0,0.000000,9
9,mkt_carrier,object,0,0.000000,9
10,mkt_carrier_fl_num,int64,0,0.000000,6582
11,origin,object,0,0.000000,362
12,origin_city_name,object,0,0.000000,356
13,origin_state_abr,object,0,0.000000,52
14,origin_state_nm,object,0,0.000000,52
15,dest,object,0,0.000000,362
16,dest_city_name,object,0,0.000000,356
17,dest_state_abr,object,0,0.000000,52
18,dest_state_nm,object,0,0.000000,52
19,crs_dep_time,int64,0,0.000000,1266
20,dep_time,float64,60784,3.290527,1437
21,dep_delay,float64,60974,3.300813,1582
22,dep_delay_new,float64,60974,3.300813,1526
23,dep_del15,float64,60974,3.300813,3
24,taxi_out,float64,61991,3.355868,185
25,taxi_in,float64,62950,3.407783,242
26,crs_arr_time,int64,0,0.000000,1364
27,arr_time,float64,62950,3.407783,1441
28,arr_delay,float64,67048,3.629627,1623
29,arr_delay_new,float64,67048,3.629627,1536
30,arr_del15,float64,67048,3.629627,3
31,cancelled,float64,0,0.000000,2
32,cancellation_code,object,1784931,96.626809,5
33,diverted,float64,0,0.000000,2
34,crs_elapsed_time,float64,1,0.000054,522
35,actual_elapsed_time,float64,67057,3.630115,707
36,air_time,float64,67057,3.630115,670
37,distance,float64,0,0.000000,1567
38,carrier_delay,float64,1462816,79.189191,1322
39,weather_delay,float64,1462816,79.189191,883
40,nas_delay,float64,1462816,79.189191,617
41,security_delay,float64,1462816,79.189191,147
42,late_aircraft_delay,float64,1462816,79.189191,1003

In [23]:
quality_report.sort_values(
    "missing_percent",
    ascending=False
)

,column,dtype,missing_count,missing_percent,unique_count
32,cancellation_code,object,1784931,96.626809,5
42,late_aircraft_delay,float64,1462816,79.189191,1003
38,carrier_delay,float64,1462816,79.189191,1322
41,security_delay,float64,1462816,79.189191,147
40,nas_delay,float64,1462816,79.189191,617
39,weather_delay,float64,1462816,79.189191,883
36,air_time,float64,67057,3.630115,670
35,actual_elapsed_time,float64,67057,3.630115,707
29,arr_delay_new,float64,67048,3.629627,1536
28,arr_delay,float64,67048,3.629627,1623
30,arr_del15,float64,67048,3.629627,3
27,arr_time,float64,62950,3.407783,1441
25,taxi_in,float64,62950,3.407783,242
24,taxi_out,float64,61991,3.355868,185
21,dep_delay,float64,60974,3.300813,1582
23,dep_del15,float64,60974,3.300813,3
22,dep_delay_new,float64,60974,3.300813,1526
20,dep_time,float64,60784,3.290527,1437
34,crs_elapsed_time,float64,1,0.000054,522
2,month,int64,0,0.000000,3
1,quarter,int64,0,0.000000,1
0,year,int64,0,0.000000,1
7,branded_code_share,object,0,0.000000,13
6,mkt_unique_carrier,object,0,0.000000,9
5,fl_date,object,0,0.000000,90
4,day_of_week,int64,0,0.000000,7
3,day_of_month,int64,0,0.000000,31
10,mkt_carrier_fl_num,int64,0,0.000000,6582
9,mkt_carrier,object,0,0.000000,9
8,mkt_carrier_airline_id,int64,0,0.000000,9
19,crs_dep_time,int64,0,0.000000,1266
26,crs_arr_time,int64,0,0.000000,1364
16,dest_city_name,object,0,0.000000,356
17,dest_state_abr,object,0,0.000000,52
18,dest_state_nm,object,0,0.000000,52
12,origin_city_name,object,0,0.000000,356
11,origin,object,0,0.000000,362
13,origin_state_abr,object,0,0.000000,52
14,origin_state_nm,object,0,0.000000,52
15,dest,object,0,0.000000,362
31,cancelled,float64,0,0.000000,2
33,diverted,float64,0,0.000000,2
37,distance,float64,0,0.000000,1567

In [24]:
quality_report = pd.DataFrame({
    "column": df.columns,
    "dtype": df.dtypes.astype(str).values,
    "missing_count": df.isna().sum().values,
    "missing_percent": df.isna().mean().values * 100,
    "unique_count": df.nunique(dropna=False).values
})

quality_report.sort_values(
    "missing_percent",
    ascending=False
)

,column,dtype,missing_count,missing_percent,unique_count
32,cancellation_code,object,1784931,96.626809,5
42,late_aircraft_delay,float64,1462816,79.189191,1003
38,carrier_delay,float64,1462816,79.189191,1322
41,security_delay,float64,1462816,79.189191,147
40,nas_delay,float64,1462816,79.189191,617
39,weather_delay,float64,1462816,79.189191,883
36,air_time,float64,67057,3.630115,670
35,actual_elapsed_time,float64,67057,3.630115,707
29,arr_delay_new,float64,67048,3.629627,1536
28,arr_delay,float64,67048,3.629627,1623
30,arr_del15,float64,67048,3.629627,3
27,arr_time,float64,62950,3.407783,1441
25,taxi_in,float64,62950,3.407783,242
24,taxi_out,float64,61991,3.355868,185
21,dep_delay,float64,60974,3.300813,1582
23,dep_del15,float64,60974,3.300813,3
22,dep_delay_new,float64,60974,3.300813,1526
20,dep_time,float64,60784,3.290527,1437
34,crs_elapsed_time,float64,1,0.000054,522
2,month,int64,0,0.000000,3
1,quarter,int64,0,0.000000,1
0,year,int64,0,0.000000,1
7,branded_code_share,object,0,0.000000,13
6,mkt_unique_carrier,object,0,0.000000,9
5,fl_date,object,0,0.000000,90
4,day_of_week,int64,0,0.000000,7
3,day_of_month,int64,0,0.000000,31
10,mkt_carrier_fl_num,int64,0,0.000000,6582
9,mkt_carrier,object,0,0.000000,9
8,mkt_carrier_airline_id,int64,0,0.000000,9
19,crs_dep_time,int64,0,0.000000,1266
26,crs_arr_time,int64,0,0.000000,1364
16,dest_city_name,object,0,0.000000,356
17,dest_state_abr,object,0,0.000000,52
18,dest_state_nm,object,0,0.000000,52
12,origin_city_name,object,0,0.000000,356
11,origin,object,0,0.000000,362
13,origin_state_abr,object,0,0.000000,52
14,origin_state_nm,object,0,0.000000,52
15,dest,object,0,0.000000,362
31,cancelled,float64,0,0.000000,2
33,diverted,float64,0,0.000000,2
37,distance,float64,0,0.000000,1567

In [25]:
df["cancelled"].value_counts(dropna=False)

cancelled
0.0    1784931
1.0      62311
Name: count, dtype: int64

In [26]:
df["cancelled"].value_counts(normalize=True, dropna=False) * 100

cancelled
0.0    96.626809
1.0     3.373191
Name: proportion, dtype: float64

In [27]:
df["diverted"].value_counts(dropna=False)

diverted
0.0    1842505
1.0       4737
Name: count, dtype: int64

In [28]:
df["diverted"].value_counts(normalize=True, dropna=False) * 100

diverted
0.0    99.743564
1.0     0.256436
Name: proportion, dtype: float64

In [29]:
pd.crosstab(
    df["cancelled"],
    df["diverted"],
    margins=True
)

diverted       0.0   1.0      All
cancelled
0.0        1780194  4737  1784931
1.0          62311     0    62311
All        1842505  4737  1847242

In [30]:
df["cancellation_code"].value_counts(dropna=False)

cancellation_code
NaN    1784931
B        47348
A        10042
C         4852
D           69
Name: count, dtype: int64

In [31]:
cols = [
    "dep_time",
    "dep_delay",
    "dep_delay_new",
    "dep_del15",
    "taxi_out",
    "arr_time",
    "taxi_in",
    "arr_delay",
    "arr_delay_new",
    "arr_del15",
    "actual_elapsed_time",
    "air_time"
]

missing_by_cancelled = (
    df.groupby("cancelled")[cols]
      .apply(lambda x: x.isna().sum())
)

missing_by_cancelled

,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,arr_time,taxi_in,arr_delay,arr_delay_new,arr_del15,actual_elapsed_time,air_time
cancelled,,,,,,,,,,,,
0.0,0,0,0,0,0,639,639,4737,4737,4737,4746,4746
1.0,60784,60974,60974,60974,61991,62311,62311,62311,62311,62311,62311,62311

In [32]:
missing_pct_by_cancelled = (
    df.groupby("cancelled")[cols]
      .apply(lambda x: x.isna().mean() * 100)
)

missing_pct_by_cancelled

,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,arr_time,taxi_in,arr_delay,arr_delay_new,arr_del15,actual_elapsed_time,air_time
cancelled,,,,,,,,,,,,
0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0358,0.0358,0.265388,0.265388,0.265388,0.265893,0.265893
1.0,97.549389,97.854311,97.854311,97.854311,99.486447,100.0000,100.0000,100.000000,100.000000,100.000000,100.000000,100.000000

In [33]:
df[
    (df["cancelled"] == 0) &
    (df["dep_time"].isna())
].shape

(0, 43)

In [34]:
df[
    (df["cancelled"] == 0) &
    (df["dep_time"].isna())
].head(20)

Empty DataFrame
Columns: [year, quarter, month, day_of_month, day_of_week, fl_date, mkt_unique_carrier, branded_code_share, mkt_carrier_airline_id, mkt_carrier, mkt_carrier_fl_num, origin, origin_city_name, origin_state_abr, origin_state_nm, dest, dest_city_name, dest_state_abr, dest_state_nm, crs_dep_time, dep_time, dep_delay, dep_delay_new, dep_del15, taxi_out, taxi_in, crs_arr_time, arr_time, arr_delay, arr_delay_new, arr_del15, cancelled, cancellation_code, diverted, crs_elapsed_time, actual_elapsed_time, air_time, distance, carrier_delay, weather_delay, nas_delay, security_delay, late_aircraft_delay]
Index: []

[0 rows x 43 columns]

In [35]:
df[
    (df["cancelled"] == 0) &
    (df["arr_time"].isna())
].shape

(639, 43)

In [36]:
df[
    (df["cancelled"] == 0) &
    (df["arr_time"].isna())
]["diverted"].value_counts()

diverted
1.0    639
Name: count, dtype: int64

In [37]:
df[
    (df["cancelled"] == 0) &
    (df["air_time"].isna())
]["diverted"].value_counts()

diverted
1.0    4737
0.0       9
Name: count, dtype: int64

In [38]:
df[
    (df["cancelled"] == 0) &
    (df["air_time"].isna())
][
    [
        "cancelled",
        "diverted",
        "dep_time",
        "taxi_out",
        "arr_time",
        "taxi_in",
        "air_time",
        "actual_elapsed_time",
        "dep_delay",
        "arr_delay"
    ]
].head(20)

,cancelled,diverted,dep_time,taxi_out,arr_time,taxi_in,air_time,actual_elapsed_time,dep_delay,arr_delay
60,0.0,1.0,613.0,25.0,1930.0,11.0,NaN,NaN,-2.0,NaN
77,0.0,1.0,1928.0,34.0,928.0,9.0,NaN,NaN,-4.0,NaN
308,0.0,1.0,1307.0,12.0,2031.0,6.0,NaN,NaN,-5.0,NaN
530,0.0,1.0,2041.0,20.0,219.0,5.0,NaN,NaN,132.0,NaN
730,0.0,1.0,2108.0,31.0,126.0,8.0,NaN,NaN,26.0,NaN
886,0.0,1.0,853.0,11.0,1405.0,3.0,NaN,NaN,-2.0,NaN
994,0.0,1.0,819.0,17.0,1427.0,2.0,NaN,NaN,-6.0,NaN
1235,0.0,1.0,2006.0,32.0,48.0,5.0,NaN,NaN,71.0,NaN
1626,0.0,1.0,851.0,18.0,1624.0,4.0,NaN,NaN,-7.0,NaN
1664,0.0,1.0,833.0,58.0,1744.0,5.0,NaN,NaN,-4.0,NaN
1706,0.0,1.0,127.0,18.0,747.0,9.0,NaN,NaN,448.0,NaN
2128,0.0,1.0,821.0,15.0,1524.0,14.0,NaN,NaN,-4.0,NaN
2344,0.0,1.0,2053.0,20.0,134.0,7.0,NaN,NaN,6.0,NaN
2387,0.0,1.0,2306.0,16.0,623.0,9.0,NaN,NaN,25.0,NaN
2522,0.0,1.0,2225.0,18.0,908.0,9.0,NaN,NaN,30.0,NaN
3312,0.0,1.0,836.0,17.0,1639.0,4.0,NaN,NaN,11.0,NaN
3549,0.0,1.0,610.0,82.0,1252.0,6.0,NaN,NaN,-5.0,NaN
3901,0.0,1.0,2338.0,19.0,1405.0,3.0,NaN,NaN,46.0,NaN
3925,0.0,1.0,2001.0,14.0,2342.0,8.0,NaN,NaN,-10.0,NaN
3928,0.0,1.0,851.0,29.0,1906.0,5.0,NaN,NaN,18.0,NaN

In [39]:
df[
    (df["cancelled"] == 0) &
    (df["actual_elapsed_time"].isna())
]["diverted"].value_counts()

diverted
1.0    4737
0.0       9
Name: count, dtype: int64

In [40]:
df[(df["cancelled"] == 0) & (df["dep_time"].isna())].shape

(0, 43)

In [41]:
df[(df["cancelled"] == 0) & (df["arr_time"].isna())].shape

(639, 43)

In [42]:
df[
    (df["cancelled"] == 0) &
    (df["arr_time"].isna())
]["diverted"].value_counts()

diverted
1.0    639
Name: count, dtype: int64

In [43]:
df[
    (df["cancelled"] == 0) &
    (df["air_time"].isna())
]["diverted"].value_counts()

diverted
1.0    4737
0.0       9
Name: count, dtype: int64

In [44]:
df[
    (df["cancelled"] == 0) &
    (df["actual_elapsed_time"].isna())
]["diverted"].value_counts()

diverted
1.0    4737
0.0       9
Name: count, dtype: int64

In [45]:
df[
    (df["cancelled"] == 0) &
    (df["air_time"].isna())
][[
    "cancelled", "diverted", "dep_time", "taxi_out",
    "arr_time", "taxi_in", "air_time",
    "actual_elapsed_time", "dep_delay", "arr_delay"
]].head(20)

,cancelled,diverted,dep_time,taxi_out,arr_time,taxi_in,air_time,actual_elapsed_time,dep_delay,arr_delay
60,0.0,1.0,613.0,25.0,1930.0,11.0,NaN,NaN,-2.0,NaN
77,0.0,1.0,1928.0,34.0,928.0,9.0,NaN,NaN,-4.0,NaN
308,0.0,1.0,1307.0,12.0,2031.0,6.0,NaN,NaN,-5.0,NaN
530,0.0,1.0,2041.0,20.0,219.0,5.0,NaN,NaN,132.0,NaN
730,0.0,1.0,2108.0,31.0,126.0,8.0,NaN,NaN,26.0,NaN
886,0.0,1.0,853.0,11.0,1405.0,3.0,NaN,NaN,-2.0,NaN
994,0.0,1.0,819.0,17.0,1427.0,2.0,NaN,NaN,-6.0,NaN
1235,0.0,1.0,2006.0,32.0,48.0,5.0,NaN,NaN,71.0,NaN
1626,0.0,1.0,851.0,18.0,1624.0,4.0,NaN,NaN,-7.0,NaN
1664,0.0,1.0,833.0,58.0,1744.0,5.0,NaN,NaN,-4.0,NaN
1706,0.0,1.0,127.0,18.0,747.0,9.0,NaN,NaN,448.0,NaN
2128,0.0,1.0,821.0,15.0,1524.0,14.0,NaN,NaN,-4.0,NaN
2344,0.0,1.0,2053.0,20.0,134.0,7.0,NaN,NaN,6.0,NaN
2387,0.0,1.0,2306.0,16.0,623.0,9.0,NaN,NaN,25.0,NaN
2522,0.0,1.0,2225.0,18.0,908.0,9.0,NaN,NaN,30.0,NaN
3312,0.0,1.0,836.0,17.0,1639.0,4.0,NaN,NaN,11.0,NaN
3549,0.0,1.0,610.0,82.0,1252.0,6.0,NaN,NaN,-5.0,NaN
3901,0.0,1.0,2338.0,19.0,1405.0,3.0,NaN,NaN,46.0,NaN
3925,0.0,1.0,2001.0,14.0,2342.0,8.0,NaN,NaN,-10.0,NaN
3928,0.0,1.0,851.0,29.0,1906.0,5.0,NaN,NaN,18.0,NaN

In [46]:
suspicious_9 = df[
    (df["cancelled"] == 0) &
    (df["diverted"] == 0) &
    (df["air_time"].isna())
]

suspicious_9

,year,quarter,month,day_of_month,day_of_week,fl_date,mkt_unique_carrier,branded_code_share,mkt_carrier_airline_id,mkt_carrier,...,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
422251,2026,1,1,22,4,2026-01-22,DL,DL_CODESHARE,19790,DL,...,0.0,141.0,NaN,NaN,834.0,NaN,NaN,NaN,NaN,NaN
1353591,2026,1,3,9,1,2026-03-09,DL,DL_CODESHARE,19790,DL,...,0.0,128.0,NaN,NaN,636.0,NaN,NaN,NaN,NaN,NaN
1418120,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,...,0.0,120.0,NaN,NaN,489.0,NaN,NaN,NaN,NaN,NaN
1418485,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,...,0.0,114.0,NaN,NaN,533.0,21.0,0.0,0.0,0.0,0.0
1418486,2026,1,3,12,4,2026-03-12,DL,DL_CODESHARE,19790,DL,...,0.0,108.0,NaN,NaN,533.0,NaN,NaN,NaN,NaN,NaN
1441673,2026,1,3,13,5,2026-03-13,DL,DL_CODESHARE,19790,DL,...,0.0,99.0,NaN,NaN,301.0,NaN,NaN,NaN,NaN,NaN
1550400,2026,1,3,18,3,2026-03-18,DL,DL_CODESHARE,19790,DL,...,0.0,68.0,NaN,NaN,174.0,NaN,NaN,NaN,NaN,NaN
1595193,2026,1,3,20,5,2026-03-20,DL,DL_CODESHARE,19790,DL,...,0.0,125.0,NaN,NaN,542.0,NaN,NaN,NaN,NaN,NaN
1595582,2026,1,3,20,5,2026-03-20,DL,DL_CODESHARE,19790,DL,...,0.0,74.0,NaN,NaN,174.0,NaN,NaN,NaN,NaN,NaN

In [47]:
suspicious_9[
    [
        "fl_date",
        "mkt_carrier",
        "mkt_carrier_fl_num",
        "origin",
        "dest",
        "crs_dep_time",
        "dep_time",
        "dep_delay",
        "taxi_out",
        "crs_arr_time",
        "arr_time",
        "taxi_in",
        "arr_delay",
        "air_time",
        "actual_elapsed_time",
        "distance",
        "cancelled",
        "diverted"
    ]
]

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_dep_time,dep_time,dep_delay,taxi_out,crs_arr_time,arr_time,taxi_in,arr_delay,air_time,actual_elapsed_time,distance,cancelled,diverted
422251,2026-01-22,DL,5444,JAX,LGA,1208,1203.0,-5.0,17.0,1429,1415.0,10.0,-14.0,NaN,NaN,834.0,0.0,0.0
1353591,2026-03-09,DL,5200,CHS,JFK,1751,1742.0,-9.0,18.0,1959,1945.0,7.0,-14.0,NaN,NaN,636.0,0.0,0.0
1418120,2026-03-12,DL,4780,RDU,IND,1150,1148.0,-2.0,14.0,1350,1330.0,6.0,-20.0,NaN,NaN,489.0,0.0,0.0
1418485,2026-03-12,DL,5202,ATL,BMI,1025,1024.0,-1.0,43.0,1119,1140.0,7.0,21.0,NaN,NaN,533.0,0.0,0.0
1418486,2026-03-12,DL,5202,BMI,ATL,1202,1219.0,17.0,14.0,1450,1459.0,9.0,9.0,NaN,NaN,533.0,0.0,0.0
1441673,2026-03-13,DL,5509,JFK,BUF,1335,1330.0,-5.0,19.0,1514,1510.0,14.0,-4.0,NaN,NaN,301.0,0.0,0.0
1550400,2026-03-18,DL,4982,CWA,MSP,1619,1617.0,-2.0,14.0,1727,1720.0,7.0,-7.0,NaN,NaN,174.0,0.0,0.0
1595193,2026-03-20,DL,5049,JFK,CLT,1240,1232.0,-8.0,20.0,1445,1416.0,5.0,-29.0,NaN,NaN,542.0,0.0,0.0
1595582,2026-03-20,DL,5384,CWA,MSP,700,653.0,-7.0,15.0,814,750.0,8.0,-24.0,NaN,NaN,174.0,0.0,0.0

In [48]:
suspicious_9[
    [
        "air_time",
        "actual_elapsed_time",
        "arr_delay",
        "arr_delay_new",
        "arr_del15"
    ]
].isna()

         air_time  actual_elapsed_time  arr_delay  arr_delay_new  arr_del15
422251       True                 True      False          False      False
1353591      True                 True      False          False      False
1418120      True                 True      False          False      False
1418485      True                 True      False          False      False
1418486      True                 True      False          False      False
1441673      True                 True      False          False      False
1550400      True                 True      False          False      False
1595193      True                 True      False          False      False
1595582      True                 True      False          False      False

In [49]:
suspicious_9[
    ["fl_date", "mkt_carrier", "mkt_carrier_fl_num", "origin", "dest"]
].duplicated(keep=False)

422251     False
1353591    False
1418120    False
1418485    False
1418486    False
1441673    False
1550400    False
1595193    False
1595582    False
dtype: bool

In [50]:
df[
    df.set_index(
        ["fl_date", "mkt_carrier", "mkt_carrier_fl_num", "origin", "dest"]
    ).index.isin(
        suspicious_9.set_index(
            ["fl_date", "mkt_carrier", "mkt_carrier_fl_num", "origin", "dest"]
        ).index
    )
][
    [
        "fl_date",
        "mkt_carrier",
        "mkt_carrier_fl_num",
        "origin",
        "dest",
        "dep_time",
        "arr_time",
        "air_time",
        "actual_elapsed_time",
        "cancelled",
        "diverted"
    ]
]

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,dep_time,arr_time,air_time,actual_elapsed_time,cancelled,diverted
422251,2026-01-22,DL,5444,JAX,LGA,1203.0,1415.0,NaN,NaN,0.0,0.0
1353591,2026-03-09,DL,5200,CHS,JFK,1742.0,1945.0,NaN,NaN,0.0,0.0
1418120,2026-03-12,DL,4780,RDU,IND,1148.0,1330.0,NaN,NaN,0.0,0.0
1418485,2026-03-12,DL,5202,ATL,BMI,1024.0,1140.0,NaN,NaN,0.0,0.0
1418486,2026-03-12,DL,5202,BMI,ATL,1219.0,1459.0,NaN,NaN,0.0,0.0
1441673,2026-03-13,DL,5509,JFK,BUF,1330.0,1510.0,NaN,NaN,0.0,0.0
1550400,2026-03-18,DL,4982,CWA,MSP,1617.0,1720.0,NaN,NaN,0.0,0.0
1595193,2026-03-20,DL,5049,JFK,CLT,1232.0,1416.0,NaN,NaN,0.0,0.0
1595582,2026-03-20,DL,5384,CWA,MSP,653.0,750.0,NaN,NaN,0.0,0.0

In [51]:
suspicious_9 = df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0) &
    (df['dep_time'].notna()) &
    (df['arr_time'].notna()) &
    (df['arr_delay'].notna()) &
    (
        df['air_time'].isna() |
        df['actual_elapsed_time'].isna()
    )
].copy()

suspicious_9.shape

(9, 43)

In [52]:
suspicious_9.T

,422251,1353591,1418120,1418485,1418486,1441673,1550400,1595193,1595582
year,2026,2026,2026,2026,2026,2026,2026,2026,2026
quarter,1,1,1,1,1,1,1,1,1
month,1,3,3,3,3,3,3,3,3
day_of_month,22,9,12,12,12,13,18,20,20
day_of_week,4,1,4,4,4,5,3,5,5
fl_date,2026-01-22,2026-03-09,2026-03-12,2026-03-12,2026-03-12,2026-03-13,2026-03-18,2026-03-20,2026-03-20
mkt_unique_carrier,DL,DL,DL,DL,DL,DL,DL,DL,DL
branded_code_share,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE
mkt_carrier_airline_id,19790,19790,19790,19790,19790,19790,19790,19790,19790
mkt_carrier,DL,DL,DL,DL,DL,DL,DL,DL,DL
mkt_carrier_fl_num,5444,5200,4780,5202,5202,5509,4982,5049,5384
origin,JAX,CHS,RDU,ATL,BMI,JFK,CWA,JFK,CWA
origin_city_name,"Jacksonville, FL","Charleston, SC","Raleigh/Durham, NC","Atlanta, GA","Bloomington/Normal, IL","New York, NY","Mosinee, WI","New York, NY","Mosinee, WI"
origin_state_abr,FL,SC,NC,GA,IL,NY,WI,NY,WI
origin_state_nm,Florida,South Carolina,North Carolina,Georgia,Illinois,New York,Wisconsin,New York,Wisconsin
dest,LGA,JFK,IND,BMI,ATL,BUF,MSP,CLT,MSP
dest_city_name,"New York, NY","New York, NY","Indianapolis, IN","Bloomington/Normal, IL","Atlanta, GA","Buffalo, NY","Minneapolis, MN","Charlotte, NC","Minneapolis, MN"
dest_state_abr,NY,NY,IN,IL,GA,NY,MN,NC,MN
dest_state_nm,New York,New York,Indiana,Illinois,Georgia,New York,Minnesota,North Carolina,Minnesota
crs_dep_time,1208,1751,1150,1025,1202,1335,1619,1240,700
dep_time,1203.0,1742.0,1148.0,1024.0,1219.0,1330.0,1617.0,1232.0,653.0
dep_delay,-5.0,-9.0,-2.0,-1.0,17.0,-5.0,-2.0,-8.0,-7.0
dep_delay_new,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0
dep_del15,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
taxi_out,17.0,18.0,14.0,43.0,14.0,19.0,14.0,20.0,15.0
taxi_in,10.0,7.0,6.0,7.0,9.0,14.0,7.0,5.0,8.0
crs_arr_time,1429,1959,1350,1119,1450,1514,1727,1445,814
arr_time,1415.0,1945.0,1330.0,1140.0,1459.0,1510.0,1720.0,1416.0,750.0
arr_delay,-14.0,-14.0,-20.0,21.0,9.0,-4.0,-7.0,-29.0,-24.0
arr_delay_new,0.0,0.0,0.0,21.0,9.0,0.0,0.0,0.0,0.0
arr_del15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
cancelled,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cancellation_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diverted,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
crs_elapsed_time,141.0,128.0,120.0,114.0,108.0,99.0,68.0,125.0,74.0
actual_elapsed_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
air_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distance,834.0,636.0,489.0,533.0,533.0,301.0,174.0,542.0,174.0
carrier_delay,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN
weather_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
nas_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
security_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
late_aircraft_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [53]:
df['flight_status'] = 'COMPLETED'

df.loc[df['cancelled'] == 1, 'flight_status'] = 'CANCELLED'

df.loc[
    (df['cancelled'] == 0) & (df['diverted'] == 1),
    'flight_status'
] = 'DIVERTED'

In [54]:
df['flight_status'].value_counts()

flight_status
COMPLETED    1780194
CANCELLED      62311
DIVERTED        4737
Name: count, dtype: int64

In [55]:
cols = [
    'dep_time',
    'dep_delay',
    'dep_delay_new',
    'dep_del15',
    'taxi_out',
    'arr_time',
    'taxi_in',
    'arr_delay',
    'arr_delay_new',
    'arr_del15',
    'actual_elapsed_time',
    'air_time',
    'carrier_delay',
    'weather_delay',
    'nas_delay',
    'security_delay',
    'late_aircraft_delay'
]

missing_status = (
    df.groupby('flight_status')[cols]
      .apply(lambda x: x.isna().mean() * 100)
      .round(2)
)

missing_status

,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,arr_time,taxi_in,arr_delay,arr_delay_new,arr_del15,actual_elapsed_time,air_time,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
flight_status,,,,,,,,,,,,,,,,,
CANCELLED,97.55,97.85,97.85,97.85,99.49,100.00,100.00,100.0,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00
COMPLETED,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,78.41,78.41,78.41,78.41,78.41
DIVERTED,0.00,0.00,0.00,0.00,0.00,13.49,13.49,100.0,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00

In [58]:
suspicious_9[
    ['mkt_carrier', 'mkt_carrier_fl_num', 'origin', 'dest']
].value_counts()

mkt_carrier  mkt_carrier_fl_num  origin  dest
DL           4780                RDU     IND     1
             4982                CWA     MSP     1
             5049                JFK     CLT     1
             5200                CHS     JFK     1
             5202                ATL     BMI     1
                                 BMI     ATL     1
             5384                CWA     MSP     1
             5444                JAX     LGA     1
             5509                JFK     BUF     1
Name: count, dtype: int64

In [59]:
suspicious_9['mkt_carrier'].value_counts()

mkt_carrier
DL    9
Name: count, dtype: int64

In [60]:
suspicious_9['fl_date'].value_counts()

fl_date
2026-03-12    3
2026-03-20    2
2026-03-09    1
2026-01-22    1
2026-03-13    1
2026-03-18    1
Name: count, dtype: int64

In [61]:
df[
    (df['mkt_carrier'] == 'DL') &
    (df['cancelled'] == 0) &
    (df['diverted'] == 0)
][
    ['air_time', 'actual_elapsed_time']
].isna().sum()

air_time               9
actual_elapsed_time    9
dtype: int64

In [62]:
df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0)
].groupby('mkt_carrier')[
    ['air_time', 'actual_elapsed_time']
].apply(lambda x: x.isna().sum())

             air_time  actual_elapsed_time
mkt_carrier
AA                  0                    0
AS                  0                    0
B6                  0                    0
DL                  9                    9
F9                  0                    0
G4                  0                    0
NK                  0                    0
UA                  0                    0
WN                  0                    0

In [63]:
df['calculated_elapsed'] = (
    df['air_time']
    + df['taxi_out']
    + df['taxi_in']
)

In [64]:
elapsed_check = df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0) &
    df['actual_elapsed_time'].notna() &
    df['calculated_elapsed'].notna()
].copy()

elapsed_check['elapsed_difference'] = (
    elapsed_check['actual_elapsed_time']
    - elapsed_check['calculated_elapsed']
)

In [65]:
elapsed_check['elapsed_difference'].describe()

count    1780185.0
mean           0.0
std            0.0
min            0.0
25%            0.0
50%            0.0
75%            0.0
max            0.0
Name: elapsed_difference, dtype: float64

In [66]:
suspicious_9.shape

(9, 44)

In [67]:
suspicious_9.T

,422251,1353591,1418120,1418485,1418486,1441673,1550400,1595193,1595582
year,2026,2026,2026,2026,2026,2026,2026,2026,2026
quarter,1,1,1,1,1,1,1,1,1
month,1,3,3,3,3,3,3,3,3
day_of_month,22,9,12,12,12,13,18,20,20
day_of_week,4,1,4,4,4,5,3,5,5
fl_date,2026-01-22,2026-03-09,2026-03-12,2026-03-12,2026-03-12,2026-03-13,2026-03-18,2026-03-20,2026-03-20
mkt_unique_carrier,DL,DL,DL,DL,DL,DL,DL,DL,DL
branded_code_share,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE,DL_CODESHARE
mkt_carrier_airline_id,19790,19790,19790,19790,19790,19790,19790,19790,19790
mkt_carrier,DL,DL,DL,DL,DL,DL,DL,DL,DL
mkt_carrier_fl_num,5444,5200,4780,5202,5202,5509,4982,5049,5384
origin,JAX,CHS,RDU,ATL,BMI,JFK,CWA,JFK,CWA
origin_city_name,"Jacksonville, FL","Charleston, SC","Raleigh/Durham, NC","Atlanta, GA","Bloomington/Normal, IL","New York, NY","Mosinee, WI","New York, NY","Mosinee, WI"
origin_state_abr,FL,SC,NC,GA,IL,NY,WI,NY,WI
origin_state_nm,Florida,South Carolina,North Carolina,Georgia,Illinois,New York,Wisconsin,New York,Wisconsin
dest,LGA,JFK,IND,BMI,ATL,BUF,MSP,CLT,MSP
dest_city_name,"New York, NY","New York, NY","Indianapolis, IN","Bloomington/Normal, IL","Atlanta, GA","Buffalo, NY","Minneapolis, MN","Charlotte, NC","Minneapolis, MN"
dest_state_abr,NY,NY,IN,IL,GA,NY,MN,NC,MN
dest_state_nm,New York,New York,Indiana,Illinois,Georgia,New York,Minnesota,North Carolina,Minnesota
crs_dep_time,1208,1751,1150,1025,1202,1335,1619,1240,700
dep_time,1203.0,1742.0,1148.0,1024.0,1219.0,1330.0,1617.0,1232.0,653.0
dep_delay,-5.0,-9.0,-2.0,-1.0,17.0,-5.0,-2.0,-8.0,-7.0
dep_delay_new,0.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0
dep_del15,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
taxi_out,17.0,18.0,14.0,43.0,14.0,19.0,14.0,20.0,15.0
taxi_in,10.0,7.0,6.0,7.0,9.0,14.0,7.0,5.0,8.0
crs_arr_time,1429,1959,1350,1119,1450,1514,1727,1445,814
arr_time,1415.0,1945.0,1330.0,1140.0,1459.0,1510.0,1720.0,1416.0,750.0
arr_delay,-14.0,-14.0,-20.0,21.0,9.0,-4.0,-7.0,-29.0,-24.0
arr_delay_new,0.0,0.0,0.0,21.0,9.0,0.0,0.0,0.0,0.0
arr_del15,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
cancelled,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
cancellation_code,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
diverted,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
crs_elapsed_time,141.0,128.0,120.0,114.0,108.0,99.0,68.0,125.0,74.0
actual_elapsed_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
air_time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
distance,834.0,636.0,489.0,533.0,533.0,301.0,174.0,542.0,174.0
carrier_delay,NaN,NaN,NaN,21.0,NaN,NaN,NaN,NaN,NaN
weather_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
nas_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
security_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
late_aircraft_delay,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
flight_status,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED,COMPLETED

In [68]:
df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0)
].groupby('mkt_carrier')[
    ['air_time', 'actual_elapsed_time']
].apply(lambda x: x.isna().sum())

             air_time  actual_elapsed_time
mkt_carrier
AA                  0                    0
AS                  0                    0
B6                  0                    0
DL                  9                    9
F9                  0                    0
G4                  0                    0
NK                  0                    0
UA                  0                    0
WN                  0                    0

In [69]:
df['flight_status'] = 'COMPLETED'

df.loc[df['cancelled'] == 1, 'flight_status'] = 'CANCELLED'

df.loc[
    (df['cancelled'] == 0) & (df['diverted'] == 1),
    'flight_status'
] = 'DIVERTED'

In [70]:
df.groupby('flight_status')[cols].apply(
    lambda x: x.isna().mean() * 100
).round(2)

,dep_time,dep_delay,dep_delay_new,dep_del15,taxi_out,arr_time,taxi_in,arr_delay,arr_delay_new,arr_del15,actual_elapsed_time,air_time,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
flight_status,,,,,,,,,,,,,,,,,
CANCELLED,97.55,97.85,97.85,97.85,99.49,100.00,100.00,100.0,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00
COMPLETED,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,78.41,78.41,78.41,78.41,78.41
DIVERTED,0.00,0.00,0.00,0.00,0.00,13.49,13.49,100.0,100.0,100.0,100.0,100.0,100.00,100.00,100.00,100.00,100.00

In [71]:
suspicious_9[
    [
        'fl_date',
        'mkt_carrier',
        'mkt_carrier_fl_num',
        'origin',
        'dest',
        'crs_dep_time',
        'dep_time',
        'dep_delay',
        'taxi_out',
        'crs_arr_time',
        'arr_time',
        'taxi_in',
        'arr_delay',
        'air_time',
        'actual_elapsed_time',
        'crs_elapsed_time',
        'distance',
        'cancelled',
        'diverted'
    ]
]

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_dep_time,dep_time,dep_delay,taxi_out,crs_arr_time,arr_time,taxi_in,arr_delay,air_time,actual_elapsed_time,crs_elapsed_time,distance,cancelled,diverted
422251,2026-01-22,DL,5444,JAX,LGA,1208,1203.0,-5.0,17.0,1429,1415.0,10.0,-14.0,NaN,NaN,141.0,834.0,0.0,0.0
1353591,2026-03-09,DL,5200,CHS,JFK,1751,1742.0,-9.0,18.0,1959,1945.0,7.0,-14.0,NaN,NaN,128.0,636.0,0.0,0.0
1418120,2026-03-12,DL,4780,RDU,IND,1150,1148.0,-2.0,14.0,1350,1330.0,6.0,-20.0,NaN,NaN,120.0,489.0,0.0,0.0
1418485,2026-03-12,DL,5202,ATL,BMI,1025,1024.0,-1.0,43.0,1119,1140.0,7.0,21.0,NaN,NaN,114.0,533.0,0.0,0.0
1418486,2026-03-12,DL,5202,BMI,ATL,1202,1219.0,17.0,14.0,1450,1459.0,9.0,9.0,NaN,NaN,108.0,533.0,0.0,0.0
1441673,2026-03-13,DL,5509,JFK,BUF,1335,1330.0,-5.0,19.0,1514,1510.0,14.0,-4.0,NaN,NaN,99.0,301.0,0.0,0.0
1550400,2026-03-18,DL,4982,CWA,MSP,1619,1617.0,-2.0,14.0,1727,1720.0,7.0,-7.0,NaN,NaN,68.0,174.0,0.0,0.0
1595193,2026-03-20,DL,5049,JFK,CLT,1240,1232.0,-8.0,20.0,1445,1416.0,5.0,-29.0,NaN,NaN,125.0,542.0,0.0,0.0
1595582,2026-03-20,DL,5384,CWA,MSP,700,653.0,-7.0,15.0,814,750.0,8.0,-24.0,NaN,NaN,74.0,174.0,0.0,0.0

In [72]:
suspicious_9[['air_time', 'actual_elapsed_time']].isna().sum()

air_time               9
actual_elapsed_time    9
dtype: int64

In [73]:
suspicious_9[
    ['crs_elapsed_time', 'taxi_out', 'taxi_in', 'distance']
]

         crs_elapsed_time  taxi_out  taxi_in  distance
422251              141.0      17.0     10.0     834.0
1353591             128.0      18.0      7.0     636.0
1418120             120.0      14.0      6.0     489.0
1418485             114.0      43.0      7.0     533.0
1418486             108.0      14.0      9.0     533.0
1441673              99.0      19.0     14.0     301.0
1550400              68.0      14.0      7.0     174.0
1595193             125.0      20.0      5.0     542.0
1595582              74.0      15.0      8.0     174.0

In [74]:
suspicious = df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0) &
    (df['air_time'].isna()) &
    (df['actual_elapsed_time'].isna())
]

print("Suspicious rows:", len(suspicious))

suspicious[
    [
        'fl_date',
        'mkt_carrier',
        'mkt_carrier_fl_num',
        'origin',
        'dest',
        'crs_dep_time',
        'dep_time',
        'dep_delay',
        'taxi_out',
        'crs_arr_time',
        'arr_time',
        'taxi_in',
        'arr_delay',
        'crs_elapsed_time',
        'actual_elapsed_time',
        'air_time',
        'distance',
        'cancelled',
        'diverted'
    ]
]

Suspicious rows: 9

,fl_date,mkt_carrier,mkt_carrier_fl_num,origin,dest,crs_dep_time,dep_time,dep_delay,taxi_out,crs_arr_time,arr_time,taxi_in,arr_delay,crs_elapsed_time,actual_elapsed_time,air_time,distance,cancelled,diverted
422251,2026-01-22,DL,5444,JAX,LGA,1208,1203.0,-5.0,17.0,1429,1415.0,10.0,-14.0,141.0,NaN,NaN,834.0,0.0,0.0
1353591,2026-03-09,DL,5200,CHS,JFK,1751,1742.0,-9.0,18.0,1959,1945.0,7.0,-14.0,128.0,NaN,NaN,636.0,0.0,0.0
1418120,2026-03-12,DL,4780,RDU,IND,1150,1148.0,-2.0,14.0,1350,1330.0,6.0,-20.0,120.0,NaN,NaN,489.0,0.0,0.0
1418485,2026-03-12,DL,5202,ATL,BMI,1025,1024.0,-1.0,43.0,1119,1140.0,7.0,21.0,114.0,NaN,NaN,533.0,0.0,0.0
1418486,2026-03-12,DL,5202,BMI,ATL,1202,1219.0,17.0,14.0,1450,1459.0,9.0,9.0,108.0,NaN,NaN,533.0,0.0,0.0
1441673,2026-03-13,DL,5509,JFK,BUF,1335,1330.0,-5.0,19.0,1514,1510.0,14.0,-4.0,99.0,NaN,NaN,301.0,0.0,0.0
1550400,2026-03-18,DL,4982,CWA,MSP,1619,1617.0,-2.0,14.0,1727,1720.0,7.0,-7.0,68.0,NaN,NaN,174.0,0.0,0.0
1595193,2026-03-20,DL,5049,JFK,CLT,1240,1232.0,-8.0,20.0,1445,1416.0,5.0,-29.0,125.0,NaN,NaN,542.0,0.0,0.0
1595582,2026-03-20,DL,5384,CWA,MSP,700,653.0,-7.0,15.0,814,750.0,8.0,-24.0,74.0,NaN,NaN,174.0,0.0,0.0

In [75]:
suspicious[['crs_elapsed_time', 'taxi_out', 'taxi_in', 'distance']].isna().sum()

crs_elapsed_time    0
taxi_out            0
taxi_in             0
distance            0
dtype: int64

In [76]:
suspicious['calculated_elapsed'] = (
    suspicious['arr_delay']
    - suspicious['dep_delay']
    + suspicious['crs_elapsed_time']
)

C:\Users\bhupa\AppData\Local\Temp\ipykernel_26308\567913305.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  suspicious['calculated_elapsed'] = (

In [77]:
check = suspicious[
    ['dep_delay', 'dep_delay_new',
     'dep_del15',
     'arr_delay', 'arr_delay_new',
     'arr_del15']
].copy()

check

,dep_delay,dep_delay_new,dep_del15,arr_delay,arr_delay_new,arr_del15
422251,-5.0,0.0,0.0,-14.0,0.0,0.0
1353591,-9.0,0.0,0.0,-14.0,0.0,0.0
1418120,-2.0,0.0,0.0,-20.0,0.0,0.0
1418485,-1.0,0.0,0.0,21.0,21.0,1.0
1418486,17.0,17.0,1.0,9.0,9.0,0.0
1441673,-5.0,0.0,0.0,-4.0,0.0,0.0
1550400,-2.0,0.0,0.0,-7.0,0.0,0.0
1595193,-8.0,0.0,0.0,-29.0,0.0,0.0
1595582,-7.0,0.0,0.0,-24.0,0.0,0.0

In [78]:
# Check whether delay conversions are consistent

print("Departure delay mismatch:")
print(
    (check['dep_delay'].clip(lower=0) != check['dep_delay_new']).sum()
)

print("Arrival delay mismatch:")
print(
    (check['arr_delay'].clip(lower=0) != check['arr_delay_new']).sum()
)

Departure delay mismatch:
0
Arrival delay mismatch:
0

In [79]:
print("Departure 15-min flag values:")
print(check['dep_del15'].value_counts(dropna=False))

print("Arrival 15-min flag values:")
print(check['arr_del15'].value_counts(dropna=False))

Departure 15-min flag values:
dep_del15
0.0    8
1.0    1
Name: count, dtype: int64
Arrival 15-min flag values:
arr_del15
0.0    8
1.0    1
Name: count, dtype: int64

In [80]:
time_cols = [
    'crs_dep_time',
    'dep_time',
    'crs_arr_time',
    'arr_time'
]

suspicious[time_cols]

         crs_dep_time  dep_time  crs_arr_time  arr_time
422251           1208    1203.0          1429    1415.0
1353591          1751    1742.0          1959    1945.0
1418120          1150    1148.0          1350    1330.0
1418485          1025    1024.0          1119    1140.0
1418486          1202    1219.0          1450    1459.0
1441673          1335    1330.0          1514    1510.0
1550400          1619    1617.0          1727    1720.0
1595193          1240    1232.0          1445    1416.0
1595582           700     653.0           814     750.0

In [81]:
for col in time_cols:
    bad = suspicious[
        (suspicious[col] < 0) |
        (suspicious[col] > 2359) |
        (suspicious[col] % 100 >= 60)
    ]

    print(col, "invalid:", len(bad))

crs_dep_time invalid: 0
dep_time invalid: 0
crs_arr_time invalid: 0
arr_time invalid: 0

In [82]:
suspicious[
    ['crs_dep_time', 'dep_time', 'dep_delay']
]

         crs_dep_time  dep_time  dep_delay
422251           1208    1203.0       -5.0
1353591          1751    1742.0       -9.0
1418120          1150    1148.0       -2.0
1418485          1025    1024.0       -1.0
1418486          1202    1219.0       17.0
1441673          1335    1330.0       -5.0
1550400          1619    1617.0       -2.0
1595193          1240    1232.0       -8.0
1595582           700     653.0       -7.0

In [83]:
def hhmm_to_minutes(x):
    h = int(x) // 100
    m = int(x) % 100
    return h * 60 + m

test = suspicious[
    ['crs_dep_time', 'dep_time', 'dep_delay']
].copy()

test['crs_dep_min'] = test['crs_dep_time'].apply(hhmm_to_minutes)
test['dep_min'] = test['dep_time'].apply(hhmm_to_minutes)

test['calculated_dep_delay'] = (
    test['dep_min'] - test['crs_dep_min']
)

# Handle flights crossing midnight
test.loc[
    test['calculated_dep_delay'] < -720,
    'calculated_dep_delay'
] += 1440

test[['crs_dep_time', 'dep_time', 'dep_delay',
      'calculated_dep_delay']]

         crs_dep_time  dep_time  dep_delay  calculated_dep_delay
422251           1208    1203.0       -5.0                    -5
1353591          1751    1742.0       -9.0                    -9
1418120          1150    1148.0       -2.0                    -2
1418485          1025    1024.0       -1.0                    -1
1418486          1202    1219.0       17.0                    17
1441673          1335    1330.0       -5.0                    -5
1550400          1619    1617.0       -2.0                    -2
1595193          1240    1232.0       -8.0                    -8
1595582           700     653.0       -7.0                    -7

In [84]:
test['difference'] = (
    test['dep_delay'] - test['calculated_dep_delay']
)

test[['crs_dep_time', 'dep_time',
      'dep_delay', 'calculated_dep_delay',
      'difference']]

         crs_dep_time  dep_time  dep_delay  calculated_dep_delay  difference
422251           1208    1203.0       -5.0                    -5         0.0
1353591          1751    1742.0       -9.0                    -9         0.0
1418120          1150    1148.0       -2.0                    -2         0.0
1418485          1025    1024.0       -1.0                    -1         0.0
1418486          1202    1219.0       17.0                    17         0.0
1441673          1335    1330.0       -5.0                    -5         0.0
1550400          1619    1617.0       -2.0                    -2         0.0
1595193          1240    1232.0       -8.0                    -8         0.0
1595582           700     653.0       -7.0                    -7         0.0

In [86]:
check = suspicious[
    ['crs_arr_time', 'arr_time', 'arr_delay',
     'arr_delay_new', 'arr_del15']
].copy()

check

         crs_arr_time  arr_time  arr_delay  arr_delay_new  arr_del15
422251           1429    1415.0      -14.0            0.0        0.0
1353591          1959    1945.0      -14.0            0.0        0.0
1418120          1350    1330.0      -20.0            0.0        0.0
1418485          1119    1140.0       21.0           21.0        1.0
1418486          1450    1459.0        9.0            9.0        0.0
1441673          1514    1510.0       -4.0            0.0        0.0
1550400          1727    1720.0       -7.0            0.0        0.0
1595193          1445    1416.0      -29.0            0.0        0.0
1595582           814     750.0      -24.0            0.0        0.0

In [87]:
def calculate_arr_delay(row):
    if pd.isna(row['arr_time']) or pd.isna(row['crs_arr_time']):
        return np.nan

    sched = int(row['crs_arr_time'])
    actual = int(row['arr_time'])

    sched_h, sched_m = divmod(sched, 100)
    actual_h, actual_m = divmod(actual, 100)

    sched_minutes = sched_h * 60 + sched_m
    actual_minutes = actual_h * 60 + actual_m

    delay = actual_minutes - sched_minutes

    # Handle midnight crossing
    if delay < -720:
        delay += 1440
    elif delay > 720:
        delay -= 1440

    return delay


check['calculated_arr_delay'] = check.apply(
    calculate_arr_delay,
    axis=1
)

check['difference'] = (
    check['arr_delay'] - check['calculated_arr_delay']
)

check

,crs_arr_time,arr_time,arr_delay,arr_delay_new,arr_del15,calculated_arr_delay,difference
422251,1429,1415.0,-14.0,0.0,0.0,-14,0.0
1353591,1959,1945.0,-14.0,0.0,0.0,-14,0.0
1418120,1350,1330.0,-20.0,0.0,0.0,-20,0.0
1418485,1119,1140.0,21.0,21.0,1.0,21,0.0
1418486,1450,1459.0,9.0,9.0,0.0,9,0.0
1441673,1514,1510.0,-4.0,0.0,0.0,-4,0.0
1550400,1727,1720.0,-7.0,0.0,0.0,-7,0.0
1595193,1445,1416.0,-29.0,0.0,0.0,-29,0.0
1595582,814,750.0,-24.0,0.0,0.0,-24,0.0

In [88]:
print(
    "Arrival delay mismatches:",
    (check['difference'] != 0).sum()
)

print(
    check['difference'].value_counts(dropna=False)
)

Arrival delay mismatches: 0
difference
0.0    9
Name: count, dtype: int64

In [89]:
check = suspicious[
    ['dep_delay', 'dep_delay_new', 'dep_del15',
     'arr_delay', 'arr_delay_new', 'arr_del15']
]

In [91]:
check = suspicious[
    ['arr_delay', 'arr_delay_new']
].copy()

check['calculated_arr_delay_new'] = check['arr_delay'].clip(lower=0)

check['difference'] = (
    check['arr_delay_new'] -
    check['calculated_arr_delay_new']
)

check

         arr_delay  arr_delay_new  calculated_arr_delay_new  difference
422251       -14.0            0.0                       0.0         0.0
1353591      -14.0            0.0                       0.0         0.0
1418120      -20.0            0.0                       0.0         0.0
1418485       21.0           21.0                      21.0         0.0
1418486        9.0            9.0                       9.0         0.0
1441673       -4.0            0.0                       0.0         0.0
1550400       -7.0            0.0                       0.0         0.0
1595193      -29.0            0.0                       0.0         0.0
1595582      -24.0            0.0                       0.0         0.0

In [92]:
print(
    "arr_delay_new mismatches:",
    (check['difference'] != 0).sum()
)

print(
    check['difference'].value_counts(dropna=False)
)

arr_delay_new mismatches: 0
difference
0.0    9
Name: count, dtype: int64

In [93]:
df.shape

(1847242, 45)

In [96]:
check = suspicious[
    ['arr_delay', 'arr_del15']
].copy()

check['calculated_arr_del15'] = (
    check['arr_delay'] >= 15
).astype(float)

check['difference'] = (
    check['arr_del15'] -
    check['calculated_arr_del15']
)

check

         arr_delay  arr_del15  calculated_arr_del15  difference
422251       -14.0        0.0                   0.0         0.0
1353591      -14.0        0.0                   0.0         0.0
1418120      -20.0        0.0                   0.0         0.0
1418485       21.0        1.0                   1.0         0.0
1418486        9.0        0.0                   0.0         0.0
1441673       -4.0        0.0                   0.0         0.0
1550400       -7.0        0.0                   0.0         0.0
1595193      -29.0        0.0                   0.0         0.0
1595582      -24.0        0.0                   0.0         0.0

In [97]:
print(
    "arr_del15 mismatches:",
    (check['difference'] != 0).sum()
)

print(
    check['difference'].value_counts(dropna=False)
)

arr_del15 mismatches: 0
difference
0.0    9
Name: count, dtype: int64

In [98]:
check = suspicious[
    ['taxi_out', 'taxi_in']
].copy()

print("Invalid taxi_out:",
      (check['taxi_out'] < 0).sum())

print("Invalid taxi_in:",
      (check['taxi_in'] < 0).sum())

Invalid taxi_out: 0
Invalid taxi_in: 0

In [99]:
print(check.isna().sum())

taxi_out    0
taxi_in     0
dtype: int64

In [100]:
print(check.describe())

        taxi_out    taxi_in
count   9.000000   9.000000
mean   19.333333   8.111111
std     9.165151   2.666667
min    14.000000   5.000000
25%    14.000000   7.000000
50%    17.000000   7.000000
75%    19.000000   9.000000
max    43.000000  14.000000

In [101]:
check = df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0)
]

print(
    "Missing actual_elapsed_time:",
    check['actual_elapsed_time'].isna().sum()
)

print(
    "Missing percentage:",
    check['actual_elapsed_time'].isna().mean() * 100
)

Missing actual_elapsed_time: 9
Missing percentage: 0.0005055628768549944

In [102]:
check = df[
    (df['cancelled'] == 0) &
    (df['diverted'] == 0) &
    (df['actual_elapsed_time'].notna())
].copy()

check['calculated_elapsed'] = (
    check['taxi_out'] +
    check['air_time'] +
    check['taxi_in']
)

check['difference'] = (
    check['actual_elapsed_time'] -
    check['calculated_elapsed']
)

print(
    "Elapsed-time mismatches:",
    (check['difference'].abs() > 1).sum()
)

Elapsed-time mismatches: 0

In [103]:
check = suspicious[['dep_time', 'arr_time', 'taxi_out', 'taxi_in',
                    'actual_elapsed_time', 'air_time']].copy()

check

         dep_time  arr_time  taxi_out  taxi_in  actual_elapsed_time  air_time
422251     1203.0    1415.0      17.0     10.0                  NaN       NaN
1353591    1742.0    1945.0      18.0      7.0                  NaN       NaN
1418120    1148.0    1330.0      14.0      6.0                  NaN       NaN
1418485    1024.0    1140.0      43.0      7.0                  NaN       NaN
1418486    1219.0    1459.0      14.0      9.0                  NaN       NaN
1441673    1330.0    1510.0      19.0     14.0                  NaN       NaN
1550400    1617.0    1720.0      14.0      7.0                  NaN       NaN
1595193    1232.0    1416.0      20.0      5.0                  NaN       NaN
1595582     653.0     750.0      15.0      8.0                  NaN       NaN

In [104]:
check['calculated_air_time'] = (
    check['actual_elapsed_time']
    - check['taxi_out']
    - check['taxi_in']
)

check['difference'] = (
    check['air_time'] - check['calculated_air_time']
)

check

,dep_time,arr_time,taxi_out,taxi_in,actual_elapsed_time,air_time,calculated_air_time,difference
422251,1203.0,1415.0,17.0,10.0,NaN,NaN,NaN,NaN
1353591,1742.0,1945.0,18.0,7.0,NaN,NaN,NaN,NaN
1418120,1148.0,1330.0,14.0,6.0,NaN,NaN,NaN,NaN
1418485,1024.0,1140.0,43.0,7.0,NaN,NaN,NaN,NaN
1418486,1219.0,1459.0,14.0,9.0,NaN,NaN,NaN,NaN
1441673,1330.0,1510.0,19.0,14.0,NaN,NaN,NaN,NaN
1550400,1617.0,1720.0,14.0,7.0,NaN,NaN,NaN,NaN
1595193,1232.0,1416.0,20.0,5.0,NaN,NaN,NaN,NaN
1595582,653.0,750.0,15.0,8.0,NaN,NaN,NaN,NaN

In [105]:
print(
    "Air-time mismatches:",
    (check['difference'].abs() > 1).sum()
)

print(
    check['difference'].value_counts(dropna=False)
)

Air-time mismatches: 0
difference
NaN    9
Name: count, dtype: int64

In [106]:
delay_cols = [
    'carrier_delay',
    'weather_delay',
    'nas_delay',
    'security_delay',
    'late_aircraft_delay'
]

suspicious[delay_cols].isna().sum()

carrier_delay          8
weather_delay          8
nas_delay              8
security_delay         8
late_aircraft_delay    8
dtype: int64

In [107]:
delay_check = suspicious[
    ['arr_delay', 'arr_del15'] + delay_cols
].copy()

delay_check

,arr_delay,arr_del15,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
422251,-14.0,0.0,NaN,NaN,NaN,NaN,NaN
1353591,-14.0,0.0,NaN,NaN,NaN,NaN,NaN
1418120,-20.0,0.0,NaN,NaN,NaN,NaN,NaN
1418485,21.0,1.0,21.0,0.0,0.0,0.0,0.0
1418486,9.0,0.0,NaN,NaN,NaN,NaN,NaN
1441673,-4.0,0.0,NaN,NaN,NaN,NaN,NaN
1550400,-7.0,0.0,NaN,NaN,NaN,NaN,NaN
1595193,-29.0,0.0,NaN,NaN,NaN,NaN,NaN
1595582,-24.0,0.0,NaN,NaN,NaN,NaN,NaN

In [108]:
delay_check['total_delay_cause'] = delay_check[delay_cols].fillna(0).sum(axis=1)

delay_check[['arr_delay', 'arr_del15', 'total_delay_cause']]

         arr_delay  arr_del15  total_delay_cause
422251       -14.0        0.0                0.0
1353591      -14.0        0.0                0.0
1418120      -20.0        0.0                0.0
1418485       21.0        1.0               21.0
1418486        9.0        0.0                0.0
1441673       -4.0        0.0                0.0
1550400       -7.0        0.0                0.0
1595193      -29.0        0.0                0.0
1595582      -24.0        0.0                0.0

In [109]:
cancel_check = df[df['cancelled'] == 1][
    ['cancelled', 'dep_time', 'dep_delay',
     'taxi_out', 'arr_time', 'arr_delay',
     'actual_elapsed_time', 'air_time', 'diverted']
]

cancel_check.isna().sum()

cancelled                  0
dep_time               60784
dep_delay              60974
taxi_out               61991
arr_time               62311
arr_delay              62311
actual_elapsed_time    62311
air_time               62311
diverted                   0
dtype: int64

In [110]:
cancel_check[['dep_time', 'arr_time', 'air_time',
              'actual_elapsed_time', 'arr_delay']].notna().sum()

dep_time               1527
arr_time                  0
air_time                  0
actual_elapsed_time       0
arr_delay                 0
dtype: int64

In [111]:
cancel_code_check = df[df['cancelled'] == 1][
    ['cancelled', 'cancellation_code']
]

print(cancel_code_check['cancellation_code'].isna().sum())
print(cancel_code_check['cancellation_code'].value_counts(dropna=False))

0
cancellation_code
B    47348
A    10042
C     4852
D       69
Name: count, dtype: int64

In [112]:
print(
    df.loc[df['cancelled'] == 0, 'cancellation_code']
      .notna()
      .sum()
)

0

In [113]:
# Cancellation code should exist only for cancelled flights
invalid_cancel_codes = df[
    (df['cancelled'] == 0) &
    (df['cancellation_code'].notna())
]

print("Non-cancelled flights with cancellation code:",
      len(invalid_cancel_codes))

# Cancelled flights without cancellation code
missing_cancel_codes = df[
    (df['cancelled'] == 1) &
    (df['cancellation_code'].isna())
]

print("Cancelled flights without cancellation code:",
      len(missing_cancel_codes))

Non-cancelled flights with cancellation code: 0
Cancelled flights without cancellation code: 0

In [114]:
print(
    df.loc[df['cancelled'] == 1, 'cancellation_code']
      .value_counts(dropna=False)
)

cancellation_code
B    47348
A    10042
C     4852
D       69
Name: count, dtype: int64

In [115]:
divert_check = df[df['diverted'] == 1][
    ['cancelled', 'diverted', 'dep_time', 'arr_time',
     'air_time', 'actual_elapsed_time', 'arr_delay']
]

divert_check.isna().sum()

cancelled                 0
diverted                  0
dep_time                  0
arr_time                639
air_time               4737
actual_elapsed_time    4737
arr_delay              4737
dtype: int64

In [116]:
print("Diverted + Cancelled:",
      ((df['diverted'] == 1) & (df['cancelled'] == 1)).sum())

print("Diverted flights:",
      (df['diverted'] == 1).sum())

Diverted + Cancelled: 0
Diverted flights: 4737

In [117]:
print("Missing CRS elapsed:",
      df['crs_elapsed_time'].isna().sum())

Missing CRS elapsed: 1

In [118]:
print("Invalid CRS elapsed:",
      (df['crs_elapsed_time'] <= 0).sum())

print(df['crs_elapsed_time'].describe())

Invalid CRS elapsed: 8
count    1.847241e+06
mean     1.480702e+02
std      7.225527e+01
min     -8.500000e+01
25%      9.500000e+01
50%      1.310000e+02
75%      1.800000e+02
max      1.202000e+03
Name: crs_elapsed_time, dtype: float64

In [119]:
# Invalid CRS elapsed time
df.loc[
    (df['crs_elapsed_time'] <= 0) |
    (df['crs_elapsed_time'] > 1000),
    'crs_elapsed_time'
] = np.nan

In [120]:
df['crs_elapsed_time'].isna().sum()

np.int64(10)

In [121]:
# ==============================
# DATA QUALITY VALIDATION
# ==============================

quality_report = pd.DataFrame({
    'missing_count': df.isna().sum(),
    'missing_percent': df.isna().mean() * 100,
    'unique_count': df.nunique()
})

quality_report = quality_report.sort_values(
    'missing_percent',
    ascending=False
)

quality_report

                        missing_count  missing_percent  unique_count
cancellation_code             1784931        96.626809             4
weather_delay                 1462816        79.189191           882
carrier_delay                 1462816        79.189191          1321
late_aircraft_delay           1462816        79.189191          1002
nas_delay                     1462816        79.189191           616
security_delay                1462816        79.189191           146
air_time                        67057         3.630115           669
actual_elapsed_time             67057         3.630115           706
calculated_elapsed              67057         3.630115           706
arr_del15                       67048         3.629627             2
arr_delay_new                   67048         3.629627          1535
arr_delay                       67048         3.629627          1622
arr_time                        62950         3.407783          1440
taxi_in                         62950         3.407783           241
taxi_out                        61991         3.355868           184
dep_delay                       60974         3.300813          1581
dep_delay_new                   60974         3.300813          1525
dep_del15                       60974         3.300813             2
dep_time                        60784         3.290527          1436
crs_elapsed_time                   10         0.000541           513
mkt_carrier_airline_id              0         0.000000             9
day_of_week                         0         0.000000             7
day_of_month                        0         0.000000            31
month                               0         0.000000             3
quarter                             0         0.000000             1
year                                0         0.000000             1
branded_code_share                  0         0.000000            13
mkt_unique_carrier                  0         0.000000             9
fl_date                             0         0.000000            90
origin_city_name                    0         0.000000           356
origin                              0         0.000000           362
mkt_carrier_fl_num                  0         0.000000          6582
mkt_carrier                         0         0.000000             9
dest_city_name                      0         0.000000           356
dest_state_abr                      0         0.000000            52
dest_state_nm                       0         0.000000            52
crs_dep_time                        0         0.000000          1266
crs_arr_time                        0         0.000000          1364
origin_state_abr                    0         0.000000            52
dest                                0         0.000000           362
origin_state_nm                     0         0.000000            52
diverted                            0         0.000000             2
cancelled                           0         0.000000             2
distance                            0         0.000000          1567
flight_status                       0         0.000000             3

In [122]:
# Cancelled flights should not have operational flight times
cancelled_check = df['cancelled'].eq(1)

df.loc[cancelled_check, [
    'dep_time',
    'taxi_out',
    'arr_time',
    'taxi_in',
    'air_time',
    'actual_elapsed_time',
    'arr_delay'
]] = np.nan

In [123]:
diverted_check = df['diverted'].eq(1)

df.loc[diverted_check, [
    'air_time',
    'actual_elapsed_time',
    'arr_delay'
]] = np.nan

In [124]:
delay_cols = [
    'dep_delay',
    'dep_delay_new',
    'dep_del15',
    'arr_delay',
    'arr_delay_new',
    'arr_del15'
]

df[delay_cols].describe()

,dep_delay,dep_delay_new,dep_del15,arr_delay,arr_delay_new,arr_del15
count,1.786268e+06,1.786268e+06,1.786268e+06,1.780194e+06,1.780194e+06,1.780194e+06
mean,1.393807e+01,1.758626e+01,2.182478e-01,7.249089e+00,1.734560e+01,2.159461e-01
std,6.111301e+01,5.991430e+01,4.130566e-01,6.346866e+01,5.963412e+01,4.114772e-01
min,-6.600000e+01,0.000000e+00,0.000000e+00,-9.000000e+01,0.000000e+00,0.000000e+00
25%,-7.000000e+00,0.000000e+00,0.000000e+00,-1.800000e+01,0.000000e+00,0.000000e+00
50%,-2.000000e+00,0.000000e+00,0.000000e+00,-7.000000e+00,0.000000e+00,0.000000e+00
75%,1.000000e+01,1.000000e+01,0.000000e+00,1.000000e+01,1.000000e+01,0.000000e+00
max,3.339000e+03,3.339000e+03,1.000000e+00,3.339000e+03,3.339000e+03,1.000000e+00

In [125]:
# Negative values allowed for raw delay,
# but *_new and *_del15 should not be negative.
df[['dep_delay_new', 'arr_delay_new']].lt(0).sum()

dep_delay_new    0
arr_delay_new    0
dtype: int64

In [126]:
checks = {
    'Cancelled flights with dep_time':
        ((df['cancelled'] == 1) & df['dep_time'].notna()).sum(),

    'Cancelled flights with arr_time':
        ((df['cancelled'] == 1) & df['arr_time'].notna()).sum(),

    'Diverted + Cancelled':
        ((df['diverted'] == 1) & (df['cancelled'] == 1)).sum(),

    'Invalid taxi_out':
        ((df['taxi_out'] < 0) | (df['taxi_out'] > 300)).sum(),

    'Invalid taxi_in':
        ((df['taxi_in'] < 0) | (df['taxi_in'] > 300)).sum(),

    'Invalid CRS elapsed':
        ((df['crs_elapsed_time'] <= 0) |
         (df['crs_elapsed_time'] > 1000)).sum()
}

pd.Series(checks)

Cancelled flights with dep_time    0
Cancelled flights with arr_time    0
Diverted + Cancelled               0
Invalid taxi_out                   0
Invalid taxi_in                    5
Invalid CRS elapsed                0
dtype: int64

In [127]:
# ==============================
# BATCH NUMERIC VALIDATION
# ==============================

rules = {
    'taxi_out': (0, 300),
    'taxi_in': (0, 300),
    'crs_elapsed_time': (1, 1000),
    'actual_elapsed_time': (1, 1500),
    'air_time': (1, 1500),
    'distance': (1, 6000),
}

validation = {}

for col, (min_val, max_val) in rules.items():
    validation[col] = (
        ((df[col] < min_val) | (df[col] > max_val)).sum()
    )

pd.Series(validation, name='invalid_count')

taxi_out               0
taxi_in                5
crs_elapsed_time       0
actual_elapsed_time    0
air_time               0
distance               0
Name: invalid_count, dtype: int64

In [128]:
delay_cols = [
    'dep_delay',
    'dep_delay_new',
    'arr_delay',
    'arr_delay_new',
    'carrier_delay',
    'weather_delay',
    'nas_delay',
    'security_delay',
    'late_aircraft_delay'
]

delay_validation = pd.DataFrame({
    'missing': df[delay_cols].isna().sum(),
    'negative': df[delay_cols].lt(0).sum(),
    'zero': df[delay_cols].eq(0).sum(),
    'max': df[delay_cols].max()
})

delay_validation

                     missing  negative     zero     max
dep_delay              60974   1048051    65618  3339.0
dep_delay_new          60974         0  1113669  3339.0
arr_delay              67048   1114558    27898  3339.0
arr_delay_new          67048         0  1142456  3339.0
carrier_delay        1462816         0   173262  3339.0
weather_delay        1462816         0   359205  1958.0
nas_delay            1462816         0   194688  1560.0
security_delay       1462816         0   382821  1600.0
late_aircraft_delay  1462816         0   194172  2338.0

In [129]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0